In [ ]:
# problem I'm having is.. 
# I need to drop 'result' column to delete rows with all question mark 
# that is x_df that has 1895 rows 
# then the

In [28]:
import torch

In [29]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
NVIDIA GeForce RTX 3050 Ti Laptop GPU

In [30]:
!nvidia-smi

Wed Mar 19 18:21:19 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.124.04             Driver Version: 570.124.04     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   40C    P8              6W /   60W |      15MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            2422      G   /usr/bin/gnome-shell                      1MiB |
+-----------------------------------------------------------------------------------------+

In [31]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [88]:
# No truncating results
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns',None)

In [33]:
# Using Practice File for faster processing, swap it to original file for correct result. 
file_path = "/home/joong/orange/ece-5464/project_3/data/k8 _practicee.xlsx"

In [34]:
df = pd.read_excel(file_path, header= None)

In [63]:
df.shape

(1900, 5409)

In [36]:
# Renaming column referred from ChatGPT 4o
df.rename(columns={df.columns[-1]: "result"}, inplace=True)

In [37]:
print(df.columns)

Index([       0,        1,        2,        3,        4,        5,        6,
              7,        8,        9,
       ...
           5399,     5400,     5401,     5402,     5403,     5404,     5405,
           5406,     5407, 'result'],
      dtype='object', length=5409)

In [38]:
# Check for missing values
missing_values = df.isnull().sum()
print("Missing values per column:\n", missing_values)

Missing values per column:
 0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        0
29        0
30        0
31        0
32        0
33        0
34        0
35        0
36        0
37        0
38        0
39        0
40        0
41        0
42        0
43        0
44        0
45        0
46        0
47        0
48        0
49        0
50        0
51        0
52        0
53        0
54        0
55        0
56        0
57        0
58        0
59        0
60        0
61        0
62        0
63        0
64        0
65        0
66        0
67        0
68        0
69        0
70        0
71        0
72        0
73        0
74        0
75        0
76        0
77        0
78        0
79        0
80        0
81        0
82        0
83        0
84        0
85        0
86        0
87        0
88        0
89        0
90        0
91        0
92        0
93        0
94        0
95        0
96        0
97        0
98        0
99        0
100       0
101       0
102       0
103       0
104       0
105       0
106       0
107       0
108       0
109       0
110       0
111       0
112       0
113       0
114       0
115       0
116       0
117       0
118       0
119       0
120       0
121       0
122       0
123       0
124       0
125       0
126       0
127       0
128       0
129       0
130       0
131       0
132       0
133       0
134       0
135       0
136       0
137       0
138       0
139       0
140       0
141       0
142       0
143       0
144       0
145       0
146       0
147       0
148       0
149       0
150       0
151       0
152       0
153       0
154       0
155       0
156       0
157       0
158       0
159       0
160       0
161       0
162       0
163       0
164       0
165       0
166       0
167       0
168       0
169       0
170       0
171       0
172       0
173       0
174       0
175       0
176       0
177       0
178       0
179       0
180       0
181       0
182       0
183       0
184       0
185       0
186       0
187       0
188       0
189       0
190       0
191       0
192       0
193       0
194       0
195       0
196       0
197       0
198       0
199       0
200       0
201       0
202       0
203       0
204       0
205       0
206       0
207       0
208       0
209       0
210       0
211       0
212       0
213       0
214       0
215       0
216       0
217       0
218       0
219       0
220       0
221       0
222       0
223       0
224       0
225       0
226       0
227       0
228       0
229       0
230       0
231       0
232       0
233       0
234       0
235       0
236       0
237       0
238       0
239       0
240       0
241       0
242       0
243       0
244       0
245       0
246       0
247       0
248       0
249       0
250       0
251       0
252       0
253       0
254       0
255       0
256       0
257       0
258       0
259       0
260       0
261       0
262       0
263       0
264       0
265       0
266       0
267       0
268       0
269       0
270       0
271       0
272       0
273       0
274       0
275       0
276       0
277       0
278       0
279       0
280       0
281       0
282       0
283       0
284       0
285       0
286       0
287       0
288       0
289       0
290       0
291       0
292       0
293       0
294       0
295       0
296       0
297       0
298       0
299       0
300       0
301       0
302       0
303       0
304       0
305       0
306       0
307       0
308       0
309       0
310       0
311       0
312       0
313       0
314       0
315       0
316       0
317       0
318       0
319       0
320       0
321       0
322       0
323       0
324       0
325       0
326       0
327       0
328       0
329       0
330       0
331       0
332       0
333       0
334       0
335       0
336       0
337       0
338       0
339       0
340       0
341       0
342       0
343       0
344       0
345       0
346       0
347       0
348       0
349       0
350       0
351       0
352       0
353       0
354       0
355       0
356       0
357       0
358       0
359       0
360       0
361       0
362       0
363       0
364       0
365       0
366       0
367       0
368       0
369       0
370       0
371       0
372       0
373       0
374       0
375       0
376       0
377       0
378       0
379       0
380       0
381       0
382       0
383       0
384       0
385       0
386       0
387       0
388       0
389       0
390       0
391       0
392       0
393       0
394       0
395       0
396       0
397       0
398       0
399       0
400       0
401       0
402       0
403       0
404       0
405       0
406       0
407       0
408       0
409       0
410       0
411       0
412       0
413       0
414       0
415       0
416       0
417       0
418       0
419       0
420       0
421       0
422       0
423       0
424       0
425       0
426       0
427       0
428       0
429       0
430       0
431       0
432       0
433       0
434       0
435       0
436       0
437       0
438       0
439       0
440       0
441       0
442       0
443       0
444       0
445       0
446       0
447       0
448       0
449       0
450       0
451       0
452       0
453       0
454       0
455       0
456       0
457       0
458       0
459       0
460       0
461       0
462       0
463       0
464       0
465       0
466       0
467       0
468       0
469       0
470       0
471       0
472       0
473       0
474       0
475       0
476       0
477       0
478       0
479       0
480       0
481       0
482       0
483       0
484       0
485       0
486       0
487       0
488       0
489       0
490       0
491       0
492       0
493       0
494       0
495       0
496       0
497       0
498       0
499       0
500       0
501       0
502       0
503       0
504       0
505       0
506       0
507       0
508       0
509       0
510       0
511       0
512       0
513       0
514       0
515       0
516       0
517       0
518       0
519       0
520       0
521       0
522       0
523       0
524       0
525       0
526       0
527       0
528       0
529       0
530       0
531       0
532       0
533       0
534       0
535       0
536       0
537       0
538       0
539       0
540       0
541       0
542       0
543       0
544       0
545       0
546       0
547       0
548       0
549       0
550       0
551       0
552       0
553       0
554       0
555       0
556       0
557       0
558       0
559       0
560       0
561       0
562       0
563       0
564       0
565       0
566       0
567       0
568       0
569       0
570       0
571       0
572       0
573       0
574       0
575       0
576       0
577       0
578       0
579       0
580       0
581       0
582       0
583       0
584       0
585       0
586       0
587       0
588       0
589       0
590       0
591       0
592       0
593       0
594       0
595       0
596       0
597       0
598       0
599       0
600       0
601       0
602       0
603       0
604       0
605       0
606       0
607       0
608       0
609       0
610       0
611       0
612       0
613       0
614       0
615       0
616       0
617       0
618       0
619       0
620       0
621       0
622       0
623       0
624       0
625       0
626       0
627       0
628       0
629       0
630       0
631       0
632       0
633       0
634       0
635       0
636       0
637       0
638       0
639       0
640       0
641       0
642       0
643       0
644       0
645       0
646       0
647       0
648       0
649       0
650       0
651       0
652       0
653       0
654       0
655       0
656       0
657       0
658       0
659       0
660       0
661       0
662       0
663       0
664       0
665       0
666       0
667       0
668       0
669       0
670       0
671       0
672       0
673       0
674       0
675       0
676       0
677       0
678       0
679       0
680       0
681       0
682       0
683       0
684       0
685       0
686       0
687       0
688       0
689       0
690       0
691       0
692       0
693       0
694       0
695       0
696       0
697       0
698       0
699       0
700       0
701       0
702       0
703       0
704       0
705       0
706       0
707       0
708       0
709       0
710       0
711       0
712       0
713       0
714       0
715       0
716       0
717       0
718       0
719       0
720       0
721       0
722       0
723       0
724       0
725       0
726       0
727       0
728       0
729       0
730       0
731       0
732       0
733       0
734       0
735       0
736       0
737       0
738       0
739       0
740       0
741       0
742       0
743       0
744       0
745       0
746       0
747       0
748       0
749       0
750       0
751       0
752       0
753       0
754       0
755       0
756       0
757       0
758       0
759       0
760       0
761       0
762       0
763       0
764       0
765       0
766       0
767       0
768       0
769       0
770       0
771       0
772       0
773       0
774       0
775       0
776       0
777       0
778       0
779       0
780       0
781       0
782       0
783       0
784       0
785       0
786       0
787       0
788       0
789       0
790       0
791       0
792       0
793       0
794       0
795       0
796       0
797       0
798       0
799       0
800       0
801       0
802       0
803       0
804       0
805       0
806       0
807       0
808       0
809       0
810       0
811       0
812       0
813       0
814       0
815       0
816       0
817       0
818       0
819       0
820       0
821       0
822       0
823       0
824       0
825       0
826       0
827       0
828       0
829       0
830       0
831       0
832       0
833       0
834       0
835       0
836       0
837       0
838       0
839       0
840       0
841       0
842       0
843       0
844       0
845       0
846       0
847       0
848       0
849       0
850       0
851       0
852       0
853       0
854       0
855       0
856       0
857       0
858       0
859       0
860       0
861       0
862       0
863       0
864       0
865       0
866       0
867       0
868       0
869       0
870       0
871       0
872       0
873       0
874       0
875       0
876       0
877       0
878       0
879       0
880       0
881       0
882       0
883       0
884       0
885       0
886       0
887       0
888       0
889       0
890       0
891       0
892       0
893       0
894       0
895       0
896       0
897       0
898       0
899       0
900       0
901       0
902       0
903       0
904       0
905       0
906       0
907       0
908       0
909       0
910       0
911       0
912       0
913       0
914       0
915       0
916       0
917       0
918       0
919       0
920       0
921       0
922       0
923       0
924       0
925       0
926       0
927       0
928       0
929       0
930       0
931       0
932       0
933       0
934       0
935       0
936       0
937       0
938       0
939       0
940       0
941       0
942       0
943       0
944       0
945       0
946       0
947       0
948       0
949       0
950       0
951       0
952       0
953       0
954       0
955       0
956       0
957       0
958       0
959       0
960       0
961       0
962       0
963       0
964       0
965       0
966       0
967       0
968       0
969       0
970       0
971       0
972       0
973       0
974       0
975       0
976       0
977       0
978       0
979       0
980       0
981       0
982       0
983       0
984       0
985       0
986       0
987       0
988       0
989       0
990       0
991       0
992       0
993       0
994       0
995       0
996       0
997       0
998       0
999       0
1000      0
1001      0
1002      0
1003      0
1004      0
1005      0
1006      0
1007      0
1008      0
1009      0
1010      0
1011      0
1012      0
1013      0
1014      0
1015      0
1016      0
1017      0
1018      0
1019      0
1020      0
1021      0
1022      0
1023      0
1024      0
1025      0
1026      0
1027      0
1028      0
1029      0
1030      0
1031      0
1032      0
1033      0
1034      0
1035      0
1036      0
1037      0
1038      0
1039      0
1040      0
1041      0
1042      0
1043      0
1044      0
1045      0
1046      0
1047      0
1048      0
1049      0
1050      0
1051      0
1052      0
1053      0
1054      0
1055      0
1056      0
1057      0
1058      0
1059      0
1060      0
1061      0
1062      0
1063      0
1064      0
1065      0
1066      0
1067      0
1068      0
1069      0
1070      0
1071      0
1072      0
1073      0
1074      0
1075      0
1076      0
1077      0
1078      0
1079      0
1080      0
1081      0
1082      0
1083      0
1084      0
1085      0
1086      0
1087      0
1088      0
1089      0
1090      0
1091      0
1092      0
1093      0
1094      0
1095      0
1096      0
1097      0
1098      0
1099      0
1100      0
1101      0
1102      0
1103      0
1104      0
1105      0
1106      0
1107      0
1108      0
1109      0
1110      0
1111      0
1112      0
1113      0
1114      0
1115      0
1116      0
1117      0
1118      0
1119      0
1120      0
1121      0
1122      0
1123      0
1124      0
1125      0
1126      0
1127      0
1128      0
1129      0
1130      0
1131      0
1132      0
1133      0
1134      0
1135      0
1136      0
1137      0
1138      0
1139      0
1140      0
1141      0
1142      0
1143      0
1144      0
1145      0
1146      0
1147      0
1148      0
1149      0
1150      0
1151      0
1152      0
1153      0
1154      0
1155      0
1156      0
1157      0
1158      0
1159      0
1160      0
1161      0
1162      0
1163      0
1164      0
1165      0
1166      0
1167      0
1168      0
1169      0
1170      0
1171      0
1172      0
1173      0
1174      0
1175      0
1176      0
1177      0
1178      0
1179      0
1180      0
1181      0
1182      0
1183      0
1184      0
1185      0
1186      0
1187      0
1188      0
1189      0
1190      0
1191      0
1192      0
1193      0
1194      0
1195      0
1196      0
1197      0
1198      0
1199      0
1200      0
1201      0
1202      0
1203      0
1204      0
1205      0
1206      0
1207      0
1208      0
1209      0
1210      0
1211      0
1212      0
1213      0
1214      0
1215      0
1216      0
1217      0
1218      0
1219      0
1220      0
1221      0
1222      0
1223      0
1224      0
1225      0
1226      0
1227      0
1228      0
1229      0
1230      0
1231      0
1232      0
1233      0
1234      0
1235      0
1236      0
1237      0
1238      0
1239      0
1240      0
1241      0
1242      0
1243      0
1244      0
1245      0
1246      0
1247      0
1248      0
1249      0
1250      0
1251      0
1252      0
1253      0
1254      0
1255      0
1256      0
1257      0
1258      0
1259      0
1260      0
1261      0
1262      0
1263      0
1264      0
1265      0
1266      0
1267      0
1268      0
1269      0
1270      0
1271      0
1272      0
1273      0
1274      0
1275      0
1276      0
1277      0
1278      0
1279      0
1280      0
1281      0
1282      0
1283      0
1284      0
1285      0
1286      0
1287      0
1288      0
1289      0
1290      0
1291      0
1292      0
1293      0
1294      0
1295      0
1296      0
1297      0
1298      0
1299      0
1300      0
1301      0
1302      0
1303      0
1304      0
1305      0
1306      0
1307      0
1308      0
1309      0
1310      0
1311      0
1312      0
1313      0
1314      0
1315      0
1316      0
1317      0
1318      0
1319      0
1320      0
1321      0
1322      0
1323      0
1324      0
1325      0
1326      0
1327      0
1328      0
1329      0
1330      0
1331      0
1332      0
1333      0
1334      0
1335      0
1336      0
1337      0
1338      0
1339      0
1340      0
1341      0
1342      0
1343      0
1344      0
1345      0
1346      0
1347      0
1348      0
1349      0
1350      0
1351      0
1352      0
1353      0
1354      0
1355      0
1356      0
1357      0
1358      0
1359      0
1360      0
1361      0
1362      0
1363      0
1364      0
1365      0
1366      0
1367      0
1368      0
1369      0
1370      0
1371      0
1372      0
1373      0
1374      0
1375      0
1376      0
1377      0
1378      0
1379      0
1380      0
1381      0
1382      0
1383      0
1384      0
1385      0
1386      0
1387      0
1388      0
1389      0
1390      0
1391      0
1392      0
1393      0
1394      0
1395      0
1396      0
1397      0
1398      0
1399      0
1400      0
1401      0
1402      0
1403      0
1404      0
1405      0
1406      0
1407      0
1408      0
1409      0
1410      0
1411      0
1412      0
1413      0
1414      0
1415      0
1416      0
1417      0
1418      0
1419      0
1420      0
1421      0
1422      0
1423      0
1424      0
1425      0
1426      0
1427      0
1428      0
1429      0
1430      0
1431      0
1432      0
1433      0
1434      0
1435      0
1436      0
1437      0
1438      0
1439      0
1440      0
1441      0
1442      0
1443      0
1444      0
1445      0
1446      0
1447      0
1448      0
1449      0
1450      0
1451      0
1452      0
1453      0
1454      0
1455      0
1456      0
1457      0
1458      0
1459      0
1460      0
1461      0
1462      0
1463      0
1464      0
1465      0
1466      0
1467      0
1468      0
1469      0
1470      0
1471      0
1472      0
1473      0
1474      0
1475      0
1476      0
1477      0
1478      0
1479      0
1480      0
1481      0
1482      0
1483      0
1484      0
1485      0
1486      0
1487      0
1488      0
1489      0
1490      0
1491      0
1492      0
1493      0
1494      0
1495      0
1496      0
1497      0
1498      0
1499      0
1500      0
1501      0
1502      0
1503      0
1504      0
1505      0
1506      0
1507      0
1508      0
1509      0
1510      0
1511      0
1512      0
1513      0
1514      0
1515      0
1516      0
1517      0
1518      0
1519      0
1520      0
1521      0
1522      0
1523      0
1524      0
1525      0
1526      0
1527      0
1528      0
1529      0
1530      0
1531      0
1532      0
1533      0
1534      0
1535      0
1536      0
1537      0
1538      0
1539      0
1540      0
1541      0
1542      0
1543      0
1544      0
1545      0
1546      0
1547      0
1548      0
1549      0
1550      0
1551      0
1552      0
1553      0
1554      0
1555      0
1556      0
1557      0
1558      0
1559      0
1560      0
1561      0
1562      0
1563      0
1564      0
1565      0
1566      0
1567      0
1568      0
1569      0
1570      0
1571      0
1572      0
1573      0
1574      0
1575      0
1576      0
1577      0
1578      0
1579      0
1580      0
1581      0
1582      0
1583      0
1584      0
1585      0
1586      0
1587      0
1588      0
1589      0
1590      0
1591      0
1592      0
1593      0
1594      0
1595      0
1596      0
1597      0
1598      0
1599      0
1600      0
1601      0
1602      0
1603      0
1604      0
1605      0
1606      0
1607      0
1608      0
1609      0
1610      0
1611      0
1612      0
1613      0
1614      0
1615      0
1616      0
1617      0
1618      0
1619      0
1620      0
1621      0
1622      0
1623      0
1624      0
1625      0
1626      0
1627      0
1628      0
1629      0
1630      0
1631      0
1632      0
1633      0
1634      0
1635      0
1636      0
1637      0
1638      0
1639      0
1640      0
1641      0
1642      0
1643      0
1644      0
1645      0
1646      0
1647      0
1648      0
1649      0
1650      0
1651      0
1652      0
1653      0
1654      0
1655      0
1656      0
1657      0
1658      0
1659      0
1660      0
1661      0
1662      0
1663      0

In [39]:
# Check for "?" in the entire DataFrame
question_marks = df.map(lambda x: x == "?")

# Sum up how many "?" values are in each column
question_mark_count = question_marks.sum()

print("Number of '?' values per column:\n", question_mark_count)

Number of '?' values per column:
 0         32
1         32
2         32
3         32
4         32
5         32
6         32
7         32
8         32
9         32
10        32
11        32
12        32
13        32
14        32
15        32
16        32
17        32
18        32
19        32
20        32
21        32
22        32
23        32
24        32
25        32
26        32
27        32
28        32
29        32
30        32
31        32
32        32
33        32
34        32
35        32
36        32
37        32
38        32
39        32
40        32
41        32
42        32
43        32
44        32
45        32
46        32
47        32
48        32
49        32
50        32
51        32
52        32
53        32
54        32
55        32
56        32
57        32
58        32
59        32
60        32
61        32
62        32
63        32
64        32
65        32
66        32
67        32
68        32
69        32
70        32
71        32
72        32
73        32
74        32
75        32
76        32
77        32
78        32
79        32
80        32
81        32
82        32
83        32
84        32
85        32
86        32
87        32
88        32
89        32
90        32
91        32
92        32
93        32
94        32
95        32
96        32
97        32
98        32
99        32
100       32
101       32
102       32
103       32
104       32
105       32
106       32
107       32
108       32
109       32
110       32
111       32
112       32
113       32
114       32
115       32
116       32
117       32
118       32
119       32
120       32
121       32
122       32
123       32
124       32
125       32
126       32
127       32
128       32
129       32
130       32
131       32
132       32
133       32
134       32
135       32
136       32
137       32
138       32
139       32
140       32
141       32
142       32
143       32
144       32
145       32
146       32
147       32
148       32
149       32
150       32
151       32
152       32
153       32
154       32
155       32
156       32
157       32
158       32
159       32
160       32
161       32
162       32
163       32
164       32
165       32
166       32
167       32
168       32
169       32
170       32
171       32
172       32
173       32
174       32
175       32
176       32
177       32
178       32
179       32
180       32
181       32
182       32
183       32
184       32
185       32
186       32
187       32
188       32
189       32
190       32
191       32
192       32
193       32
194       32
195       32
196       32
197       32
198       32
199       32
200       32
201       32
202       32
203       32
204       32
205       32
206       32
207       32
208       32
209       32
210       32
211       32
212       32
213       32
214       32
215       32
216       32
217       32
218       32
219       32
220       32
221       32
222       32
223       32
224       32
225       32
226       32
227       32
228       32
229       32
230       32
231       32
232       32
233       32
234       32
235       32
236       32
237       32
238       32
239       32
240       32
241       32
242       32
243       32
244       32
245       32
246       32
247       32
248       32
249       32
250       32
251       32
252       32
253       32
254       32
255       32
256       32
257       32
258       32
259       32
260       32
261       32
262       32
263       32
264       32
265       32
266       32
267       32
268       32
269       32
270       32
271       32
272       32
273       32
274       32
275       32
276       32
277       32
278       32
279       32
280       32
281       32
282       32
283       32
284       32
285       32
286       32
287       32
288       32
289       32
290       32
291       32
292       32
293       32
294       32
295       32
296       32
297       32
298       32
299       32
300       32
301       32
302       32
303       32
304       32
305       32
306       32
307       32
308       32
309       32
310       32
311       32
312       32
313       32
314       32
315       32
316       32
317       32
318       32
319       32
320       32
321       32
322       32
323       32
324       32
325       32
326       32
327       32
328       32
329       32
330       32
331       32
332       32
333       32
334       32
335       32
336       32
337       32
338       32
339       32
340       32
341       32
342       32
343       32
344       32
345       32
346       32
347       32
348       32
349       32
350       32
351       32
352       32
353       32
354       32
355       32
356       32
357       32
358       32
359       32
360       32
361       32
362       32
363       32
364       32
365       32
366       32
367       32
368       32
369       32
370       32
371       32
372       32
373       32
374       32
375       32
376       32
377       32
378       32
379       32
380       32
381       32
382       32
383       32
384       32
385       32
386       32
387       32
388       32
389       32
390       32
391       32
392       32
393       32
394       32
395       32
396       32
397       32
398       32
399       32
400       32
401       32
402       32
403       32
404       32
405       32
406       32
407       32
408       32
409       32
410       32
411       32
412       32
413       32
414       32
415       32
416       32
417       32
418       32
419       32
420       32
421       32
422       32
423       32
424       32
425       32
426       32
427       32
428       32
429       32
430       32
431       32
432       32
433       32
434       32
435       32
436       32
437       32
438       32
439       32
440       32
441       32
442       32
443       32
444       32
445       32
446       32
447       32
448       32
449       32
450       32
451       32
452       32
453       32
454       32
455       32
456       32
457       32
458       32
459       32
460       32
461       32
462       32
463       32
464       32
465       32
466       32
467       32
468       32
469       32
470       32
471       32
472       32
473       32
474       32
475       32
476       32
477       32
478       32
479       32
480       32
481       32
482       32
483       32
484       32
485       32
486       32
487       32
488       32
489       32
490       32
491       32
492       32
493       32
494       32
495       32
496       32
497       32
498       32
499       32
500       32
501       32
502       32
503       32
504       32
505       32
506       32
507       32
508       32
509       32
510       32
511       32
512       32
513       32
514       32
515       32
516       32
517       32
518       32
519       32
520       32
521       32
522       32
523       32
524       32
525       32
526       32
527       32
528       32
529       32
530       32
531       32
532       32
533       32
534       32
535       32
536       32
537       32
538       32
539       32
540       32
541       32
542       32
543       32
544       32
545       32
546       32
547       32
548       32
549       32
550       32
551       32
552       32
553       32
554       32
555       32
556       32
557       32
558       32
559       32
560       32
561       32
562       32
563       32
564       32
565       32
566       32
567       32
568       32
569       32
570       32
571       32
572       32
573       32
574       32
575       32
576       32
577       32
578       32
579       32
580       32
581       32
582       32
583       32
584       32
585       32
586       32
587       32
588       32
589       32
590       32
591       32
592       32
593       32
594       32
595       32
596       32
597       32
598       32
599       32
600       32
601       32
602       32
603       32
604       32
605       32
606       32
607       32
608       32
609       32
610       32
611       32
612       32
613       32
614       32
615       32
616       32
617       32
618       32
619       32
620       32
621       32
622       32
623       32
624       32
625       32
626       32
627       32
628       32
629       32
630       32
631       32
632       32
633       32
634       32
635       32
636       32
637       32
638       32
639       32
640       32
641       32
642       32
643       32
644       32
645       32
646       32
647       32
648       32
649       32
650       32
651       32
652       32
653       32
654       32
655       32
656       32
657       32
658       32
659       32
660       32
661       32
662       32
663       32
664       32
665       32
666       32
667       32
668       32
669       32
670       32
671       32
672       32
673       32
674       32
675       32
676       32
677       32
678       32
679       32
680       32
681       32
682       32
683       32
684       32
685       32
686       32
687       32
688       32
689       32
690       32
691       32
692       32
693       32
694       32
695       32
696       32
697       32
698       32
699       32
700       32
701       32
702       32
703       32
704       32
705       32
706       32
707       32
708       32
709       32
710       32
711       32
712       32
713       32
714       32
715       32
716       32
717       32
718       32
719       32
720       32
721       32
722       32
723       32
724       32
725       32
726       32
727       32
728       32
729       32
730       32
731       32
732       32
733       32
734       32
735       32
736       32
737       32
738       32
739       32
740       32
741       32
742       32
743       32
744       32
745       32
746       32
747       32
748       32
749       32
750       32
751       32
752       32
753       32
754       32
755       32
756       32
757       32
758       32
759       32
760       32
761       32
762       32
763       32
764       32
765       32
766       32
767       32
768       32
769       32
770       32
771       32
772       32
773       32
774       32
775       32
776       32
777       32
778       32
779       32
780       32
781       32
782       32
783       32
784       32
785       32
786       32
787       32
788       32
789       32
790       32
791       32
792       32
793       32
794       32
795       32
796       32
797       32
798       32
799       32
800       32
801       32
802       32
803       32
804       32
805       32
806       32
807       32
808       32
809       32
810       32
811       32
812       32
813       32
814       32
815       32
816       32
817       32
818       32
819       32
820       32
821       32
822       32
823       32
824       32
825       32
826       32
827       32
828       32
829       32
830       32
831       32
832       32
833       32
834       32
835       32
836       32
837       32
838       32
839       32
840       32
841       32
842       32
843       32
844       32
845       32
846       32
847       32
848       32
849       32
850       32
851       32
852       32
853       32
854       32
855       32
856       32
857       32
858       32
859       32
860       32
861       32
862       32
863       32
864       32
865       32
866       32
867       32
868       32
869       32
870       32
871       32
872       32
873       32
874       32
875       32
876       32
877       32
878       32
879       32
880       32
881       32
882       32
883       32
884       32
885       32
886       32
887       32
888       32
889       32
890       32
891       32
892       32
893       32
894       32
895       32
896       32
897       32
898       32
899       32
900       32
901       32
902       32
903       32
904       32
905       32
906       32
907       32
908       32
909       32
910       32
911       32
912       32
913       32
914       32
915       32
916       32
917       32
918       32
919       32
920       32
921       32
922       32
923       32
924       32
925       32
926       32
927       32
928       32
929       32
930       32
931       32
932       32
933       32
934       32
935       32
936       32
937       32
938       32
939       32
940       32
941       32
942       32
943       32
944       32
945       32
946       32
947       32
948       32
949       32
950       32
951       32
952       32
953       32
954       32
955       32
956       32
957       32
958       32
959       32
960       32
961       32
962       32
963       32
964       32
965       32
966       32
967       32
968       32
969       32
970       32
971       32
972       32
973       32
974       32
975       32
976       32
977       32
978       32
979       32
980       32
981       32
982       32
983       32
984       32
985       32
986       32
987       32
988       32
989       32
990       32
991       32
992       32
993       32
994       32
995       32
996       32
997       32
998       32
999       32
1000      32
1001      32
1002      32
1003      32
1004      32
1005      32
1006      32
1007      32
1008      32
1009      32
1010      32
1011      32
1012      32
1013      32
1014      32
1015      32
1016      32
1017      32
1018      32
1019      32
1020      32
1021      32
1022      32
1023      32
1024      32
1025      32
1026      32
1027      32
1028      32
1029      32
1030      32
1031      32
1032      32
1033      32
1034      32
1035      32
1036      32
1037      32
1038      32
1039      32
1040      32
1041      32
1042      32
1043      32
1044      32
1045      32
1046      32
1047      32
1048      32
1049      32
1050      32
1051      32
1052      32
1053      32
1054      32
1055      32
1056      32
1057      32
1058      32
1059      32
1060      32
1061      32
1062      32
1063      32
1064      32
1065      32
1066      32
1067      32
1068      32
1069      32
1070      32
1071      32
1072      32
1073      32
1074      32
1075      32
1076      32
1077      32
1078      32
1079      32
1080      32
1081      32
1082      32
1083      32
1084      32
1085      32
1086      32
1087      32
1088      32
1089      32
1090      32
1091      32
1092      32
1093      32
1094      32
1095      32
1096      32
1097      32
1098      32
1099      32
1100      32
1101      32
1102      32
1103      32
1104      32
1105      32
1106      32
1107      32
1108      32
1109      32
1110      32
1111      32
1112      32
1113      32
1114      32
1115      32
1116      32
1117      32
1118      32
1119      32
1120      32
1121      32
1122      32
1123      32
1124      32
1125      32
1126      32
1127      32
1128      32
1129      32
1130      32
1131      32
1132      32
1133      32
1134      32
1135      32
1136      32
1137      32
1138      32
1139      32
1140      32
1141      32
1142      32
1143      32
1144      32
1145      32
1146      32
1147      32
1148      32
1149      32
1150      32
1151      32
1152      32
1153      32
1154      32
1155      32
1156      32
1157      32
1158      32
1159      32
1160      32
1161      32
1162      32
1163      32
1164      32
1165      32
1166      32
1167      32
1168      32
1169      32
1170      32
1171      32
1172      32
1173      32
1174      32
1175      32
1176      32
1177      32
1178      32
1179      32
1180      32
1181      32
1182      32
1183      32
1184      32
1185      32
1186      32
1187      32
1188      32
1189      32
1190      32
1191      32
1192      32
1193      32
1194      32
1195      32
1196      32
1197      32
1198      32
1199      32
1200      32
1201      32
1202      32
1203      32
1204      32
1205      32
1206      32
1207      32
1208      32
1209      32
1210      32
1211      32
1212      32
1213      32
1214      32
1215      32
1216      32
1217      32
1218      32
1219      32
1220      32
1221      32
1222      32
1223      32
1224      32
1225      32
1226      32
1227      32
1228      32
1229      32
1230      32
1231      32
1232      32
1233      32
1234      32
1235      32
1236      32
1237      32
1238      32
1239      32
1240      32
1241      32
1242      32
1243      32
1244      32
1245      32
1246      32
1247      32
1248      32
1249      32
1250      32
1251      32
1252      32
1253      32
1254      32
1255      32
1256      32
1257      32
1258      32
1259      32
1260      32
1261      32
1262      32
1263      32
1264      32
1265      32
1266      32
1267      32
1268      32
1269      32
1270      32
1271      32
1272      32
1273      32
1274      32
1275      32
1276      32
1277      32
1278      32
1279      32
1280      32
1281      32
1282      32
1283      32
1284      32
1285      32
1286      32
1287      32
1288      32
1289      32
1290      32
1291      32
1292      32
1293      32
1294      32
1295      32
1296      32
1297      32
1298      32
1299      32
1300      32
1301      32
1302      32
1303      32
1304      32
1305      32
1306      32
1307      32
1308      32
1309      32
1310      32
1311      32
1312      32
1313      32
1314      32
1315      32
1316      32
1317      32
1318      32
1319      32
1320      32
1321      32
1322      32
1323      32
1324      32
1325      32
1326      32
1327      32
1328      32
1329      32
1330      32
1331      32
1332      32
1333      32
1334      32
1335      32
1336      32
1337      32
1338      32
1339      32
1340      32
1341      32
1342      32
1343      32
1344      32
1345      32
1346      32
1347      32
1348      32
1349      32
1350      32
1351      32
1352      32
1353      32
1354      32
1355      32
1356      32
1357      32
1358      32
1359      32
1360      32
1361      32
1362      32
1363      32
1364      32
1365      32
1366      32
1367      32
1368      32
1369      32
1370      32
1371      32
1372      32
1373      32
1374      32
1375      32
1376      32
1377      32
1378      32
1379      32
1380      32
1381      32
1382      32
1383      32
1384      32
1385      32
1386      32
1387      32
1388      32
1389      32
1390      32
1391      32
1392      32
1393      32
1394      32
1395      32
1396      32
1397      32
1398      32
1399      32
1400      32
1401      32
1402      32
1403      32
1404      32
1405      32
1406      32
1407      32
1408      32
1409      32
1410      32
1411      32
1412      32
1413      32
1414      32
1415      32
1416      32
1417      32
1418      32
1419      32
1420      32
1421      32
1422      32
1423      32
1424      32
1425      32
1426      32
1427      32
1428      32
1429      32
1430      32
1431      32
1432      32
1433      32
1434      32
1435      32
1436      32
1437      32
1438      32
1439      32
1440      32
1441      32
1442      32
1443      32
1444      32
1445      32
1446      32
1447      32
1448      32
1449      32
1450      32
1451      32
1452      32
1453      32
1454      32
1455      32
1456      32
1457      32
1458      32
1459      32
1460      32
1461      32
1462      32
1463      32
1464      32
1465      32
1466      32
1467      32
1468      32
1469      32
1470      32
1471      32
1472      32
1473      32
1474      32
1475      32
1476      32
1477      32
1478      32
1479      32
1480      32
1481      32
1482      32
1483      32
1484      32
1485      32
1486      32
1487      32
1488      32
1489      32
1490      32
1491      32
1492      32
1493      32
1494      32
1495      32
1496      32
1497      32
1498      32
1499      32
1500      32
1501      32
1502      32
1503      32
1504      32
1505      32
1506      32
1507      32
1508      32
1509      32
1510      32
1511      32
1512      32
1513      32
1514      32
1515      32
1516      32
1517      32
1518      32
1519      32
1520      32
1521      32
1522      32
1523      32
1524      32
1525      32
1526      32
1527      32
1528      32
1529      32
1530      32
1531      32
1532      32
1533      32
1534      32

In [40]:
# how to drop rows with all "?"
# Referred from https://saturncloud.io/blog/how-to-drop-rows-with-all-zeros-in-pandas-dataframe/

In [92]:
x_df.head()

       0      1      2      3      4      5      6      7      8      9  \
0 -0.161 -0.014  0.002 -0.036 -0.033 -0.093  0.025  0.005  0.000 -0.015
1 -0.158 -0.002 -0.012 -0.025 -0.012 -0.106  0.013  0.005  0.000 -0.002
3 -0.169 -0.025 -0.010 -0.041 -0.045 -0.069  0.038  0.014  0.008 -0.014
4 -0.183 -0.051 -0.023 -0.077 -0.092 -0.015  0.071  0.027  0.020 -0.019
5 -0.154  0.005 -0.011 -0.013 -0.002 -0.115  0.005  0.002 -0.003  0.002

      10     11     12     13     14     15     16     17     18     19  \
0 -0.030 -0.050 -0.031 -0.036 -0.093 -0.008 -0.030 -0.023 -0.036 -0.042
1 -0.007 -0.010 -0.009 -0.017 -0.024  0.002  0.003 -0.011 -0.013 -0.010
3 -0.032 -0.043 -0.033 -0.046 -0.094 -0.017 -0.042 -0.022 -0.033 -0.039
4 -0.044 -0.097 -0.052 -0.079 -0.175 -0.040 -0.084 -0.030 -0.047 -0.058
5  0.006 -0.002 -0.004 -0.009 -0.011  0.006  0.015 -0.008 -0.009 -0.004

      20     21     22     23     24     25     26     27     28     29  \
0 -0.038 -0.036 -0.088 -0.102 -0.021 -0.031 -0.053 -0.257 -0.114 -0.075
1 -0.019 -0.017 -0.023 -0.044 -0.004 -0.019 -0.033 -0.187 -0.074 -0.057
3 -0.044 -0.040 -0.091 -0.132 -0.035 -0.036 -0.062 -0.258 -0.133 -0.097
4 -0.067 -0.063 -0.148 -0.228 -1.008 -0.058 -0.094 -0.315 -0.204 -0.156
5 -0.010 -0.011 -0.007 -0.016  0.005 -0.011 -0.022 -0.161 -0.058 -0.043

      30     31     32     33     34     35     36     37     38        39  \
0 -0.037  0.080  0.027 -0.161  0.056 -0.004  0.002  0.003 -0.033 -0.056133
1 -0.044  0.044  0.006 -0.146  0.009 -0.017 -0.009 -0.008 -0.029 -0.010433
3 -0.070  0.069  0.014 -0.177  0.053 -0.006 -0.002 -0.005 -0.031 -0.070167
4 -0.122  0.081  0.007 -0.204  0.084  0.003  0.000 -0.008 -0.028 -0.113500
5 -0.030  0.041  0.008 -0.133  0.000 -0.020 -0.012 -0.010 -0.029  0.000033

         40     41     42     43     44     45     46     47     48     49  \
0 -0.019444  0.016  0.004  0.038  0.028 -0.016 -0.027 -0.044 -0.055 -0.024
1  0.012889  0.023  0.022  0.026  0.060 -0.025  0.053 -0.053 -0.087 -0.029
3 -0.035333  0.006 -0.010  0.029 -0.013 -0.032 -0.030 -0.049 -0.084 -0.028
4 -0.114333 -0.002 -0.032  0.034 -0.073 -0.108 -0.066 -0.073 -0.166 -0.046
5  0.008278  0.018  0.010  0.043  0.050 -0.003 -0.011 -0.025 -0.014 -0.009

      50     51     52     53     54     55     56     57     58     59  \
0  0.016 -0.020 -0.019 -0.024  0.007 -0.046 -0.052  0.042 -0.059 -0.073
1 -0.075 -0.122 -0.363 -0.010  0.101  0.006 -0.104 -0.029 -0.240 -0.099
3 -0.012 -0.051 -0.377 -0.050  0.008 -0.071 -0.073  0.019 -0.040 -0.076
4 -0.038 -0.125 -0.423 -0.118 -0.030 -0.184 -0.133 -0.037 -0.089 -0.187
5  0.008 -0.006 -0.025 -0.019 -0.006 -0.027 -0.030  0.025 -0.110 -0.114

      60     61     62     63     64     65     66     67     68     69  \
0 -0.020  0.016 -0.018 -0.023 -0.039 -0.268 -0.036  0.015 -0.003 -0.019
1  0.027  0.120  0.086  0.199 -0.185 -0.640 -0.066  0.059  0.017  0.053
3 -0.040 -0.014 -0.034 -0.017 -0.043 -0.270 -0.033  0.000 -0.011 -0.024
4 -0.149 -0.121 -0.120 -0.124 -0.098 -0.478 -0.068 -0.062 -0.053 -0.078
5 -0.022  0.002 -0.021  0.017 -0.051 -0.444 -0.062  0.015 -0.027 -0.032

      70     71     72     73     74     75     76     77     78     79  \
0 -0.019 -0.053 -0.037 -0.002 -0.034 -0.031 -0.034 -0.025  0.018  0.008
1  0.084 -0.149 -0.047  0.049 -0.048 -0.012 -0.007 -0.003  0.071  0.048
3 -0.026 -0.050 -0.035  0.000 -0.023 -0.023 -0.028 -0.026  0.015  0.015
4 -0.082 -0.121 -0.107 -0.046 -0.034 -0.040 -0.047 -0.057 -0.064  0.054
5 -0.030 -0.078 -0.059 -0.007 -0.064 -0.049 -0.040 -0.026  0.005 -0.009

      80     81     82     83     84     85     86     87     88     89  \
0 -0.017 -0.042 -0.035 -0.065 -0.076  0.006 -0.024 -0.023 -0.048 -0.049
1 -0.045 -0.081 -0.029  0.093 -0.068 -0.048  0.006 -0.008 -0.012  0.006
3 -0.007 -0.028 -0.023 -0.069 -0.071  0.010 -0.056 -0.051 -0.050 -0.065
4 -0.030 -0.052 -0.052 -0.184 -0.089 -0.111 -0.116 -0.087 -0.096 -0.139
5 -0.031 -0.088 -0.056 -0.070 -0.081 -0.090  0.012 -0.011  0.003  0.028

      90     91     92     93     94     95     96     97     98     99  \
0 -0.049 -0.069 -0.026  0.049  0.049  0.025 -0.025  3.593  3.082  4.411
1 -0.007 -0.021 -0.010  0.036  0.024  0.014 -0.005  3.600  3.094  4.406
3 -0.047 -0.062 -0.025  0.060  0.053  0.020 -0.031  3.591  3.075  4.405
4 -0.097 -0.103 -0.039  0.036  0.076  0.019 -0.055  3.589  3.056  4.398
5  0.016 -0.008  0.004  0.071  0.046  0.036  0.018  0.043  2.910  0.005

     100    101    102    103    104    105       106       107       108  \
0  3.695  2.765  0.038  0.463  0.604  0.904 -0.144053  0.027000  0.085904
1  3.696  2.776  0.027  0.412  0.609  0.910 -0.172632  0.024812  0.082942
3  3.690  2.762  0.043  0.450  0.595  0.896 -0.158158  0.050250  0.146481
4  3.684  2.747 -0.963  0.444  0.574  0.872 -0.038211  0.045687  0.112500
5  3.103  2.495 -2.852 -2.116 -1.979  0.407 -0.178263  0.024250  0.022962

     109    110    111    112    113    114    115    116    117    118  \
0 -0.044 -0.003  0.034 -0.021 -0.024  0.033 -0.014  0.023 -0.035 -0.058
1 -0.042  0.006  0.041 -0.026 -0.011  0.005 -0.003 -0.013 -0.017 -0.047
3 -0.062  0.004  0.005 -0.032 -0.019  0.035 -0.013  0.010 -0.031 -0.049
4 -0.082 -0.005 -0.018 -0.075 -0.028  0.046 -0.021  0.005 -0.052 -0.061
5 -0.037  0.010  0.037 -0.029 -0.007  0.010  0.002 -0.014 -0.015 -0.040

     119    120    121    122    123    124    125    126    127    128  \
0 -0.063 -0.027  0.009 -0.076 -0.059 -0.035  0.009  0.082 -0.101 -0.100
1 -0.008 -0.007  0.015 -0.054 -0.044 -0.025  0.023  0.141 -0.051 -0.082
3 -0.041 -0.025  0.005 -0.075 -0.058 -0.037  0.009  0.088 -0.096 -0.097
4 -0.061 -0.040 -0.007 -0.095 -0.070 -0.049  0.002  0.064 -0.121 -0.098
5  0.001 -0.002  0.018 -0.044 -0.038 -0.020  0.025  0.063 -0.041 -0.078

     129    130    131       132       133     134       135       136    137  \
0  0.053  0.197 -0.021  0.032727 -0.006955  0.1020 -0.572514  0.009724  0.021
1  0.008  0.089 -0.038  0.035212 -0.005523  0.0475 -0.559914  0.008690  0.002
3  0.043  0.185 -0.033  0.041485 -0.013295  0.0960 -0.579429  0.007966  0.020
4  0.065  0.197 -0.039  0.057303 -0.025864  0.1300 -0.591600  0.002759  0.014
5  0.001  0.071 -0.037  0.031818 -0.002500  0.0390 -0.557514  0.010241  0.024

     138    139    140    141    142    143    144    145    146    147  \
0 -0.274 -0.011  0.013 -0.025 -0.037 -0.005  0.016  0.023  0.026 -0.045
1 -0.291  0.011  0.001 -0.042  0.002  0.014  0.014  0.023  0.069 -0.022
3  0.051 -0.012  0.019  0.036 -0.048 -0.013  0.010  0.034  0.044 -0.040
4  0.027 -0.027  0.039  0.035 -0.086 -0.032  0.012  0.046  0.046 -0.075
5  0.070  0.000  0.002  0.036 -0.005 -0.013  0.002  0.020  0.052 -0.005

     148    149    150    151    152    153    154    155    156    157  \
0  0.001  0.019  0.007  0.013 -0.034 -0.033  0.006  0.009  0.026  0.006
1  0.013  0.022 -0.011  0.011 -0.035  0.002  0.003 -0.004  0.001  0.000
3 -0.003  0.006  0.001  0.000 -0.078 -0.005  0.011  0.007  0.006  0.008
4  0.000  0.010  0.027  0.009 -0.089  0.015  0.033  0.025  0.021  0.022
5 -0.007 -0.007 -0.034 -0.016 -0.062  0.009 -0.014 -0.020 -0.024  0.001

     158    159       160    161    162    163    164    165    166    167  \
0  0.045  0.052  0.073167 -0.044 -0.018 -0.066 -0.064 -0.050 -0.028 -0.036
1  0.011  0.006  0.027333 -0.041 -0.017 -0.055 -0.048 -0.042 -0.021 -0.034
3  0.004  0.021  0.057500 -0.044 -0.027 -0.064 -0.054 -0.047 -0.032 -0.034
4  0.014  0.037  0.034167 -2.503 -0.013 -0.076 -0.061 -0.056 -0.043 -0.044
5 -0.015 -0.009  0.037500 -0.044 -0.012 -0.057 -0.054 -0.038 -0.015 -0.023

        168       169       170       171    172    173    174    175    176  \
0  0.001857 -0.018933 -0.035123  0.017667 -0.084  0.171  0.004  0.004 -0.002
1 -0.005714 -0.017533 -0.014308  0.006667  0.027 -0.022  0.014  0.019  0.008
3 -0.012800 -0.028133 -0.044062 -0.006833 -0.066 -0.043  0.009  0.001 -0.001
4 -0.025457  0.603633 -0.055246 -0.081333 -0.035  0.041  0.039 -0.014 -0.001
5 -0.000771 -0.015167 -0.007277 -0.008500 -0.021  0.235  0.013  0.026  0.010

     177    178    179    180    181    182    183    184    185    186  \
0  0.108  0.169 -0.156  0.013  0.007  0.013  0.029  0.063 -0.183  0.023
1  0.013  0.076 -0.150  0.021  0.011  0.021  0.026  0.058 -0.188  0.013
3  0.009  0.058 -0.200  0.007  0.004  0.012  0.024  0.036 -0.202  0.031
4  0.002  0.053 -0.302 -0.008  0.000  0.005  0.022  0.003 -0.224  0.050
5  0.117  0.164 -0.138  0.027  0.014  0.023  0.028  0.068 -0.183  0.010

     187    188    189    190    191    192    193    194    195    196  \
0  0.000  0.018  0.037  0.051 -0.152 -0.127 -0.029 -0.009 -0.015  0.001
1 -0.003  0.025  0.042  0.036 -0.167 -0.122 -0.071  0.017 -0.005  0.020
3  0.000  0.017  0.020  0.030 -0.161 -0.144  0.002 -0.009 -0.016  0.004
4  0.008  0.008 -0.025  0.010 -0.167 -0.182  0.109 -0.032 -0.008 -0.008
5 -0.004  0.027  0.044  0.041 -0.166 -0.107 -0.095  0.024 -0.001  0.021

     197    198    199    200    201    202    203    204    205    206  \
0  0.018  0.027  0.021  0.025  0.105  0.028 -0.150  0.021  0.005 -0.016
1  0.026  0.028  0.019  0.027  0.011  0.014 -0.151  0.022  0.020 -0.007
3  0.018  0.028  0.019  0.022  0.094  0.011 -0.174  0.001  0.004 -0.027
4  0.018  0.035  0.021  0.017  0.088 -0.006 -0.209 -0.028 -0.004 -0.048
5  0.022  0.023  0.018  0.029  0.011  0.019 -0.138  0.033  0.024  0.000

     207    208    209    210    211    212    213    214    215    216  \
0 -0.006  0.006 -0.003  0.017  0.029  0.185  0.022  0.040  0.001 -0.009
1  0.006  0.021  0.004  0.019  0.018  0.018  0.013  0.054  0.007  0.007
3 -0.014  0.002 -0.011  0.011  0.022  0.159  0.000  0.025 -0.025 -0.023
4 -0.032 -0.010 -0.036 -0.002  0.016  0.130 -0.036 -0.007 -0.064 -0.057
5  0.011  0.020  0.014  0.021  0.020  0.019  0.021  0.067  0.022  0.017

     217    218    219    220    221    222    223    224    225    226  \
0  0.025  0.026 -0.001 -0.029 -0.037  0.015  0.299  0.037 -0.004 -0.009
1  0.023  0.014 -0.007 -0.023 -0.010  0.010  0.296  0.031 -0.003  0.056
3  0.017  0.015 -0.036 -0.057 -0.054  0.008  0.275  0.025 -0.009 -0.020
4  0.000  0.006 -0.099 -0.113 -0.093  0.016  0.199 -0.006 -0.011 -0.065
5  0.027  0.015  0.005 -0.004  0.006  0.011  0.310  0.041  0.001  0.027

     227    228    229    230    231    232    233    234    235    236  \
0 -0.028 -0.042 -0.070 -0.061 -0.063 -0.019  0.031 -0.074 -0.110 -0.092
1 -0.035  0.009  0.000  0.005 -0.014 -0.016  0.024  0.033  0.016  0.006
3 -0.040 -0.039 -0.065 -0.065 -0.065 -0.076 -0.007 -0.072 -0.111 -0.096
4 -0.082 -0.052 -0.092 -0.103 -0.104 -0.120 -0.028 -0.104 -0.151 -0.147
5 -0.002 -0.033 -0.048 -0.020 -0.026 -0.029  0.010 -0.027 -0.048 -0.019

     237    238    239    240    241    242    243    244    245    246  \
0 -0.088  0.017 -0.037 -0.039 -0.080 -0.078  0.013 -0.023  0.009  0.021
1  0.006 -0.022 -0.044 -0.013  0.012 -0.004  0.004 -0.011  0.008  0.004
3 -0.087 -0.032  0.022  0.104 -0.085 -0.088 -0.013 -0.045  0.019  0.009
4 -0.131 -0.028 -0.012  0.060 -0.131 -0.143 -0.044 -0.088  0.046  0.033
5 -0.015 -0.045 -0.057 -0.002 -0.004  0.025  0.011 -0.003 -0.006 -0.012

     247    248    249    250    251    252    253    254    255    256  \
0  0.002 -0.043 -0.034 -0.051  0.086  0.008 -0.021 -0.015 -0.027 -0.064
1 -0.001 -0.017 -0.008  0.004  0.060 -0.011 -0.010 -0.001  0.009 -0.011
3 -0.014 -0.049 -0.042 -0.048  0.143 -0.016 -0.030 -0.023 -0.027 -0.059
4 -0.028 -0.079 -0.080 -0.093  0.350 -0.026 -0.048 -0.048 -0.061 -0.109
5 -0.003 -0.002  0.005  0.016  0.002 -0.029 -0.009  0.003  0.019  0.008

     257    258    259    260    261    262    263    264    265    266  \
0 -0.085  0.070  0.005 -0.025 -0.015 -0.023 -0.044 -0.061 -0.092 -0.062
1 -0.020  0.006 -0.002 -0.025 -0.011 -0.009 -0.020  0.000 -0.032 -0.036
3 -0.073  0.075 -0.001 -0.044 -0.022 -0.028 -0.045 -0.049 -0.083 -0.058
4 -0.125  0.100 -0.006 -0.074 -0.038 -0.050 -0.086 -0.089 -0.131 -0.079
5  0.004  0.002  0.002 -0.024 -0.008 -0.004 -0.006  0.018 -0.013 -0.034

     267    268    269    270    271    272    273    274    275    276  \
0  0.039 -0.024 -0.017 -0.053 -0.089  0.054  0.003 -0.011 -0.018  0.159
1  0.003 -0.005 -0.003 -0.031 -0.043  0.026  0.005 -0.011 -0.028 -0.028
3  0.036 -0.049 -0.020 -0.058 -0.099  0.122  0.006 -0.013 -0.028  0.146
4  0.053 -0.024 -0.044 -0.088 -0.152  0.162  0.011 -0.020 -0.040  0.100
5  0.019  0.003 -0.004 -0.020 -0.017  0.019  0.026  0.001 -0.004  0.180

     277    278    279    280    281    282    283    284    285    286  \
0 -0.055 -0.052 -0.013 -0.062 -0.397  0.023  0.010 -0.068 -0.100 -0.061
1 -0.023 -0.031 -0.047 -0.006  0.009 -0.029  0.030 -0.027 -0.046 -0.039
3 -0.064 -0.059 -0.022 -0.087 -0.107  0.014 -0.003 -0.068 -0.096 -0.060
4 -0.084 -0.090 -0.051 -0.158 -0.181  0.018 -0.046 -0.101 -0.125 -0.073
5 -0.052 -0.036 -0.017 -0.012 -0.018 -0.030  0.046 -0.020 -0.042 -0.039

     287    288    289    290    291    292    293    294    295    296  \
0 -0.479 -4.485 -0.058 -0.055 -0.171 -0.694 -4.222 -4.109 -0.072 -0.065
1 -0.469 -4.489 -0.022 -0.016 -0.147 -0.689 -4.238 -4.111 -0.084 -0.034
3 -0.481 -4.485 -0.062 -0.054 -0.173 -0.696 -4.224 -4.107 -0.086 -0.083
4 -0.493 -4.484 -0.094 -0.082 -0.192 -0.701 -4.219 -4.106 -0.101 -0.131
5 -0.468 -4.490 -0.011 -0.013 -0.143 -0.688 -4.239 -4.110 -0.093 -0.013

     297    298    299    300    301    302    303    304    305       306  \
0  0.003 -0.004  0.011 -0.033 -3.665 -2.676  0.025  0.075 -2.556  0.023846
1  0.006 -0.002 -0.001 -0.057 -3.725 -2.851  0.014  0.023 -2.645  0.027423
3 -0.012 -0.017  0.001 -0.031 -3.643 -2.769  0.016  0.054 -2.580  0.011077
4 -0.038 -0.043 -0.011 -0.145 -3.998 -2.806  0.011  0.052 -2.557 -0.007346
5  0.011  0.004  0.002 -0.060 -3.741 -2.841  0.018  0.022 -2.649  0.035000

        307     308      309    310    311    312    313    314    315    316  \
0 -0.103000  0.0100  0.01780  0.062 -0.051 -0.030 -0.011  0.012  0.005 -0.026
1 -0.054667  0.0135  0.02330  0.054 -0.071 -0.040 -0.011 -0.008 -0.014 -0.029
3 -0.099333  0.0095 -0.00882  0.060 -0.080 -0.050 -0.021 -0.006 -0.012 -0.030
4 -0.134333  0.0040 -0.02124  0.067 -0.104 -0.096 -0.039 -0.017 -0.026 -0.041
5 -0.057333  0.0120  0.03686  0.051 -0.047 -0.027 -0.005 -0.004 -0.013 -0.022

     317    318    319    320    321    322    323    324    325    326  \
0 -0.014 -0.011  0.002  0.011  2.551 -0.047 -0.046 -0.008  0.005  0.006
1 -0.038 -0.024 -0.004  0.003 -0.002 -0.032 -0.046 -0.021  0.003  0.001
3 -0.036 -0.027 -0.006  0.001 -0.002 -0.043 -0.061 -0.020  0.002 -0.001
4 -0.065 -0.049 -0.017 -0.011 -0.017 -0.051 -0.095 -0.038 -0.002 -0.010
5 -0.027 -0.015  0.000  0.004  0.000 -0.025 -0.032 -0.014  0.005  0.005

     327    328    329    330    331    332    333    334    335    336  \
0  0.015  0.002 -0.076 -0.037 -0.016 -0.001 -0.003 -0.001 -0.001 -0.118
1  0.004  0.007 -0.042 -0.043 -0.021  0.001  0.000  0.000  0.003 -0.039
3  0.000 -0.006 -0.074 -0.052 -0.028 -0.002 -0.008 -0.010 -0.012 -0.060
4 -0.019 -0.016 -0.099 -0.082 -0.050 -0.007 -0.017 -0.030 -0.035 -0.086
5  0.008  0.013 -0.031 -0.029 -0.011  0.004  0.004  0.005  0.014 -0.027

     337    338    339    340    341    342    343    344    345    346  \
0 -0.008 -0.003 -0.002  3.024 -0.030 -0.019 -0.015 -0.024 -0.442 -0.001
1  0.003  0.006  0.005  2.952  0.001  0.008  0.006 -0.004 -0.366  0.009
3 -0.012  0.000 -0.004  3.031 -0.032 -0.016 -0.004 -0.027 -0.089 -0.019
4 -0.026  0.000 -0.012 -0.033 -0.036 -0.030  0.012 -0.056 -0.056 -0.046
5  0.006  0.007  0.009  2.974  0.007  0.019  0.009  0.008 -0.362  0.017

     347    348    349    350    351    352    353    354    355    356  \
0 -0.198  0.235  0.199  0.074 -0.220  0.069 -0.016  0.102  0.028  0.028
1 -0.123  0.291  0.113  0.056 -0.385  0.051 -0.025  0.036  0.012  0.035
3 -0.233  0.268  0.190  0.051 -0.232  0.063 -0.020  0.098  0.033  0.040
4 -0.319  0.387  0.207  0.025 -0.105 -0.109 -0.066 -0.005 -0.011 -0.010
5 -0.008  0.270  0.115  0.068 -0.024 -0.171 -0.006  0.109 -0.007  0.064

     357    358    359    360    361    362    363    364    365    366  \
0  0.026  0.621  0.060  0.020 -0.008 -0.076 -0.035  0.021 -0.019  0.004
1  0.034  0.086  0.000 -0.005 -0.007  0.041  0.033  0.012  0.065  0.015
3  0.037  0.607  0.061  0.024 -0.005 -0.040 -0.032  0.008 -0.029 -0.004
4  0.001  0.534  0.042  0.030 -0.012 -0.030 -0.054 -0.011 -0.086 -0.040
5  0.033  0.609  0.063  0.020  0.013  0.069  0.029  0.011 -0.024 -0.001

     367    368    369    370    371    372    373    374    375    376  \
0 -0.007  0.000  0.005  1.038 -0.014 -0.011 -0.023 -0.041 -0.031  0.064
1 -0.016 -0.011 -0.004  0.992 -0.014 -0.022 -0.014 -0.009  0.000  0.017
3 -0.011 -0.008  0.001  1.051 -0.023 -0.014 -0.023 -0.046 -0.031  0.051
4 -0.014 -0.013  0.021  1.180 -0.060 -0.017 -0.030 -0.088 -0.051  0.021
5 -0.001 -0.004  0.011  0.949 -0.012 -0.010  0.002 -0.009  0.001 -0.024

     377    378    379    380    381    382    383    384    385    386  \
0 -0.046 -0.049 -0.043 -0.033 -0.028 -0.036 -0.027 -0.049 -0.074 -0.049
1 -0.004 -0.019 -0.018 -0.012 -0.009  0.001 -0.012 -0.036 -0.024 -0.014
3 -0.035 -0.047 -0.043 -0.030 -0.035 -0.047 -0.024 -0.048 -0.065 -0.048
4 -0.047 -0.074 -0.051 -0.039 -0.056 -0.097  0.007 -0.048 -0.109 -0.087
5 -0.025 -0.014 -0.001 -0.003 -0.006 -0.009 -0.011 -0.038 -0.025 -0.007

     387    388    389    390    391    392    393    394    395    396  \
0 -0.047 -0.025 -0.008 -0.014 -0.030 -0.052 -0.028  0.049 -0.102 -0.029
1 -0.015 -0.009  0.000 -0.033 -0.006 -0.016 -0.008  0.016 -0.029  0.009
3 -0.047 -0.033 -0.019 -0.018 -0.030 -0.054 -0.034  0.029 -0.099 -0.027
4 -0.064 -0.050 -0.040  0.008 -0.087 -0.085 -0.057  0.040 -0.110 -0.057
5 -0.002 -0.002 -0.009 -0.036 -0.012 -0.011 -0.008  0.020  0.007  0.006

     397    398    399    400    401    402    403    404    405    406  \
0  0.063 -0.041 -0.023 -0.006 -0.003 -0.014  0.024  0.012 -0.012 -0.018
1  0.041 -0.027 -0.002  0.011  0.014  0.010 -0.005  0.006 -0.002 -0.008
3  0.028 -0.055 -0.024 -0.010 -0.004 -0.014  0.038  0.017  0.004 -0.015
4 -0.008 -0.125 -0.161 -0.164  0.076 -0.110  0.060 -0.018  0.087 -0.055
5  0.026 -0.051 -0.079 -0.080 -0.042 -0.082  0.116 -0.008  0.126 -0.035

     407    408    409    410    411    412    413    414    415    416  \
0  0.044  0.065  0.022 -0.002  0.059  0.042 -0.017  0.027  0.189  0.147
1  0.050  0.067  0.021 -0.003  0.056  0.043 -0.017  0.005  0.183  0.040
3  0.058  0.085  0.033  0.005  0.065  0.046 -0.024  0.012  0.195  0.150
4  0.038  0.092  0.075  0.003  0.064  0.054 -0.187 -0.304  0.219  0.157
5  0.051  0.086  0.096  0.055  0.051  0.047 -0.100 -0.166  0.174  0.034

     417    418    419    420    421    422    423    424    425    426  \
0  0.021  0.008 -0.004  0.621  0.046 -0.001 -0.027 -0.012 -0.015  0.042
1  0.014  0.001 -0.010  0.609  0.004 -0.018 -0.026 -0.012 -0.008  0.015
3  0.022  0.008 -0.019  0.626  0.046 -0.004 -0.030 -0.016 -0.014  0.024
4  0.019  0.011 -0.185 -0.340  0.049 -0.022 -0.056 -0.052 -0.034 -0.054
5  0.008  0.002 -0.097 -0.206 -0.004 -0.034 -0.039 -0.027 -0.014 -0.020

     427    428    429    430    431    432    433    434    435    436  \
0  0.063 -0.039 -0.151 -0.130 -0.127 -0.017 -0.050 -0.007 -0.079 -0.423
1  0.054 -0.031 -0.148 -0.128 -0.125 -0.004 -0.043 -0.021 -0.071 -0.414
3  0.045 -0.037 -0.148 -0.135 -0.132 -0.018 -0.047 -0.012 -0.077 -0.422
4 -0.301 -0.024  0.005 -0.045 -0.061 -0.069 -0.019 -0.013 -0.026 -0.031
5 -0.279 -0.027 -0.129 -0.144 -0.144 -0.024 -0.037 -0.029 -0.071 -0.411

     437    438    439    440    441    442    443    444    445    446  \
0 -0.238 -0.008 -0.050  0.012 -0.084 -0.023 -0.007 -0.196  0.008 -0.017
1 -0.227  0.003 -0.040  0.024 -0.066 -0.009  0.015 -0.182  0.018 -0.009
3 -0.244 -0.014 -0.051  0.011 -0.084 -0.026 -0.007 -0.194  0.007 -0.021
4 -0.054 -0.069 -0.113 -0.042 -0.061 -0.052 -0.047 -0.197 -0.040 -0.052
5 -0.244 -0.040 -0.071  0.003 -0.071 -0.008  0.002 -0.174 -0.003 -0.016

     447       448    449    450    451    452    453    454    455    456  \
0 -0.018  0.013176  1.221  0.048  0.134 -0.015  0.028 -0.006 -0.051  0.034

In [93]:
df.head()

       0      1      2      3      4      5      6      7      8      9  \
0 -0.161 -0.014  0.002 -0.036 -0.033 -0.093  0.025  0.005      0 -0.015
1 -0.158 -0.002 -0.012 -0.025 -0.012 -0.106  0.013  0.005      0 -0.002
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.169 -0.025  -0.01 -0.041 -0.045 -0.069  0.038  0.014  0.008 -0.014
4 -0.183 -0.051 -0.023 -0.077 -0.092 -0.015  0.071  0.027   0.02 -0.019

      10     11     12     13     14     15     16     17     18     19  \
0  -0.03  -0.05 -0.031 -0.036 -0.093 -0.008  -0.03 -0.023 -0.036 -0.042
1 -0.007  -0.01 -0.009 -0.017 -0.024  0.002  0.003 -0.011 -0.013  -0.01
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.032 -0.043 -0.033 -0.046 -0.094 -0.017 -0.042 -0.022 -0.033 -0.039
4 -0.044 -0.097 -0.052 -0.079 -0.175  -0.04 -0.084  -0.03 -0.047 -0.058

      20     21     22     23     24     25     26     27     28     29  \
0 -0.038 -0.036 -0.088 -0.102 -0.021 -0.031 -0.053 -0.257 -0.114 -0.075
1 -0.019 -0.017 -0.023 -0.044 -0.004 -0.019 -0.033 -0.187 -0.074 -0.057
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.044  -0.04 -0.091 -0.132 -0.035 -0.036 -0.062 -0.258 -0.133 -0.097
4 -0.067 -0.063 -0.148 -0.228 -1.008 -0.058 -0.094 -0.315 -0.204 -0.156

      30     31     32     33     34     35     36     37     38        39  \
0 -0.037   0.08  0.027 -0.161  0.056 -0.004  0.002  0.003 -0.033 -0.056133
1 -0.044  0.044  0.006 -0.146  0.009 -0.017 -0.009 -0.008 -0.029 -0.010433
2      ?      ?      ?      ?      ?      ?      ?      ?      ?         ?
3  -0.07  0.069  0.014 -0.177  0.053 -0.006 -0.002 -0.005 -0.031 -0.070167
4 -0.122  0.081  0.007 -0.204  0.084  0.003      0 -0.008 -0.028   -0.1135

         40     41     42     43     44     45     46     47     48     49  \
0 -0.019444  0.016  0.004  0.038  0.028 -0.016 -0.027 -0.044 -0.055 -0.024
1  0.012889  0.023  0.022  0.026   0.06 -0.025  0.053 -0.053 -0.087 -0.029
2         ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.035333  0.006  -0.01  0.029 -0.013 -0.032  -0.03 -0.049 -0.084 -0.028
4 -0.114333 -0.002 -0.032  0.034 -0.073 -0.108 -0.066 -0.073 -0.166 -0.046

      50     51     52     53     54     55     56     57     58     59  \
0  0.016  -0.02 -0.019 -0.024  0.007 -0.046 -0.052  0.042 -0.059 -0.073
1 -0.075 -0.122 -0.363  -0.01  0.101  0.006 -0.104 -0.029  -0.24 -0.099
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.012 -0.051 -0.377  -0.05  0.008 -0.071 -0.073  0.019  -0.04 -0.076
4 -0.038 -0.125 -0.423 -0.118  -0.03 -0.184 -0.133 -0.037 -0.089 -0.187

      60     61     62     63     64     65     66     67     68     69  \
0  -0.02  0.016 -0.018 -0.023 -0.039 -0.268 -0.036  0.015 -0.003 -0.019
1  0.027   0.12  0.086  0.199 -0.185  -0.64 -0.066  0.059  0.017  0.053
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  -0.04 -0.014 -0.034 -0.017 -0.043  -0.27 -0.033      0 -0.011 -0.024
4 -0.149 -0.121  -0.12 -0.124 -0.098 -0.478 -0.068 -0.062 -0.053 -0.078

      70     71     72     73     74     75     76     77     78     79  \
0 -0.019 -0.053 -0.037 -0.002 -0.034 -0.031 -0.034 -0.025  0.018  0.008
1  0.084 -0.149 -0.047  0.049 -0.048 -0.012 -0.007 -0.003  0.071  0.048
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.026  -0.05 -0.035      0 -0.023 -0.023 -0.028 -0.026  0.015  0.015
4 -0.082 -0.121 -0.107 -0.046 -0.034  -0.04 -0.047 -0.057 -0.064  0.054

      80     81     82     83     84     85     86     87     88     89  \
0 -0.017 -0.042 -0.035 -0.065 -0.076  0.006 -0.024 -0.023 -0.048 -0.049
1 -0.045 -0.081 -0.029  0.093 -0.068 -0.048  0.006 -0.008 -0.012  0.006
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.007 -0.028 -0.023 -0.069 -0.071   0.01 -0.056 -0.051  -0.05 -0.065
4  -0.03 -0.052 -0.052 -0.184 -0.089 -0.111 -0.116 -0.087 -0.096 -0.139

      90     91     92     93     94     95     96     97     98     99  \
0 -0.049 -0.069 -0.026  0.049  0.049  0.025 -0.025  3.593  3.082  4.411
1 -0.007 -0.021  -0.01  0.036  0.024  0.014 -0.005    3.6  3.094  4.406
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.047 -0.062 -0.025   0.06  0.053   0.02 -0.031  3.591  3.075  4.405
4 -0.097 -0.103 -0.039  0.036  0.076  0.019 -0.055  3.589  3.056  4.398

     100    101    102    103    104    105       106       107       108  \
0  3.695  2.765  0.038  0.463  0.604  0.904 -0.144053     0.027  0.085904
1  3.696  2.776  0.027  0.412  0.609   0.91 -0.172632  0.024812  0.082942
2      ?      ?      ?      ?      ?      ?         ?         ?         ?
3   3.69  2.762  0.043   0.45  0.595  0.896 -0.158158   0.05025  0.146481
4  3.684  2.747 -0.963  0.444  0.574  0.872 -0.038211  0.045687    0.1125

     109    110    111    112    113    114    115    116    117    118  \
0 -0.044 -0.003  0.034 -0.021 -0.024  0.033 -0.014  0.023 -0.035 -0.058
1 -0.042  0.006  0.041 -0.026 -0.011  0.005 -0.003 -0.013 -0.017 -0.047
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.062  0.004  0.005 -0.032 -0.019  0.035 -0.013   0.01 -0.031 -0.049
4 -0.082 -0.005 -0.018 -0.075 -0.028  0.046 -0.021  0.005 -0.052 -0.061

     119    120    121    122    123    124    125    126    127    128  \
0 -0.063 -0.027  0.009 -0.076 -0.059 -0.035  0.009  0.082 -0.101   -0.1
1 -0.008 -0.007  0.015 -0.054 -0.044 -0.025  0.023  0.141 -0.051 -0.082
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.041 -0.025  0.005 -0.075 -0.058 -0.037  0.009  0.088 -0.096 -0.097
4 -0.061  -0.04 -0.007 -0.095  -0.07 -0.049  0.002  0.064 -0.121 -0.098

     129    130    131       132       133     134       135       136    137  \
0  0.053  0.197 -0.021  0.032727 -0.006955   0.102 -0.572514  0.009724  0.021
1  0.008  0.089 -0.038  0.035212 -0.005523  0.0475 -0.559914   0.00869  0.002
2      ?      ?      ?         ?         ?       ?         ?         ?      ?
3  0.043  0.185 -0.033  0.041485 -0.013295   0.096 -0.579429  0.007966   0.02
4  0.065  0.197 -0.039  0.057303 -0.025864    0.13   -0.5916  0.002759  0.014

     138    139    140    141    142    143    144    145    146    147  \
0 -0.274 -0.011  0.013 -0.025 -0.037 -0.005  0.016  0.023  0.026 -0.045
1 -0.291  0.011  0.001 -0.042  0.002  0.014  0.014  0.023  0.069 -0.022
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.051 -0.012  0.019  0.036 -0.048 -0.013   0.01  0.034  0.044  -0.04
4  0.027 -0.027  0.039  0.035 -0.086 -0.032  0.012  0.046  0.046 -0.075

     148    149    150    151    152    153    154    155    156    157  \
0  0.001  0.019  0.007  0.013 -0.034 -0.033  0.006  0.009  0.026  0.006
1  0.013  0.022 -0.011  0.011 -0.035  0.002  0.003 -0.004  0.001      0
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.003  0.006  0.001      0 -0.078 -0.005  0.011  0.007  0.006  0.008
4      0   0.01  0.027  0.009 -0.089  0.015  0.033  0.025  0.021  0.022

     158    159       160    161    162    163    164    165    166    167  \
0  0.045  0.052  0.073167 -0.044 -0.018 -0.066 -0.064  -0.05 -0.028 -0.036
1  0.011  0.006  0.027333 -0.041 -0.017 -0.055 -0.048 -0.042 -0.021 -0.034
2      ?      ?         ?      ?      ?      ?      ?      ?      ?      ?
3  0.004  0.021    0.0575 -0.044 -0.027 -0.064 -0.054 -0.047 -0.032 -0.034
4  0.014  0.037  0.034167 -2.503 -0.013 -0.076 -0.061 -0.056 -0.043 -0.044

        168       169       170       171    172    173    174    175    176  \
0  0.001857 -0.018933 -0.035123  0.017667 -0.084  0.171  0.004  0.004 -0.002
1 -0.005714 -0.017533 -0.014308  0.006667  0.027 -0.022  0.014  0.019  0.008
2         ?         ?         ?         ?      ?      ?      ?      ?      ?
3   -0.0128 -0.028133 -0.044062 -0.006833 -0.066 -0.043  0.009  0.001 -0.001
4 -0.025457  0.603633 -0.055246 -0.081333 -0.035  0.041  0.039 -0.014 -0.001

     177    178    179    180    181    182    183    184    185    186  \
0  0.108  0.169 -0.156  0.013  0.007  0.013  0.029  0.063 -0.183  0.023
1  0.013  0.076  -0.15  0.021  0.011  0.021  0.026  0.058 -0.188  0.013
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.009  0.058   -0.2  0.007  0.004  0.012  0.024  0.036 -0.202  0.031
4  0.002  0.053 -0.302 -0.008      0  0.005  0.022  0.003 -0.224   0.05

     187    188    189    190    191    192    193    194    195    196  \
0      0  0.018  0.037  0.051 -0.152 -0.127 -0.029 -0.009 -0.015  0.001
1 -0.003  0.025  0.042  0.036 -0.167 -0.122 -0.071  0.017 -0.005   0.02
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3      0  0.017   0.02   0.03 -0.161 -0.144  0.002 -0.009 -0.016  0.004
4  0.008  0.008 -0.025   0.01 -0.167 -0.182  0.109 -0.032 -0.008 -0.008

     197    198    199    200    201    202    203    204    205    206  \
0  0.018  0.027  0.021  0.025  0.105  0.028  -0.15  0.021  0.005 -0.016
1  0.026  0.028  0.019  0.027  0.011  0.014 -0.151  0.022   0.02 -0.007
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.018  0.028  0.019  0.022  0.094  0.011 -0.174  0.001  0.004 -0.027
4  0.018  0.035  0.021  0.017  0.088 -0.006 -0.209 -0.028 -0.004 -0.048

     207    208    209    210    211    212    213    214    215    216  \
0 -0.006  0.006 -0.003  0.017  0.029  0.185  0.022   0.04  0.001 -0.009
1  0.006  0.021  0.004  0.019  0.018  0.018  0.013  0.054  0.007  0.007
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.014  0.002 -0.011  0.011  0.022  0.159      0  0.025 -0.025 -0.023
4 -0.032  -0.01 -0.036 -0.002  0.016   0.13 -0.036 -0.007 -0.064 -0.057

     217    218    219    220    221    222    223    224    225    226  \
0  0.025  0.026 -0.001 -0.029 -0.037  0.015  0.299  0.037 -0.004 -0.009
1  0.023  0.014 -0.007 -0.023  -0.01   0.01  0.296  0.031 -0.003  0.056
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.017  0.015 -0.036 -0.057 -0.054  0.008  0.275  0.025 -0.009  -0.02
4      0  0.006 -0.099 -0.113 -0.093  0.016  0.199 -0.006 -0.011 -0.065

     227    228    229    230    231    232    233    234    235    236  \
0 -0.028 -0.042  -0.07 -0.061 -0.063 -0.019  0.031 -0.074  -0.11 -0.092
1 -0.035  0.009      0  0.005 -0.014 -0.016  0.024  0.033  0.016  0.006
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  -0.04 -0.039 -0.065 -0.065 -0.065 -0.076 -0.007 -0.072 -0.111 -0.096
4 -0.082 -0.052 -0.092 -0.103 -0.104  -0.12 -0.028 -0.104 -0.151 -0.147

     237    238    239    240    241    242    243    244    245    246  \
0 -0.088  0.017 -0.037 -0.039  -0.08 -0.078  0.013 -0.023  0.009  0.021
1  0.006 -0.022 -0.044 -0.013  0.012 -0.004  0.004 -0.011  0.008  0.004
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.087 -0.032  0.022  0.104 -0.085 -0.088 -0.013 -0.045  0.019  0.009
4 -0.131 -0.028 -0.012   0.06 -0.131 -0.143 -0.044 -0.088  0.046  0.033

     247    248    249    250    251    252    253    254    255    256  \
0  0.002 -0.043 -0.034 -0.051  0.086  0.008 -0.021 -0.015 -0.027 -0.064
1 -0.001 -0.017 -0.008  0.004   0.06 -0.011  -0.01 -0.001  0.009 -0.011
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.014 -0.049 -0.042 -0.048  0.143 -0.016  -0.03 -0.023 -0.027 -0.059
4 -0.028 -0.079  -0.08 -0.093   0.35 -0.026 -0.048 -0.048 -0.061 -0.109

     257    258    259    260    261    262    263    264    265    266  \
0 -0.085   0.07  0.005 -0.025 -0.015 -0.023 -0.044 -0.061 -0.092 -0.062
1  -0.02  0.006 -0.002 -0.025 -0.011 -0.009  -0.02      0 -0.032 -0.036
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.073  0.075 -0.001 -0.044 -0.022 -0.028 -0.045 -0.049 -0.083 -0.058
4 -0.125    0.1 -0.006 -0.074 -0.038  -0.05 -0.086 -0.089 -0.131 -0.079

     267    268    269    270    271    272    273    274    275    276  \
0  0.039 -0.024 -0.017 -0.053 -0.089  0.054  0.003 -0.011 -0.018  0.159
1  0.003 -0.005 -0.003 -0.031 -0.043  0.026  0.005 -0.011 -0.028 -0.028
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.036 -0.049  -0.02 -0.058 -0.099  0.122  0.006 -0.013 -0.028  0.146
4  0.053 -0.024 -0.044 -0.088 -0.152  0.162  0.011  -0.02  -0.04    0.1

     277    278    279    280    281    282    283    284    285    286  \
0 -0.055 -0.052 -0.013 -0.062 -0.397  0.023   0.01 -0.068   -0.1 -0.061
1 -0.023 -0.031 -0.047 -0.006  0.009 -0.029   0.03 -0.027 -0.046 -0.039
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.064 -0.059 -0.022 -0.087 -0.107  0.014 -0.003 -0.068 -0.096  -0.06
4 -0.084  -0.09 -0.051 -0.158 -0.181  0.018 -0.046 -0.101 -0.125 -0.073

     287    288    289    290    291    292    293    294    295    296  \
0 -0.479 -4.485 -0.058 -0.055 -0.171 -0.694 -4.222 -4.109 -0.072 -0.065
1 -0.469 -4.489 -0.022 -0.016 -0.147 -0.689 -4.238 -4.111 -0.084 -0.034
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.481 -4.485 -0.062 -0.054 -0.173 -0.696 -4.224 -4.107 -0.086 -0.083
4 -0.493 -4.484 -0.094 -0.082 -0.192 -0.701 -4.219 -4.106 -0.101 -0.131

     297    298    299    300    301    302    303    304    305       306  \
0  0.003 -0.004  0.011 -0.033 -3.665 -2.676  0.025  0.075 -2.556  0.023846
1  0.006 -0.002 -0.001 -0.057 -3.725 -2.851  0.014  0.023 -2.645  0.027423
2      ?      ?      ?      ?      ?      ?      ?      ?      ?         ?
3 -0.012 -0.017  0.001 -0.031 -3.643 -2.769  0.016  0.054  -2.58  0.011077
4 -0.038 -0.043 -0.011 -0.145 -3.998 -2.806  0.011  0.052 -2.557 -0.007346

        307     308      309    310    311    312    313    314    315    316  \
0    -0.103    0.01   0.0178  0.062 -0.051  -0.03 -0.011  0.012  0.005 -0.026
1 -0.054667  0.0135   0.0233  0.054 -0.071  -0.04 -0.011 -0.008 -0.014 -0.029
2         ?       ?        ?      ?      ?      ?      ?      ?      ?      ?
3 -0.099333  0.0095 -0.00882   0.06  -0.08  -0.05 -0.021 -0.006 -0.012  -0.03
4 -0.134333   0.004 -0.02124  0.067 -0.104 -0.096 -0.039 -0.017 -0.026 -0.041

     317    318    319    320    321    322    323    324    325    326  \
0 -0.014 -0.011  0.002  0.011  2.551 -0.047 -0.046 -0.008  0.005  0.006
1 -0.038 -0.024 -0.004  0.003 -0.002 -0.032 -0.046 -0.021  0.003  0.001
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.036 -0.027 -0.006  0.001 -0.002 -0.043 -0.061  -0.02  0.002 -0.001
4 -0.065 -0.049 -0.017 -0.011 -0.017 -0.051 -0.095 -0.038 -0.002  -0.01

     327    328    329    330    331    332    333    334    335    336  \
0  0.015  0.002 -0.076 -0.037 -0.016 -0.001 -0.003 -0.001 -0.001 -0.118
1  0.004  0.007 -0.042 -0.043 -0.021  0.001      0      0  0.003 -0.039
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3      0 -0.006 -0.074 -0.052 -0.028 -0.002 -0.008  -0.01 -0.012  -0.06
4 -0.019 -0.016 -0.099 -0.082  -0.05 -0.007 -0.017  -0.03 -0.035 -0.086

     337    338    339    340    341    342    343    344    345    346  \
0 -0.008 -0.003 -0.002  3.024  -0.03 -0.019 -0.015 -0.024 -0.442 -0.001
1  0.003  0.006  0.005  2.952  0.001  0.008  0.006 -0.004 -0.366  0.009
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.012      0 -0.004  3.031 -0.032 -0.016 -0.004 -0.027 -0.089 -0.019
4 -0.026      0 -0.012 -0.033 -0.036  -0.03  0.012 -0.056 -0.056 -0.046

     347    348    349    350    351    352    353    354    355    356  \
0 -0.198  0.235  0.199  0.074  -0.22  0.069 -0.016  0.102  0.028  0.028
1 -0.123  0.291  0.113  0.056 -0.385  0.051 -0.025  0.036  0.012  0.035
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.233  0.268   0.19  0.051 -0.232  0.063  -0.02  0.098  0.033   0.04
4 -0.319  0.387  0.207  0.025 -0.105 -0.109 -0.066 -0.005 -0.011  -0.01

     357    358    359    360    361    362    363    364    365    366  \
0  0.026  0.621   0.06   0.02 -0.008 -0.076 -0.035  0.021 -0.019  0.004
1  0.034  0.086      0 -0.005 -0.007  0.041  0.033  0.012  0.065  0.015
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.037  0.607  0.061  0.024 -0.005  -0.04 -0.032  0.008 -0.029 -0.004
4  0.001  0.534  0.042   0.03 -0.012  -0.03 -0.054 -0.011 -0.086  -0.04

     367    368    369    370    371    372    373    374    375    376  \
0 -0.007      0  0.005  1.038 -0.014 -0.011 -0.023 -0.041 -0.031  0.064
1 -0.016 -0.011 -0.004  0.992 -0.014 -0.022 -0.014 -0.009      0  0.017
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.011 -0.008  0.001  1.051 -0.023 -0.014 -0.023 -0.046 -0.031  0.051
4 -0.014 -0.013  0.021   1.18  -0.06 -0.017  -0.03 -0.088 -0.051  0.021

     377    378    379    380    381    382    383    384    385    386  \
0 -0.046 -0.049 -0.043 -0.033 -0.028 -0.036 -0.027 -0.049 -0.074 -0.049
1 -0.004 -0.019 -0.018 -0.012 -0.009  0.001 -0.012 -0.036 -0.024 -0.014
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.035 -0.047 -0.043  -0.03 -0.035 -0.047 -0.024 -0.048 -0.065 -0.048
4 -0.047 -0.074 -0.051 -0.039 -0.056 -0.097  0.007 -0.048 -0.109 -0.087

     387    388    389    390    391    392    393    394    395    396  \
0 -0.047 -0.025 -0.008 -0.014  -0.03 -0.052 -0.028  0.049 -0.102 -0.029
1 -0.015 -0.009      0 -0.033 -0.006 -0.016 -0.008  0.016 -0.029  0.009
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.047 -0.033 -0.019 -0.018  -0.03 -0.054 -0.034  0.029 -0.099 -0.027
4 -0.064  -0.05  -0.04  0.008 -0.087 -0.085 -0.057   0.04  -0.11 -0.057

     397    398    399    400    401    402    403    404    405    406  \
0  0.063 -0.041 -0.023 -0.006 -0.003 -0.014  0.024  0.012 -0.012 -0.018
1  0.041 -0.027 -0.002  0.011  0.014   0.01 -0.005  0.006 -0.002 -0.008
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.028 -0.055 -0.024  -0.01 -0.004 -0.014  0.038  0.017  0.004 -0.015
4 -0.008 -0.125 -0.161 -0.164  0.076  -0.11   0.06 -0.018  0.087 -0.055

     407    408    409    410    411    412    413    414    415    416  \
0  0.044  0.065  0.022 -0.002  0.059  0.042 -0.017  0.027  0.189  0.147
1   0.05  0.067  0.021 -0.003  0.056  0.043 -0.017  0.005  0.183   0.04
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.058  0.085  0.033  0.005  0.065  0.046 -0.024  0.012  0.195   0.15
4  0.038  0.092  0.075  0.003  0.064  0.054 -0.187 -0.304  0.219  0.157

     417    418    419    420    421    422    423    424    425    426  \
0  0.021  0.008 -0.004  0.621  0.046 -0.001 -0.027 -0.012 -0.015  0.042
1  0.014  0.001  -0.01  0.609  0.004 -0.018 -0.026 -0.012 -0.008  0.015
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.022  0.008 -0.019  0.626  0.046 -0.004  -0.03 -0.016 -0.014  0.024
4  0.019  0.011 -0.185  -0.34  0.049 -0.022 -0.056 -0.052 -0.034 -0.054

     427    428    429    430    431    432    433    434    435    436  \
0  0.063 -0.039 -0.151  -0.13 -0.127 -0.017  -0.05 -0.007 -0.079 -0.423
1  0.054 -0.031 -0.148 -0.128 -0.125 -0.004 -0.043 -0.021 -0.071 -0.414
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.045 -0.037 -0.148 -0.135 -0.132 -0.018 -0.047 -0.012 -0.077 -0.422
4 -0.301 -0.024  0.005 -0.045 -0.061 -0.069 -0.019 -0.013 -0.026 -0.031

     437    438    439    440    441    442    443    444    445    446  \
0 -0.238 -0.008  -0.05  0.012 -0.084 -0.023 -0.007 -0.196  0.008 -0.017
1 -0.227  0.003  -0.04  0.024 -0.066 -0.009  0.015 -0.182  0.018 -0.009
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.244 -0.014 -0.051  0.011 -0.084 -0.026 -0.007 -0.194  0.007 -0.021
4 -0.054 -0.069 -0.113 -0.042 -0.061 -0.052 -0.047 -0.197  -0.04 -0.052

     447       448    449    450    451    452    453    454    455    456  \
0 -0.018  0.013176  1.221  0.048  0.134 -0.015  0.028 -0.006 -0.051  0.034

In [ ]:
# Drop rows where column 4826 has a "?"
filtered_df = df[df[4826] != "?"]

# impute here!!

In [ ]:
#impute here!!

In [ ]:
# Now extract X and y properly
x_df = filtered_df.drop(columns=["result"])  # Drop the target column for features
y = filtered_df["result"]  # Keep the target variable

In [95]:
filtered_df.head()

       0      1      2      3      4      5      6      7      8      9  \
0 -0.161 -0.014  0.002 -0.036 -0.033 -0.093  0.025  0.005      0 -0.015
1 -0.158 -0.002 -0.012 -0.025 -0.012 -0.106  0.013  0.005      0 -0.002
3 -0.169 -0.025  -0.01 -0.041 -0.045 -0.069  0.038  0.014  0.008 -0.014
4 -0.183 -0.051 -0.023 -0.077 -0.092 -0.015  0.071  0.027   0.02 -0.019
5 -0.154  0.005 -0.011 -0.013 -0.002 -0.115  0.005  0.002 -0.003  0.002

      10     11     12     13     14     15     16     17     18     19  \
0  -0.03  -0.05 -0.031 -0.036 -0.093 -0.008  -0.03 -0.023 -0.036 -0.042
1 -0.007  -0.01 -0.009 -0.017 -0.024  0.002  0.003 -0.011 -0.013  -0.01
3 -0.032 -0.043 -0.033 -0.046 -0.094 -0.017 -0.042 -0.022 -0.033 -0.039
4 -0.044 -0.097 -0.052 -0.079 -0.175  -0.04 -0.084  -0.03 -0.047 -0.058
5  0.006 -0.002 -0.004 -0.009 -0.011  0.006  0.015 -0.008 -0.009 -0.004

      20     21     22     23     24     25     26     27     28     29  \
0 -0.038 -0.036 -0.088 -0.102 -0.021 -0.031 -0.053 -0.257 -0.114 -0.075
1 -0.019 -0.017 -0.023 -0.044 -0.004 -0.019 -0.033 -0.187 -0.074 -0.057
3 -0.044  -0.04 -0.091 -0.132 -0.035 -0.036 -0.062 -0.258 -0.133 -0.097
4 -0.067 -0.063 -0.148 -0.228 -1.008 -0.058 -0.094 -0.315 -0.204 -0.156
5  -0.01 -0.011 -0.007 -0.016  0.005 -0.011 -0.022 -0.161 -0.058 -0.043

      30     31     32     33     34     35     36     37     38        39  \
0 -0.037   0.08  0.027 -0.161  0.056 -0.004  0.002  0.003 -0.033 -0.056133
1 -0.044  0.044  0.006 -0.146  0.009 -0.017 -0.009 -0.008 -0.029 -0.010433
3  -0.07  0.069  0.014 -0.177  0.053 -0.006 -0.002 -0.005 -0.031 -0.070167
4 -0.122  0.081  0.007 -0.204  0.084  0.003      0 -0.008 -0.028   -0.1135
5  -0.03  0.041  0.008 -0.133      0  -0.02 -0.012  -0.01 -0.029  0.000033

         40     41     42     43     44     45     46     47     48     49  \
0 -0.019444  0.016  0.004  0.038  0.028 -0.016 -0.027 -0.044 -0.055 -0.024
1  0.012889  0.023  0.022  0.026   0.06 -0.025  0.053 -0.053 -0.087 -0.029
3 -0.035333  0.006  -0.01  0.029 -0.013 -0.032  -0.03 -0.049 -0.084 -0.028
4 -0.114333 -0.002 -0.032  0.034 -0.073 -0.108 -0.066 -0.073 -0.166 -0.046
5  0.008278  0.018   0.01  0.043   0.05 -0.003 -0.011 -0.025 -0.014 -0.009

      50     51     52     53     54     55     56     57     58     59  \
0  0.016  -0.02 -0.019 -0.024  0.007 -0.046 -0.052  0.042 -0.059 -0.073
1 -0.075 -0.122 -0.363  -0.01  0.101  0.006 -0.104 -0.029  -0.24 -0.099
3 -0.012 -0.051 -0.377  -0.05  0.008 -0.071 -0.073  0.019  -0.04 -0.076
4 -0.038 -0.125 -0.423 -0.118  -0.03 -0.184 -0.133 -0.037 -0.089 -0.187
5  0.008 -0.006 -0.025 -0.019 -0.006 -0.027  -0.03  0.025  -0.11 -0.114

      60     61     62     63     64     65     66     67     68     69  \
0  -0.02  0.016 -0.018 -0.023 -0.039 -0.268 -0.036  0.015 -0.003 -0.019
1  0.027   0.12  0.086  0.199 -0.185  -0.64 -0.066  0.059  0.017  0.053
3  -0.04 -0.014 -0.034 -0.017 -0.043  -0.27 -0.033      0 -0.011 -0.024
4 -0.149 -0.121  -0.12 -0.124 -0.098 -0.478 -0.068 -0.062 -0.053 -0.078
5 -0.022  0.002 -0.021  0.017 -0.051 -0.444 -0.062  0.015 -0.027 -0.032

      70     71     72     73     74     75     76     77     78     79  \
0 -0.019 -0.053 -0.037 -0.002 -0.034 -0.031 -0.034 -0.025  0.018  0.008
1  0.084 -0.149 -0.047  0.049 -0.048 -0.012 -0.007 -0.003  0.071  0.048
3 -0.026  -0.05 -0.035      0 -0.023 -0.023 -0.028 -0.026  0.015  0.015
4 -0.082 -0.121 -0.107 -0.046 -0.034  -0.04 -0.047 -0.057 -0.064  0.054
5  -0.03 -0.078 -0.059 -0.007 -0.064 -0.049  -0.04 -0.026  0.005 -0.009

      80     81     82     83     84     85     86     87     88     89  \
0 -0.017 -0.042 -0.035 -0.065 -0.076  0.006 -0.024 -0.023 -0.048 -0.049
1 -0.045 -0.081 -0.029  0.093 -0.068 -0.048  0.006 -0.008 -0.012  0.006
3 -0.007 -0.028 -0.023 -0.069 -0.071   0.01 -0.056 -0.051  -0.05 -0.065
4  -0.03 -0.052 -0.052 -0.184 -0.089 -0.111 -0.116 -0.087 -0.096 -0.139
5 -0.031 -0.088 -0.056  -0.07 -0.081  -0.09  0.012 -0.011  0.003  0.028

      90     91     92     93     94     95     96     97     98     99  \
0 -0.049 -0.069 -0.026  0.049  0.049  0.025 -0.025  3.593  3.082  4.411
1 -0.007 -0.021  -0.01  0.036  0.024  0.014 -0.005    3.6  3.094  4.406
3 -0.047 -0.062 -0.025   0.06  0.053   0.02 -0.031  3.591  3.075  4.405
4 -0.097 -0.103 -0.039  0.036  0.076  0.019 -0.055  3.589  3.056  4.398
5  0.016 -0.008  0.004  0.071  0.046  0.036  0.018  0.043   2.91  0.005

     100    101    102    103    104    105       106       107       108  \
0  3.695  2.765  0.038  0.463  0.604  0.904 -0.144053     0.027  0.085904
1  3.696  2.776  0.027  0.412  0.609   0.91 -0.172632  0.024812  0.082942
3   3.69  2.762  0.043   0.45  0.595  0.896 -0.158158   0.05025  0.146481
4  3.684  2.747 -0.963  0.444  0.574  0.872 -0.038211  0.045687    0.1125
5  3.103  2.495 -2.852 -2.116 -1.979  0.407 -0.178263   0.02425  0.022962

     109    110    111    112    113    114    115    116    117    118  \
0 -0.044 -0.003  0.034 -0.021 -0.024  0.033 -0.014  0.023 -0.035 -0.058
1 -0.042  0.006  0.041 -0.026 -0.011  0.005 -0.003 -0.013 -0.017 -0.047
3 -0.062  0.004  0.005 -0.032 -0.019  0.035 -0.013   0.01 -0.031 -0.049
4 -0.082 -0.005 -0.018 -0.075 -0.028  0.046 -0.021  0.005 -0.052 -0.061
5 -0.037   0.01  0.037 -0.029 -0.007   0.01  0.002 -0.014 -0.015  -0.04

     119    120    121    122    123    124    125    126    127    128  \
0 -0.063 -0.027  0.009 -0.076 -0.059 -0.035  0.009  0.082 -0.101   -0.1
1 -0.008 -0.007  0.015 -0.054 -0.044 -0.025  0.023  0.141 -0.051 -0.082
3 -0.041 -0.025  0.005 -0.075 -0.058 -0.037  0.009  0.088 -0.096 -0.097
4 -0.061  -0.04 -0.007 -0.095  -0.07 -0.049  0.002  0.064 -0.121 -0.098
5  0.001 -0.002  0.018 -0.044 -0.038  -0.02  0.025  0.063 -0.041 -0.078

     129    130    131       132       133     134       135       136    137  \
0  0.053  0.197 -0.021  0.032727 -0.006955   0.102 -0.572514  0.009724  0.021
1  0.008  0.089 -0.038  0.035212 -0.005523  0.0475 -0.559914   0.00869  0.002
3  0.043  0.185 -0.033  0.041485 -0.013295   0.096 -0.579429  0.007966   0.02
4  0.065  0.197 -0.039  0.057303 -0.025864    0.13   -0.5916  0.002759  0.014
5  0.001  0.071 -0.037  0.031818   -0.0025   0.039 -0.557514  0.010241  0.024

     138    139    140    141    142    143    144    145    146    147  \
0 -0.274 -0.011  0.013 -0.025 -0.037 -0.005  0.016  0.023  0.026 -0.045
1 -0.291  0.011  0.001 -0.042  0.002  0.014  0.014  0.023  0.069 -0.022
3  0.051 -0.012  0.019  0.036 -0.048 -0.013   0.01  0.034  0.044  -0.04
4  0.027 -0.027  0.039  0.035 -0.086 -0.032  0.012  0.046  0.046 -0.075
5   0.07      0  0.002  0.036 -0.005 -0.013  0.002   0.02  0.052 -0.005

     148    149    150    151    152    153    154    155    156    157  \
0  0.001  0.019  0.007  0.013 -0.034 -0.033  0.006  0.009  0.026  0.006
1  0.013  0.022 -0.011  0.011 -0.035  0.002  0.003 -0.004  0.001      0
3 -0.003  0.006  0.001      0 -0.078 -0.005  0.011  0.007  0.006  0.008
4      0   0.01  0.027  0.009 -0.089  0.015  0.033  0.025  0.021  0.022
5 -0.007 -0.007 -0.034 -0.016 -0.062  0.009 -0.014  -0.02 -0.024  0.001

     158    159       160    161    162    163    164    165    166    167  \
0  0.045  0.052  0.073167 -0.044 -0.018 -0.066 -0.064  -0.05 -0.028 -0.036
1  0.011  0.006  0.027333 -0.041 -0.017 -0.055 -0.048 -0.042 -0.021 -0.034
3  0.004  0.021    0.0575 -0.044 -0.027 -0.064 -0.054 -0.047 -0.032 -0.034
4  0.014  0.037  0.034167 -2.503 -0.013 -0.076 -0.061 -0.056 -0.043 -0.044
5 -0.015 -0.009    0.0375 -0.044 -0.012 -0.057 -0.054 -0.038 -0.015 -0.023

        168       169       170       171    172    173    174    175    176  \
0  0.001857 -0.018933 -0.035123  0.017667 -0.084  0.171  0.004  0.004 -0.002
1 -0.005714 -0.017533 -0.014308  0.006667  0.027 -0.022  0.014  0.019  0.008
3   -0.0128 -0.028133 -0.044062 -0.006833 -0.066 -0.043  0.009  0.001 -0.001
4 -0.025457  0.603633 -0.055246 -0.081333 -0.035  0.041  0.039 -0.014 -0.001
5 -0.000771 -0.015167 -0.007277   -0.0085 -0.021  0.235  0.013  0.026   0.01

     177    178    179    180    181    182    183    184    185    186  \
0  0.108  0.169 -0.156  0.013  0.007  0.013  0.029  0.063 -0.183  0.023
1  0.013  0.076  -0.15  0.021  0.011  0.021  0.026  0.058 -0.188  0.013
3  0.009  0.058   -0.2  0.007  0.004  0.012  0.024  0.036 -0.202  0.031
4  0.002  0.053 -0.302 -0.008      0  0.005  0.022  0.003 -0.224   0.05
5  0.117  0.164 -0.138  0.027  0.014  0.023  0.028  0.068 -0.183   0.01

     187    188    189    190    191    192    193    194    195    196  \
0      0  0.018  0.037  0.051 -0.152 -0.127 -0.029 -0.009 -0.015  0.001
1 -0.003  0.025  0.042  0.036 -0.167 -0.122 -0.071  0.017 -0.005   0.02
3      0  0.017   0.02   0.03 -0.161 -0.144  0.002 -0.009 -0.016  0.004
4  0.008  0.008 -0.025   0.01 -0.167 -0.182  0.109 -0.032 -0.008 -0.008
5 -0.004  0.027  0.044  0.041 -0.166 -0.107 -0.095  0.024 -0.001  0.021

     197    198    199    200    201    202    203    204    205    206  \
0  0.018  0.027  0.021  0.025  0.105  0.028  -0.15  0.021  0.005 -0.016
1  0.026  0.028  0.019  0.027  0.011  0.014 -0.151  0.022   0.02 -0.007
3  0.018  0.028  0.019  0.022  0.094  0.011 -0.174  0.001  0.004 -0.027
4  0.018  0.035  0.021  0.017  0.088 -0.006 -0.209 -0.028 -0.004 -0.048
5  0.022  0.023  0.018  0.029  0.011  0.019 -0.138  0.033  0.024      0

     207    208    209    210    211    212    213    214    215    216  \
0 -0.006  0.006 -0.003  0.017  0.029  0.185  0.022   0.04  0.001 -0.009
1  0.006  0.021  0.004  0.019  0.018  0.018  0.013  0.054  0.007  0.007
3 -0.014  0.002 -0.011  0.011  0.022  0.159      0  0.025 -0.025 -0.023
4 -0.032  -0.01 -0.036 -0.002  0.016   0.13 -0.036 -0.007 -0.064 -0.057
5  0.011   0.02  0.014  0.021   0.02  0.019  0.021  0.067  0.022  0.017

     217    218    219    220    221    222    223    224    225    226  \
0  0.025  0.026 -0.001 -0.029 -0.037  0.015  0.299  0.037 -0.004 -0.009
1  0.023  0.014 -0.007 -0.023  -0.01   0.01  0.296  0.031 -0.003  0.056
3  0.017  0.015 -0.036 -0.057 -0.054  0.008  0.275  0.025 -0.009  -0.02
4      0  0.006 -0.099 -0.113 -0.093  0.016  0.199 -0.006 -0.011 -0.065
5  0.027  0.015  0.005 -0.004  0.006  0.011   0.31  0.041  0.001  0.027

     227    228    229    230    231    232    233    234    235    236  \
0 -0.028 -0.042  -0.07 -0.061 -0.063 -0.019  0.031 -0.074  -0.11 -0.092
1 -0.035  0.009      0  0.005 -0.014 -0.016  0.024  0.033  0.016  0.006
3  -0.04 -0.039 -0.065 -0.065 -0.065 -0.076 -0.007 -0.072 -0.111 -0.096
4 -0.082 -0.052 -0.092 -0.103 -0.104  -0.12 -0.028 -0.104 -0.151 -0.147
5 -0.002 -0.033 -0.048  -0.02 -0.026 -0.029   0.01 -0.027 -0.048 -0.019

     237    238    239    240    241    242    243    244    245    246  \
0 -0.088  0.017 -0.037 -0.039  -0.08 -0.078  0.013 -0.023  0.009  0.021
1  0.006 -0.022 -0.044 -0.013  0.012 -0.004  0.004 -0.011  0.008  0.004
3 -0.087 -0.032  0.022  0.104 -0.085 -0.088 -0.013 -0.045  0.019  0.009
4 -0.131 -0.028 -0.012   0.06 -0.131 -0.143 -0.044 -0.088  0.046  0.033
5 -0.015 -0.045 -0.057 -0.002 -0.004  0.025  0.011 -0.003 -0.006 -0.012

     247    248    249    250    251    252    253    254    255    256  \
0  0.002 -0.043 -0.034 -0.051  0.086  0.008 -0.021 -0.015 -0.027 -0.064
1 -0.001 -0.017 -0.008  0.004   0.06 -0.011  -0.01 -0.001  0.009 -0.011
3 -0.014 -0.049 -0.042 -0.048  0.143 -0.016  -0.03 -0.023 -0.027 -0.059
4 -0.028 -0.079  -0.08 -0.093   0.35 -0.026 -0.048 -0.048 -0.061 -0.109
5 -0.003 -0.002  0.005  0.016  0.002 -0.029 -0.009  0.003  0.019  0.008

     257    258    259    260    261    262    263    264    265    266  \
0 -0.085   0.07  0.005 -0.025 -0.015 -0.023 -0.044 -0.061 -0.092 -0.062
1  -0.02  0.006 -0.002 -0.025 -0.011 -0.009  -0.02      0 -0.032 -0.036
3 -0.073  0.075 -0.001 -0.044 -0.022 -0.028 -0.045 -0.049 -0.083 -0.058
4 -0.125    0.1 -0.006 -0.074 -0.038  -0.05 -0.086 -0.089 -0.131 -0.079
5  0.004  0.002  0.002 -0.024 -0.008 -0.004 -0.006  0.018 -0.013 -0.034

     267    268    269    270    271    272    273    274    275    276  \
0  0.039 -0.024 -0.017 -0.053 -0.089  0.054  0.003 -0.011 -0.018  0.159
1  0.003 -0.005 -0.003 -0.031 -0.043  0.026  0.005 -0.011 -0.028 -0.028
3  0.036 -0.049  -0.02 -0.058 -0.099  0.122  0.006 -0.013 -0.028  0.146
4  0.053 -0.024 -0.044 -0.088 -0.152  0.162  0.011  -0.02  -0.04    0.1
5  0.019  0.003 -0.004  -0.02 -0.017  0.019  0.026  0.001 -0.004   0.18

     277    278    279    280    281    282    283    284    285    286  \
0 -0.055 -0.052 -0.013 -0.062 -0.397  0.023   0.01 -0.068   -0.1 -0.061
1 -0.023 -0.031 -0.047 -0.006  0.009 -0.029   0.03 -0.027 -0.046 -0.039
3 -0.064 -0.059 -0.022 -0.087 -0.107  0.014 -0.003 -0.068 -0.096  -0.06
4 -0.084  -0.09 -0.051 -0.158 -0.181  0.018 -0.046 -0.101 -0.125 -0.073
5 -0.052 -0.036 -0.017 -0.012 -0.018  -0.03  0.046  -0.02 -0.042 -0.039

     287    288    289    290    291    292    293    294    295    296  \
0 -0.479 -4.485 -0.058 -0.055 -0.171 -0.694 -4.222 -4.109 -0.072 -0.065
1 -0.469 -4.489 -0.022 -0.016 -0.147 -0.689 -4.238 -4.111 -0.084 -0.034
3 -0.481 -4.485 -0.062 -0.054 -0.173 -0.696 -4.224 -4.107 -0.086 -0.083
4 -0.493 -4.484 -0.094 -0.082 -0.192 -0.701 -4.219 -4.106 -0.101 -0.131
5 -0.468  -4.49 -0.011 -0.013 -0.143 -0.688 -4.239  -4.11 -0.093 -0.013

     297    298    299    300    301    302    303    304    305       306  \
0  0.003 -0.004  0.011 -0.033 -3.665 -2.676  0.025  0.075 -2.556  0.023846
1  0.006 -0.002 -0.001 -0.057 -3.725 -2.851  0.014  0.023 -2.645  0.027423
3 -0.012 -0.017  0.001 -0.031 -3.643 -2.769  0.016  0.054  -2.58  0.011077
4 -0.038 -0.043 -0.011 -0.145 -3.998 -2.806  0.011  0.052 -2.557 -0.007346
5  0.011  0.004  0.002  -0.06 -3.741 -2.841  0.018  0.022 -2.649     0.035

        307     308      309    310    311    312    313    314    315    316  \
0    -0.103    0.01   0.0178  0.062 -0.051  -0.03 -0.011  0.012  0.005 -0.026
1 -0.054667  0.0135   0.0233  0.054 -0.071  -0.04 -0.011 -0.008 -0.014 -0.029
3 -0.099333  0.0095 -0.00882   0.06  -0.08  -0.05 -0.021 -0.006 -0.012  -0.03
4 -0.134333   0.004 -0.02124  0.067 -0.104 -0.096 -0.039 -0.017 -0.026 -0.041
5 -0.057333   0.012  0.03686  0.051 -0.047 -0.027 -0.005 -0.004 -0.013 -0.022

     317    318    319    320    321    322    323    324    325    326  \
0 -0.014 -0.011  0.002  0.011  2.551 -0.047 -0.046 -0.008  0.005  0.006
1 -0.038 -0.024 -0.004  0.003 -0.002 -0.032 -0.046 -0.021  0.003  0.001
3 -0.036 -0.027 -0.006  0.001 -0.002 -0.043 -0.061  -0.02  0.002 -0.001
4 -0.065 -0.049 -0.017 -0.011 -0.017 -0.051 -0.095 -0.038 -0.002  -0.01
5 -0.027 -0.015      0  0.004      0 -0.025 -0.032 -0.014  0.005  0.005

     327    328    329    330    331    332    333    334    335    336  \
0  0.015  0.002 -0.076 -0.037 -0.016 -0.001 -0.003 -0.001 -0.001 -0.118
1  0.004  0.007 -0.042 -0.043 -0.021  0.001      0      0  0.003 -0.039
3      0 -0.006 -0.074 -0.052 -0.028 -0.002 -0.008  -0.01 -0.012  -0.06
4 -0.019 -0.016 -0.099 -0.082  -0.05 -0.007 -0.017  -0.03 -0.035 -0.086
5  0.008  0.013 -0.031 -0.029 -0.011  0.004  0.004  0.005  0.014 -0.027

     337    338    339    340    341    342    343    344    345    346  \
0 -0.008 -0.003 -0.002  3.024  -0.03 -0.019 -0.015 -0.024 -0.442 -0.001
1  0.003  0.006  0.005  2.952  0.001  0.008  0.006 -0.004 -0.366  0.009
3 -0.012      0 -0.004  3.031 -0.032 -0.016 -0.004 -0.027 -0.089 -0.019
4 -0.026      0 -0.012 -0.033 -0.036  -0.03  0.012 -0.056 -0.056 -0.046
5  0.006  0.007  0.009  2.974  0.007  0.019  0.009  0.008 -0.362  0.017

     347    348    349    350    351    352    353    354    355    356  \
0 -0.198  0.235  0.199  0.074  -0.22  0.069 -0.016  0.102  0.028  0.028
1 -0.123  0.291  0.113  0.056 -0.385  0.051 -0.025  0.036  0.012  0.035
3 -0.233  0.268   0.19  0.051 -0.232  0.063  -0.02  0.098  0.033   0.04
4 -0.319  0.387  0.207  0.025 -0.105 -0.109 -0.066 -0.005 -0.011  -0.01
5 -0.008   0.27  0.115  0.068 -0.024 -0.171 -0.006  0.109 -0.007  0.064

     357    358    359    360    361    362    363    364    365    366  \
0  0.026  0.621   0.06   0.02 -0.008 -0.076 -0.035  0.021 -0.019  0.004
1  0.034  0.086      0 -0.005 -0.007  0.041  0.033  0.012  0.065  0.015
3  0.037  0.607  0.061  0.024 -0.005  -0.04 -0.032  0.008 -0.029 -0.004
4  0.001  0.534  0.042   0.03 -0.012  -0.03 -0.054 -0.011 -0.086  -0.04
5  0.033  0.609  0.063   0.02  0.013  0.069  0.029  0.011 -0.024 -0.001

     367    368    369    370    371    372    373    374    375    376  \
0 -0.007      0  0.005  1.038 -0.014 -0.011 -0.023 -0.041 -0.031  0.064
1 -0.016 -0.011 -0.004  0.992 -0.014 -0.022 -0.014 -0.009      0  0.017
3 -0.011 -0.008  0.001  1.051 -0.023 -0.014 -0.023 -0.046 -0.031  0.051
4 -0.014 -0.013  0.021   1.18  -0.06 -0.017  -0.03 -0.088 -0.051  0.021
5 -0.001 -0.004  0.011  0.949 -0.012  -0.01  0.002 -0.009  0.001 -0.024

     377    378    379    380    381    382    383    384    385    386  \
0 -0.046 -0.049 -0.043 -0.033 -0.028 -0.036 -0.027 -0.049 -0.074 -0.049
1 -0.004 -0.019 -0.018 -0.012 -0.009  0.001 -0.012 -0.036 -0.024 -0.014
3 -0.035 -0.047 -0.043  -0.03 -0.035 -0.047 -0.024 -0.048 -0.065 -0.048
4 -0.047 -0.074 -0.051 -0.039 -0.056 -0.097  0.007 -0.048 -0.109 -0.087
5 -0.025 -0.014 -0.001 -0.003 -0.006 -0.009 -0.011 -0.038 -0.025 -0.007

     387    388    389    390    391    392    393    394    395    396  \
0 -0.047 -0.025 -0.008 -0.014  -0.03 -0.052 -0.028  0.049 -0.102 -0.029
1 -0.015 -0.009      0 -0.033 -0.006 -0.016 -0.008  0.016 -0.029  0.009
3 -0.047 -0.033 -0.019 -0.018  -0.03 -0.054 -0.034  0.029 -0.099 -0.027
4 -0.064  -0.05  -0.04  0.008 -0.087 -0.085 -0.057   0.04  -0.11 -0.057
5 -0.002 -0.002 -0.009 -0.036 -0.012 -0.011 -0.008   0.02  0.007  0.006

     397    398    399    400    401    402    403    404    405    406  \
0  0.063 -0.041 -0.023 -0.006 -0.003 -0.014  0.024  0.012 -0.012 -0.018
1  0.041 -0.027 -0.002  0.011  0.014   0.01 -0.005  0.006 -0.002 -0.008
3  0.028 -0.055 -0.024  -0.01 -0.004 -0.014  0.038  0.017  0.004 -0.015
4 -0.008 -0.125 -0.161 -0.164  0.076  -0.11   0.06 -0.018  0.087 -0.055
5  0.026 -0.051 -0.079  -0.08 -0.042 -0.082  0.116 -0.008  0.126 -0.035

     407    408    409    410    411    412    413    414    415    416  \
0  0.044  0.065  0.022 -0.002  0.059  0.042 -0.017  0.027  0.189  0.147
1   0.05  0.067  0.021 -0.003  0.056  0.043 -0.017  0.005  0.183   0.04
3  0.058  0.085  0.033  0.005  0.065  0.046 -0.024  0.012  0.195   0.15
4  0.038  0.092  0.075  0.003  0.064  0.054 -0.187 -0.304  0.219  0.157
5  0.051  0.086  0.096  0.055  0.051  0.047   -0.1 -0.166  0.174  0.034

     417    418    419    420    421    422    423    424    425    426  \
0  0.021  0.008 -0.004  0.621  0.046 -0.001 -0.027 -0.012 -0.015  0.042
1  0.014  0.001  -0.01  0.609  0.004 -0.018 -0.026 -0.012 -0.008  0.015
3  0.022  0.008 -0.019  0.626  0.046 -0.004  -0.03 -0.016 -0.014  0.024
4  0.019  0.011 -0.185  -0.34  0.049 -0.022 -0.056 -0.052 -0.034 -0.054
5  0.008  0.002 -0.097 -0.206 -0.004 -0.034 -0.039 -0.027 -0.014  -0.02

     427    428    429    430    431    432    433    434    435    436  \
0  0.063 -0.039 -0.151  -0.13 -0.127 -0.017  -0.05 -0.007 -0.079 -0.423
1  0.054 -0.031 -0.148 -0.128 -0.125 -0.004 -0.043 -0.021 -0.071 -0.414
3  0.045 -0.037 -0.148 -0.135 -0.132 -0.018 -0.047 -0.012 -0.077 -0.422
4 -0.301 -0.024  0.005 -0.045 -0.061 -0.069 -0.019 -0.013 -0.026 -0.031
5 -0.279 -0.027 -0.129 -0.144 -0.144 -0.024 -0.037 -0.029 -0.071 -0.411

     437    438    439    440    441    442    443    444    445    446  \
0 -0.238 -0.008  -0.05  0.012 -0.084 -0.023 -0.007 -0.196  0.008 -0.017
1 -0.227  0.003  -0.04  0.024 -0.066 -0.009  0.015 -0.182  0.018 -0.009
3 -0.244 -0.014 -0.051  0.011 -0.084 -0.026 -0.007 -0.194  0.007 -0.021
4 -0.054 -0.069 -0.113 -0.042 -0.061 -0.052 -0.047 -0.197  -0.04 -0.052
5 -0.244  -0.04 -0.071  0.003 -0.071 -0.008  0.002 -0.174 -0.003 -0.016

     447       448    449    450    451    452    453    454    455    456  \
0 -0.018  0.013176  1.221  0.048  0.134 -0.015  0.028 -0.006 -0.051  0.034

In [76]:
x_df = x_df.loc[(x_df!="?").any(axis=1)]

In [77]:
x_df.head(100)

,0,1,2,3,4,5,6,7,8,9,...,5398,5399,5400,5401,5402,5403,5404,5405,5406,5407
0,-0.161,-0.014,0.002,-0.036,-0.033,-0.093,0.025,0.005,0,-0.015,...,-0.015,0.006,0.013,0.021,0.02,0.016,-0.011,0.003,0.01,-0.007
1,-0.158,-0.002,-0.012,-0.025,-0.012,-0.106,0.013,0.005,0,-0.002,...,-0.007,0.002,-0.008,0.007,0.015,-0.008,-0.011,-0.004,0.013,0.005
3,-0.169,-0.025,-0.01,-0.041,-0.045,-0.069,0.038,0.014,0.008,-0.014,...,-0.016,0.019,0.01,0.025,0.025,0.021,-0.012,0.006,0.016,-0.018
4,-0.183,-0.051,-0.023,-0.077,-0.092,-0.015,0.071,0.027,0.02,-0.019,...,-0.028,0.051,0.012,0.05,0.038,0.051,-0.015,0.017,0.027,-0.049
5,-0.154,0.005,-0.011,-0.013,-0.002,-0.115,0.005,0.002,-0.003,0.002,...,0.027,-0.011,0.012,0.009,0.003,-0.001,0.002,-0.006,0.009,0.013
6,-0.15,0.016,-0.014,0,0.016,-0.123,-0.004,-0.002,-0.005,0.01,...,0.015,0,-0.033,-0.032,0.029,-0.052,-0.029,-0.006,0.004,0.023
7,-0.158,0.002,-0.019,-0.028,-0.008,-0.101,0.011,0.005,0.001,0.003,...,0.036,0.015,-0.025,-0.003,0.017,-0.017,-0.009,-0.001,0.017,0.012
8,-0.152,0.009,-0.015,-0.008,0.004,-0.12,-0.002,-0.002,-0.007,0.004,...,-0.003,-0.014,-0.009,-0.007,0.009,-0.027,-0.012,-0.009,0.008,0.021
9,-0.172,-0.028,0.003,-0.045,-0.055,-0.078,0.039,0.011,0.006,-0.02,...,-0.061,0.016,0.031,-0.059,0.05,0.01,-0.005,0.137,0.098,-0.015
10,-0.164,-0.019,-0.011,-0.037,-0.031,-0.081,0.029,0.012,0.007,-0.01,...,-0.012,0.012,0.006,0.019,0.022,0.011,-0.012,0.002,0.014,-0.009
11,-0.148,0.018,-0.012,0.004,0.021,-0.128,-0.007,-0.003,-0.006,0.01,...,-0.005,-0.02,-0.013,-0.011,0.004,-0.035,-0.011,-0.011,0.008,0.026
12,-0.153,0.012,-0.017,-0.009,0.006,-0.116,0,0.001,-0.004,0.008,...,-0.002,-0.011,-0.014,-0.008,0.008,-0.028,-0.011,-0.009,0.011,0.019
13,-0.161,-0.014,0.001,-0.033,-0.027,-0.093,0.023,0.007,0.003,-0.013,...,-0.007,-0.017,0.016,0.019,0.074,-0.032,-0.041,-0.002,0.01,0.025
14,-0.153,0.01,-0.017,-0.012,0.004,-0.112,0.004,0.002,-0.002,0.007,...,0.009,0.031,-0.027,-0.011,0.026,-0.025,-0.013,-0.006,0.009,0.02
15,-0.153,0.006,-0.011,-0.01,0,-0.119,0.003,0,-0.005,0.004,...,-0.007,-0.008,-0.008,0,0.011,-0.021,-0.012,-0.008,0.008,0.017
16,?,?,?,?,?,?,?,?,?,?,...,0.001,-0.018,-0.014,-0.013,0.006,-0.035,-0.012,-0.011,0.008,0.026
17,-3.272,-0.168,0.113,0.064,0.057,-0.05,0.084,0.097,0.089,-0.078,...,-0.008,-0.014,-0.019,-0.014,0.005,-0.037,-0.012,-0.011,0.006,0.028
18,-0.141,0.035,-0.015,0.023,0.059,-0.143,-0.018,-0.006,-0.01,0.018,...,0.007,-0.028,-0.023,-0.024,-0.002,-0.054,-0.011,-0.016,0.007,0.039
19,-0.166,-0.019,0,-0.041,-0.038,-0.093,0.029,0.008,0.003,-0.017,...,-0.012,0.005,0.022,0.016,0.023,0.016,-0.013,0.005,0.01,-0.009
20,-0.175,-0.036,-0.022,-0.058,-0.061,-0.043,0.052,0.022,0.015,-0.014,...,-0.019,0.036,0.004,0.033,0.032,0.029,-0.014,0.009,0.023,-0.031
21,-0.158,-0.004,-0.014,-0.026,-0.011,-0.099,0.013,0.006,0.002,0,...,-0.006,0.001,-0.005,0.004,0.015,-0.011,-0.012,-0.005,0.012,0.006
22,-0.14,0.043,-0.015,0.033,0.08,-0.148,-0.027,-0.011,-0.014,0.023,...,0.009,-0.037,-0.026,-0.031,-0.005,-0.064,-0.011,-0.018,0.006,0.047
23,-0.164,-0.013,-0.005,-0.032,-0.028,-0.1,0.023,0.007,0.002,-0.012,...,0,-0.016,-0.004,0.03,0.002,-0.003,-0.001,-0.003,0.006,0.003
24,-0.142,0.039,-0.016,0.028,0.071,-0.144,-0.022,-0.009,-0.012,0.021,...,0.006,-0.032,-0.025,-0.028,-0.003,-0.059,-0.012,-0.017,0.006,0.043
25,-0.156,-0.002,-0.01,-0.018,-0.009,-0.108,0.011,0.003,-0.002,-0.002,...,-0.001,-0.007,0.002,0,0.014,-0.012,-0.013,-0.005,0.01,0.011
26,-0.148,0.024,-0.015,0.008,0.033,-0.129,-0.01,-0.003,-0.008,0.013,...,0.002,-0.02,-0.018,-0.017,0.003,-0.042,-0.012,-0.012,0.009,0.03
27,-0.16,-0.005,-0.013,-0.031,-0.016,-0.096,0.017,0.007,0.002,-0.003,...,-0.009,0.004,-0.004,0.007,0.016,-0.006,-0.012,-0.003,0.013,0.003
28,-0.146,0.026,-0.015,0.01,0.037,-0.131,-0.011,-0.003,-0.008,0.014,...,0,-0.023,-0.018,-0.018,0.002,-0.044,-0.011,-0.013,0.008,0.032
29,-0.168,-0.019,-0.01,-0.037,-0.039,-0.074,0.033,0.012,0.007,-0.013,...,-0.015,0.016,0.008,0.022,0.023,0.017,-0.013,0.005,0.016,-0.015
30,-0.155,0.002,-0.01,-0.016,-0.009,-0.111,0.009,0.003,-0.001,-0.001,...,-0.012,-0.001,-0.002,-0.003,0.012,-0.015,-0.015,-0.004,0.006,0.012
31,-0.169,-0.022,0.002,-0.04,-0.041,-0.095,0.031,0.008,0.003,-0.019,...,-0.013,0.006,0.022,0.021,0.023,0.022,-0.01,0.006,0.01,-0.01
32,-0.152,0.01,-0.013,-0.007,0.007,-0.117,0,0.001,-0.003,0.007,...,-0.002,-0.013,-0.01,-0.007,0.008,-0.027,-0.011,-0.009,0.01,0.02
33,-0.17,-0.024,-0.005,-0.042,-0.047,-0.077,0.037,0.013,0.007,-0.017,...,-0.021,-0.161,0.049,-0.203,0.05,-0.185,0.068,0.041,-0.112,0.101
34,-0.152,0.008,-0.013,-0.009,0.004,-0.115,0.002,0.002,-0.003,0.005,...,0.002,-0.012,-0.008,-0.008,0.009,-0.025,-0.011,-0.007,0.01,0.018
35,-0.152,0.011,-0.013,-0.006,0.006,-0.118,0,0.002,-0.003,0.005,...,-0.003,-0.013,-0.01,-0.007,0.008,-0.026,-0.011,-0.009,0.009,0.02
36,-0.155,0.004,-0.01,-0.011,-0.003,-0.111,0.007,0.003,-0.002,0.002,...,-0.004,-0.008,-0.006,-0.001,0.009,-0.019,-0.01,-0.006,0.01,0.014
37,-0.166,-0.022,-0.007,-0.038,-0.039,-0.079,0.034,0.012,0.005,-0.014,...,-0.015,0.014,0.012,0.024,0.024,0.021,-0.011,0.004,0.013,-0.014
38,-0.176,-0.035,0.009,-0.049,-0.061,-0.086,0.044,0.009,0.003,-0.027,...,-0.039,0.018,0.038,0.02,0.037,0.041,-0.016,0.015,0.01,-0.023
39,-0.16,-0.01,-0.016,-0.037,-0.019,-0.092,0.019,0.008,0.003,-0.004,...,-0.026,0.01,0,0.002,0.023,-0.003,-0.016,-0.001,0.015,-0.002
40,-0.166,-0.017,-0.003,-0.037,-0.035,-0.087,0.029,0.01,0.005,-0.014,...,-0.032,0.017,0.014,0.01,0.029,0.017,-0.016,0.005,0.012,-0.011
41,-5.837,-2.313,-2.874,-3.357,-3.221,-0.077,0.041,0.043,-0.041,-0.211,...,-0.013,0.005,0.005,0.012,0.018,0.005,-0.012,0.001,0.011,-0.003
42,-3.302,-0.188,0.126,0.045,0.016,-0.021,0.114,0.112,0.111,-0.083,...,-0.007,-0.004,0.001,0.005,0.014,-0.007,-0.011,-0.003,0.01,0.007
43,-2.716,0.053,-0.006,-0.028,-0.02,-0.046,0.048,-0.002,-0.042,-0.04,...,-0.008,0,0.004,0.009,0.016,-0.001,-0.01,-0.001,0.01,0.002
44,-0.181,-0.046,-0.019,-0.071,-0.084,-0.026,0.066,0.026,0.019,-0.019,...,-0.022,0.048,0.037,0.063,0.023,0.078,0.007,0.015,0.023,-0.047
45,-0.152,0.008,-0.014,-0.012,0,-0.109,0.004,0.001,-0.005,0,...,0.005,-0.008,-0.009,-0.002,0.011,-0.02,-0.013,-0.009,0.011,0.017
46,-0.174,-0.033,0.006,-0.049,-0.063,-0.08,0.044,0.01,0.008,-0.025,...,-0.017,0.017,0.03,0.036,0.03,0.041,-0.011,0.013,0.011,-0.024
47,-0.162,-0.01,-0.007,-0.035,-0.024,-0.097,0.021,0.007,0.003,-0.009,...,0.024,0.004,0.022,0.027,0.01,0.024,0.003,0.001,0.012,-0.004
48,-0.163,-0.011,-0.02,-0.038,-0.022,-0.083,0.024,0.011,0.005,-0.004,...,0.036,0.009,0.018,0.03,0.014,0.019,-0.003,0,0.017,-0.008
49,-0.168,-0.021,-0.009,-0.037,-0.038,-0.079,0.033,0.012,0.007,-0.013,...,0.049,0.019,-0.008,0.021,0.021,0.012,-0.009,0.004,0.019,-0.008
50,-0.152,0.015,-0.013,0.002,0.018,-0.12,-0.003,-0.001,-0.005,0.008,...,0.003,-0.022,-0.009,-0.017,0.006,-0.034,-0.01,-0.01,0.007,0.025
51,-0.155,0.002,-0.011,-0.014,-0.005,-0.112,0.008,0.004,-0.001,0.001,...,-0.008,-0.008,0.018,0.023,0.097,-0.047,-0.031,-0.005,0.005,0.049
52,-0.162,-0.009,-0.004,-0.028,-0.026,-0.104,0.02,0.006,0,-0.011,...,-0.015,-0.044,-0.034,-0.013,0.023,-0.092,-0.097,-0.022,-0.017,-0.039
53,-0.164,-0.016,-0.016,-0.038,-0.029,-0.083,0.028,0.013,0.008,-0.009,...,-0.01,0.001,0.018,0.011,0.021,0.005,-0.016,0.001,0.017,-0.009
54,-0.158,-0.004,-0.018,-0.031,-0.011,-0.1,0.013,0.006,0.002,0,...,-0.007,0,-0.006,0.004,0.015,-0.011,-0.012,-0.004,0.013,0.006
55,-0.184,-0.05,0.009,-0.072,-0.098,-0.048,0.062,0.014,0.009,-0.03,...,-0.022,0.039,0.032,0.057,0.036,0.064,-0.014,0.022,0.018,-0.047
56,-0.18,0.256,0.076,-0.07,-0.134,-0.075,0.069,0.006,-0.011,-0.051,...,-0.046,0.013,0.096,0.059,0.058,0.108,-0.027,0.035,-0.021,-0.068
57,-0.138,0.049,-0.016,0.038,0.091,-0.152,-0.031,-0.012,-0.016,0.024,...,-0.011,-0.033,-0.035,-0.038,-0.003,-0.069,-0.017,-0.018,0.001,0.047
58,-0.18,-0.037,0.013,-0.057,-0.074,-0.103,0.047,0.009,0.001,-0.03,...,-0.047,0.022,0.036,0.026,0.044,0.051,-0.026,0.02,-0.006,-0.036
59,-0.165,-0.02,0.002,-0.039,-0.038,-0.092,0.029,0.008,0.003,-0.017,...,-0.037,0.012,0.016,0.011,0.032,0.016,-0.023,0.006,0.003,-0.019
60,-0.172,-0.035,0,-0.049,-0.061,-0.073,0.045,0.013,0.007,-0.022,...,-0.044,0.025,0.021,0.024,0.04,0.034,-0.024,0.012,0.006,-0.034
61,-0.163,-0.013,-0.015,-0.037,-0.025,-0.086,0.024,0.01,0.005,-0.006,...,-0.055,0.017,-0.008,0,0.03,-0.001,-0.025,0.002,0.009,-0.014
62,-0.171,-0.029,-0.017,-0.048,-0.051,-0.061,0.043,0.017,0.01,-0.014,...,-0.039,0.02,-0.002,0.028,0.027,0.018,-0.02,0.008,0.012,-0.031
63,-0.171,-0.026,-0.017,-0.045,-0.047,-0.066,0.039,0.017,0.011,-0.01,...,-0.046,0.027,0.004,0.02,0.036,0.017,-0.025,0.007,0.013,-0.031
64,-0.166,-0.02,-0.008,-0.037,-0.037,-0.08,0.032,0.01,0.005,-0.013,...,0.038,0.041,-0.008,0.023,0.043,0.011,-0.007,0.015,0.018,-0.002
65,-0.166,-0.018,-0.012,-0.037,-0.032,-0.078,0.031,0.013,0.006,-0.009,...,-0.004,0.039,-0.004,-0.062,0.065,-0.019,0.048,0.186,0.125,0.042
66,-0.175,-0.032,0.007,-0.049,-0.062,-0.087,0.042,0.009,0.005,-0.024,...,0.007,0.046,0.029,0.001,0.048,0.041,0.058,0.2,0.054,-0.017
67,-0.167,-0.021,-0.011,-0.038,-0.037,-0.076,0.033,0.012,0.007,-0.011,...,0.038,0.043,-0.011,0.022,0.043,0.01,-0.007,0.014,0.02,-0.003
68,-0.168,-0.023,0.007,-0.037,-0.045,-0.086,0.033,0.007,0.004,-0.02,...,0.038,0.036,0.007,0.029,0.045,0.02,-0.006,0.019,0.013,-0.003
69,-0.167,-0.019,-0.003,-0.039,-0.038,-0.09,0.029,0.01,0.005,-0.016,...,0.035,0.033,0,0.022,0.042,0.011,-0.006,0.016,0.014,0.002
70,-0.173,-0.035,0.01,-0.051,-0.068,-0.073,0.047,0.01,0.008,-0.025,...,0.038,0.048,0.014,0.044,0.055,0.036,-0.006,0.026,0.016,-0.014
71,-0.165,-0.019,-0.012,-0.036,-0.032,-0.081,0.031,0.013,0.007,-0.011,...,0.045,0.04,0.02,0.049,0.14,-0.023,-0.03,0.014,0.013,0.041
72,-0.153,0.009,-0.014,-0.009,0.004,-0.117,0.001,0,-0.004,0.006,...,0.039,0.011,-0.025,-0.008,0.024,-0.029,-0.007,0,0.013,0.027
73,-0.153,0.016,-0.019,-0.001,0.016,-0.122,-0.007,-0.006,-0.01,0.005,...,-0.001,-0.016,-0.012,-0.011,0.006,-0.032,-0.011,-0.01,0.009,0.024
74,-0.173,0.08,0.057,-0.037,-0.076,-0.106,0.034,-0.008,-0.012,-0.043,...,-0.015,-0.005,0.065,0.056,0.027,0.065,-0.012,0.024,0.001,-0.024
75,-0.15,0.013,-0.013,-0.003,0.009,-0.12,-0.001,0.001,-0.004,0.007,...,-0.001,-0.015,-0.011,-0.009,0.007,-0.03,-0.011,-0.01,0.009,0.022
76,-0.159,-0.005,-0.013,-0.03,-0.014,-0.097,0.016,0.007,0.002,-0.003,...,-0.007,0.003,-0.006,0.006,0.015,-0.008,-0.012,-0.003,0.013,0.003
77,-0.162,-0.011,-0.011,-0.035,-0.022,-0.095,0.021,0.008,0.004,-0.006,...,-0.013,-0.138,-0.007,-0.128,0.039,-0.174,0.067,0.024,-0.094,0.105
78,-0.168,-0.022,0,-0.039,-0.041,-0.091,0.031,0.008,0.004,-0.018,...,-0.06,0.003,0.031,-0.074,0.046,-0.001,0.022,0.165,0.125,0.019
79,-0.146,0.025,-0.015,0.011,0.039,-0.133,-0.013,-0.004,-0.006,0.014,...,0.003,-0.023,-0.019,-0.018,0.002,-0.044,-0.011,-0.014,0.008,0.033
80,-0.17,-0.03,0.009,-0.046,-0.06,-0.072,0.04,0.009,0.005,-0.023,...,-0.024,0.02,0.026,0.032,0.03,0.037,-0.015,0.012,0.014,-0.025
81,-0.167,-0.023,-0.013,0.175,0.274,-0.07,0.037,0.016,0.011,-0.011,...,-0.016,0.019,0.006,0.023,0.024,0.017,-0.013,0.005,0.016,-0.016
82,-0.169,-0.024,-0.024,-0.041,-0.037,-0.066,0.036,0.017,0.01,-0.007,...,-0.016,0.023,-0.002,0.021,0.025,0.012,-0.013,0.004,0.02,-0.017
83,-0.148,0.021,-0.014,0.007,0.028,-0.13,-0.009,-0.003,-0.007,0.012,...,-0.002,-0.02,-0.016,-0.015,0.004,-0.038,-0.011,-0.012,0.006,0.029
84,-0.159,-0.006,-0.009,-0.028,-0.018,-0.1,0.016,0.005,0,-0.007,...,-0.01,0,0.002,0.007,0.016,-0.003,-0.011,-0.002,0.011,0.003
85,-0.149,0.019,-0.013,0.005,0.025,-0.129,-0.008,-0.002,-0.007,0.011,...,-0.007,-0.014,-0.015,-0.015,0.002,-0.039,-0.009,-0.013,0.006,0.028
86,-0.171,-0.027,-0.007,-0.044,-0.05,-0.07,0.039,0.014,0.007,-0.014,...,-0.025,0.022,0.01,0.028,0.026,0.025,-0.012,0.008,0.014,-0.022
87,-0.153,0.007,-0.014,-0.01,0.004,-0.114,0.004,0.002,-0.003,0.005,...,-0.004,-0.01,-0.008,-0.004,0.01,-0.023,-0.011,-0.008,0.01,0.016
88,-0.159,-0.003,-0.008,-0.021,-0.014,-0.11,0.013,0.004,-0.001,-0.004,...,-0.052,-0.009,0.013,-0.084,0.032,-0.029,0.022,0.152,0.117,0.033
89,-0.147,0.022,-0.013,0.011,0.035,-0.131,-0.01,-0.003,-0.007,0.011,...,-0.035,-0.019,-0.009,-0.04,-0.017,-0.027,0.058,0.156,0.041,0.014
90,-0.157,-0.002,-0.009,-0.021,-0.012,-0.107,0.012,0.004,-0.001,-0.004,...,-0.004,-0.008,0.002,0.004,0.014,-0.009,-0.011,-0.003,0.01,0.008
91,-0.155,0.004,-0.01,-0.013,-0.003,-0.112,0.007,0.002,-0.003,0.001,...,-0.005,-0.009,-0.004,-0.001,0.011,-0.017,-0.011,-0.006,0.009,0.014
92,-0.186,-0.058,-0.018,-0.086,-0.104,-0.006,0.08,0.029,0.024,-0.023,...,-0.028,0.055,0.02,0.059,0.042,0.062,-0.014,0.019,0.026,-0.055
93,-0.177,-0.033,0.025,-0.05,-0.071,-0.103,0.043,0.004,-0.002,-0.034,...,-0.007,-0.014,0.022,0.075,-0.002,0.039,0.005,0.014,0.001,-0.018
94,-0.158,-0.005,-0.013,-0.031,-0.015,-0.097,0.016,0.007,0.002,-0.002,...,-0.008,0.002,-0.003,0.006,0.016,-0.007,-0.012,-0.003,0.013,0.003
95,-0.16,-0.009,-0.007,-0.027,-0.019,-0.109,0.017,0.006,0,-0.006,...,-0.01,-0.004,0.006,0.009,0.017,-0.001,-0.011,-0.002,0.008,0.005
96,-0.169,-0.021,0,-0.039,-0.044,-0.095,0.031,0.009,0,-0.021,...,-0.014,0.006,0.025,0.011,0.027,0.017,-0.017,0.006,0.008,-0.011
97,-0.16,-0.006,-0.014,-0.033,-0.017,-0.098,0.018,0.007,0.002,-0.004,...,-0.01,0.002,-0.002,0.008,0.016,-0.005,-0.012,-0.002,0.012,0.002
98,-0.178,-0.046,-0.024,-0.069,-0.078,-0.022,0.066,0.027,0.019,-0.016,...,-0.023,0.046,0.01,0.043,0.036,0.043,-0.013,0.011,0.024,-0.041
99,-0.192,-0.075,-0.014,-0.104,-0.133,0.028,0.102,0.033,0.026,-0.027,...,-0.032,0.071,0.031,0.078,0.05,0.086,-0.015,0.026,0.029,-0.073
100,-0.171,-0.026,0.009,-0.042,-0.055,-0.083,0.037,0.007,0.004,-0.023,...,-0.014,0.012,0.027,0.031,0.026,0.035,-0.012,0.011,0.01,-0.02

In [79]:
from sklearn.impute import KNNImputer

# Replace '?' with np.nan explicitly
x_df = x_df.replace("?", np.nan)

/tmp/ipykernel_4416/1846180426.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x_df = x_df.replace("?", np.nan)

In [80]:
x_df.shape

(1895, 5408)

In [81]:
x_df.head(17)

,0,1,2,3,4,5,6,7,8,9,...,5398,5399,5400,5401,5402,5403,5404,5405,5406,5407
0,-0.161,-0.014,0.002,-0.036,-0.033,-0.093,0.025,0.005,0.000,-0.015,...,-0.015,0.006,0.013,0.021,0.020,0.016,-0.011,0.003,0.010,-0.007
1,-0.158,-0.002,-0.012,-0.025,-0.012,-0.106,0.013,0.005,0.000,-0.002,...,-0.007,0.002,-0.008,0.007,0.015,-0.008,-0.011,-0.004,0.013,0.005
3,-0.169,-0.025,-0.010,-0.041,-0.045,-0.069,0.038,0.014,0.008,-0.014,...,-0.016,0.019,0.010,0.025,0.025,0.021,-0.012,0.006,0.016,-0.018
4,-0.183,-0.051,-0.023,-0.077,-0.092,-0.015,0.071,0.027,0.020,-0.019,...,-0.028,0.051,0.012,0.050,0.038,0.051,-0.015,0.017,0.027,-0.049
5,-0.154,0.005,-0.011,-0.013,-0.002,-0.115,0.005,0.002,-0.003,0.002,...,0.027,-0.011,0.012,0.009,0.003,-0.001,0.002,-0.006,0.009,0.013
6,-0.150,0.016,-0.014,0.000,0.016,-0.123,-0.004,-0.002,-0.005,0.010,...,0.015,0.000,-0.033,-0.032,0.029,-0.052,-0.029,-0.006,0.004,0.023
7,-0.158,0.002,-0.019,-0.028,-0.008,-0.101,0.011,0.005,0.001,0.003,...,0.036,0.015,-0.025,-0.003,0.017,-0.017,-0.009,-0.001,0.017,0.012
8,-0.152,0.009,-0.015,-0.008,0.004,-0.120,-0.002,-0.002,-0.007,0.004,...,-0.003,-0.014,-0.009,-0.007,0.009,-0.027,-0.012,-0.009,0.008,0.021
9,-0.172,-0.028,0.003,-0.045,-0.055,-0.078,0.039,0.011,0.006,-0.020,...,-0.061,0.016,0.031,-0.059,0.050,0.010,-0.005,0.137,0.098,-0.015
10,-0.164,-0.019,-0.011,-0.037,-0.031,-0.081,0.029,0.012,0.007,-0.010,...,-0.012,0.012,0.006,0.019,0.022,0.011,-0.012,0.002,0.014,-0.009
11,-0.148,0.018,-0.012,0.004,0.021,-0.128,-0.007,-0.003,-0.006,0.010,...,-0.005,-0.020,-0.013,-0.011,0.004,-0.035,-0.011,-0.011,0.008,0.026
12,-0.153,0.012,-0.017,-0.009,0.006,-0.116,0.000,0.001,-0.004,0.008,...,-0.002,-0.011,-0.014,-0.008,0.008,-0.028,-0.011,-0.009,0.011,0.019
13,-0.161,-0.014,0.001,-0.033,-0.027,-0.093,0.023,0.007,0.003,-0.013,...,-0.007,-0.017,0.016,0.019,0.074,-0.032,-0.041,-0.002,0.010,0.025
14,-0.153,0.010,-0.017,-0.012,0.004,-0.112,0.004,0.002,-0.002,0.007,...,0.009,0.031,-0.027,-0.011,0.026,-0.025,-0.013,-0.006,0.009,0.020
15,-0.153,0.006,-0.011,-0.010,0.000,-0.119,0.003,0.000,-0.005,0.004,...,-0.007,-0.008,-0.008,0.000,0.011,-0.021,-0.012,-0.008,0.008,0.017
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.001,-0.018,-0.014,-0.013,0.006,-0.035,-0.012,-0.011,0.008,0.026
17,-3.272,-0.168,0.113,0.064,0.057,-0.050,0.084,0.097,0.089,-0.078,...,-0.008,-0.014,-0.019,-0.014,0.005,-0.037,-0.012,-0.011,0.006,0.028

In [82]:
# Convert any 'pd.NA' to np.nan
x_df = x_df.applymap(lambda x: np.nan if pd.isna(x) else x)

# Ensure all values are numeric
x_df = x_df.astype(float)

/tmp/ipykernel_4416/2348258333.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  x_df = x_df.applymap(lambda x: np.nan if pd.isna(x) else x)

In [48]:
# n_neighbors = 1 
# Apply KNN Imputer
imputer = KNNImputer(n_neighbors=1)
x_df_1 = imputer.fit_transform(x_df)  # Returns a NumPy array

# Convert back to DataFrame
x_df_1 = pd.DataFrame(x_df_1)

# Check for remaining NaNs
print(x_df_1.isna().sum().sum())  # Should print 0 if all missing values are imputed

0

In [49]:
x_df_1.head(20)

,0,1,2,3,4,5,6,7,8,9,...,5398,5399,5400,5401,5402,5403,5404,5405,5406,5407
0,-0.161,-0.014,0.002,-0.036,-0.033,-0.093,0.025,0.005,0.000,-0.015,...,-0.015,0.006,0.013,0.021,0.020,0.016,-0.011,0.003,0.010,-0.007
1,-0.158,-0.002,-0.012,-0.025,-0.012,-0.106,0.013,0.005,0.000,-0.002,...,-0.007,0.002,-0.008,0.007,0.015,-0.008,-0.011,-0.004,0.013,0.005
2,-0.169,-0.025,-0.010,-0.041,-0.045,-0.069,0.038,0.014,0.008,-0.014,...,-0.016,0.019,0.010,0.025,0.025,0.021,-0.012,0.006,0.016,-0.018
3,-0.183,-0.051,-0.023,-0.077,-0.092,-0.015,0.071,0.027,0.020,-0.019,...,-0.028,0.051,0.012,0.050,0.038,0.051,-0.015,0.017,0.027,-0.049
4,-0.154,0.005,-0.011,-0.013,-0.002,-0.115,0.005,0.002,-0.003,0.002,...,0.027,-0.011,0.012,0.009,0.003,-0.001,0.002,-0.006,0.009,0.013
5,-0.150,0.016,-0.014,0.000,0.016,-0.123,-0.004,-0.002,-0.005,0.010,...,0.015,0.000,-0.033,-0.032,0.029,-0.052,-0.029,-0.006,0.004,0.023
6,-0.158,0.002,-0.019,-0.028,-0.008,-0.101,0.011,0.005,0.001,0.003,...,0.036,0.015,-0.025,-0.003,0.017,-0.017,-0.009,-0.001,0.017,0.012
7,-0.152,0.009,-0.015,-0.008,0.004,-0.120,-0.002,-0.002,-0.007,0.004,...,-0.003,-0.014,-0.009,-0.007,0.009,-0.027,-0.012,-0.009,0.008,0.021
8,-0.172,-0.028,0.003,-0.045,-0.055,-0.078,0.039,0.011,0.006,-0.020,...,-0.061,0.016,0.031,-0.059,0.050,0.010,-0.005,0.137,0.098,-0.015
9,-0.164,-0.019,-0.011,-0.037,-0.031,-0.081,0.029,0.012,0.007,-0.010,...,-0.012,0.012,0.006,0.019,0.022,0.011,-0.012,0.002,0.014,-0.009
10,-0.148,0.018,-0.012,0.004,0.021,-0.128,-0.007,-0.003,-0.006,0.010,...,-0.005,-0.020,-0.013,-0.011,0.004,-0.035,-0.011,-0.011,0.008,0.026
11,-0.153,0.012,-0.017,-0.009,0.006,-0.116,0.000,0.001,-0.004,0.008,...,-0.002,-0.011,-0.014,-0.008,0.008,-0.028,-0.011,-0.009,0.011,0.019
12,-0.161,-0.014,0.001,-0.033,-0.027,-0.093,0.023,0.007,0.003,-0.013,...,-0.007,-0.017,0.016,0.019,0.074,-0.032,-0.041,-0.002,0.010,0.025
13,-0.153,0.010,-0.017,-0.012,0.004,-0.112,0.004,0.002,-0.002,0.007,...,0.009,0.031,-0.027,-0.011,0.026,-0.025,-0.013,-0.006,0.009,0.020
14,-0.153,0.006,-0.011,-0.010,0.000,-0.119,0.003,0.000,-0.005,0.004,...,-0.007,-0.008,-0.008,0.000,0.011,-0.021,-0.012,-0.008,0.008,0.017
15,-3.272,-0.168,0.113,0.064,0.057,-0.050,0.084,0.097,0.089,-0.078,...,0.001,-0.018,-0.014,-0.013,0.006,-0.035,-0.012,-0.011,0.008,0.026
16,-3.272,-0.168,0.113,0.064,0.057,-0.050,0.084,0.097,0.089,-0.078,...,-0.008,-0.014,-0.019,-0.014,0.005,-0.037,-0.012,-0.011,0.006,0.028
17,-0.141,0.035,-0.015,0.023,0.059,-0.143,-0.018,-0.006,-0.010,0.018,...,0.007,-0.028,-0.023,-0.024,-0.002,-0.054,-0.011,-0.016,0.007,0.039
18,-0.166,-0.019,0.000,-0.041,-0.038,-0.093,0.029,0.008,0.003,-0.017,...,-0.012,0.005,0.022,0.016,0.023,0.016,-0.013,0.005,0.010,-0.009
19,-0.175,-0.036,-0.022,-0.058,-0.061,-0.043,0.052,0.022,0.015,-0.014,...,-0.019,0.036,0.004,0.033,0.032,0.029,-0.014,0.009,0.023,-0.031

In [83]:
# n_neighbors = 1 
# Apply KNN Imputer
imputer = KNNImputer(n_neighbors=3)
x_df_3 = imputer.fit_transform(x_df)  # Returns a NumPy array

# Convert back to DataFrame
x_df_3 = pd.DataFrame(x_df_3)

# Check for remaining NaNs
print(x_df_3.isna().sum().sum())  # Should print 0 if all missing values are imputed

0

In [84]:
x_df_3.head(20)

,0,1,2,3,4,5,6,7,8,9,...,5398,5399,5400,5401,5402,5403,5404,5405,5406,5407
0,-0.161,-0.014000,0.002000,-0.036000,-0.033000,-0.093000,0.025000,0.005000,0.000000,-0.015000,...,-0.015,0.006,0.013,0.021,0.020,0.016,-0.011,0.003,0.010,-0.007
1,-0.158,-0.002000,-0.012000,-0.025000,-0.012000,-0.106000,0.013000,0.005000,0.000000,-0.002000,...,-0.007,0.002,-0.008,0.007,0.015,-0.008,-0.011,-0.004,0.013,0.005
2,-0.169,-0.025000,-0.010000,-0.041000,-0.045000,-0.069000,0.038000,0.014000,0.008000,-0.014000,...,-0.016,0.019,0.010,0.025,0.025,0.021,-0.012,0.006,0.016,-0.018
3,-0.183,-0.051000,-0.023000,-0.077000,-0.092000,-0.015000,0.071000,0.027000,0.020000,-0.019000,...,-0.028,0.051,0.012,0.050,0.038,0.051,-0.015,0.017,0.027,-0.049
4,-0.154,0.005000,-0.011000,-0.013000,-0.002000,-0.115000,0.005000,0.002000,-0.003000,0.002000,...,0.027,-0.011,0.012,0.009,0.003,-0.001,0.002,-0.006,0.009,0.013
5,-0.150,0.016000,-0.014000,0.000000,0.016000,-0.123000,-0.004000,-0.002000,-0.005000,0.010000,...,0.015,0.000,-0.033,-0.032,0.029,-0.052,-0.029,-0.006,0.004,0.023
6,-0.158,0.002000,-0.019000,-0.028000,-0.008000,-0.101000,0.011000,0.005000,0.001000,0.003000,...,0.036,0.015,-0.025,-0.003,0.017,-0.017,-0.009,-0.001,0.017,0.012
7,-0.152,0.009000,-0.015000,-0.008000,0.004000,-0.120000,-0.002000,-0.002000,-0.007000,0.004000,...,-0.003,-0.014,-0.009,-0.007,0.009,-0.027,-0.012,-0.009,0.008,0.021
8,-0.172,-0.028000,0.003000,-0.045000,-0.055000,-0.078000,0.039000,0.011000,0.006000,-0.020000,...,-0.061,0.016,0.031,-0.059,0.050,0.010,-0.005,0.137,0.098,-0.015
9,-0.164,-0.019000,-0.011000,-0.037000,-0.031000,-0.081000,0.029000,0.012000,0.007000,-0.010000,...,-0.012,0.012,0.006,0.019,0.022,0.011,-0.012,0.002,0.014,-0.009
10,-0.148,0.018000,-0.012000,0.004000,0.021000,-0.128000,-0.007000,-0.003000,-0.006000,0.010000,...,-0.005,-0.020,-0.013,-0.011,0.004,-0.035,-0.011,-0.011,0.008,0.026
11,-0.153,0.012000,-0.017000,-0.009000,0.006000,-0.116000,0.000000,0.001000,-0.004000,0.008000,...,-0.002,-0.011,-0.014,-0.008,0.008,-0.028,-0.011,-0.009,0.011,0.019
12,-0.161,-0.014000,0.001000,-0.033000,-0.027000,-0.093000,0.023000,0.007000,0.003000,-0.013000,...,-0.007,-0.017,0.016,0.019,0.074,-0.032,-0.041,-0.002,0.010,0.025
13,-0.153,0.010000,-0.017000,-0.012000,0.004000,-0.112000,0.004000,0.002000,-0.002000,0.007000,...,0.009,0.031,-0.027,-0.011,0.026,-0.025,-0.013,-0.006,0.009,0.020
14,-0.153,0.006000,-0.011000,-0.010000,0.000000,-0.119000,0.003000,0.000000,-0.005000,0.004000,...,-0.007,-0.008,-0.008,0.000,0.011,-0.021,-0.012,-0.008,0.008,0.017
15,-1.187,-0.036333,0.027667,0.031667,0.049667,-0.107333,0.018667,0.029333,0.023667,-0.015667,...,0.001,-0.018,-0.014,-0.013,0.006,-0.035,-0.012,-0.011,0.008,0.026
16,-3.272,-0.168000,0.113000,0.064000,0.057000,-0.050000,0.084000,0.097000,0.089000,-0.078000,...,-0.008,-0.014,-0.019,-0.014,0.005,-0.037,-0.012,-0.011,0.006,0.028
17,-0.141,0.035000,-0.015000,0.023000,0.059000,-0.143000,-0.018000,-0.006000,-0.010000,0.018000,...,0.007,-0.028,-0.023,-0.024,-0.002,-0.054,-0.011,-0.016,0.007,0.039
18,-0.166,-0.019000,0.000000,-0.041000,-0.038000,-0.093000,0.029000,0.008000,0.003000,-0.017000,...,-0.012,0.005,0.022,0.016,0.023,0.016,-0.013,0.005,0.010,-0.009
19,-0.175,-0.036000,-0.022000,-0.058000,-0.061000,-0.043000,0.052000,0.022000,0.015000,-0.014000,...,-0.019,0.036,0.004,0.033,0.032,0.029,-0.014,0.009,0.023,-0.031

In [85]:
# This is the help I got from ChatGPT 4o to determine which rows were used to impute row 15. 
# Since n_neighbors=1 returned whatever row was closest, I had to make sure it was not just using the closest rows in my dataset. 

from sklearn.metrics.pairwise import nan_euclidean_distances
import numpy as np

# Assume x_df is your original dataframe (before imputation)
x_imputed = imputer.fit_transform(x_df_3)  # Imputed Data

# Compute distances to find nearest neighbors
distances = nan_euclidean_distances(x_df_3)
nearest_neighbors = np.argsort(distances, axis=1)[:, 1:4]  # Get top 3 nearest neighbors

# Show the 3 nearest rows used for row 15
print("Nearest neighbors for row 15:")
print(x_df.iloc[nearest_neighbors[15]])

Nearest neighbors for row 15:
     0      1      2      3      4      5      6      7      8      9     ...  \
17 -3.272 -0.168  0.113  0.064  0.057 -0.050  0.084  0.097  0.089 -0.078  ...
18 -0.141  0.035 -0.015  0.023  0.059 -0.143 -0.018 -0.006 -0.010  0.018  ...
26 -0.148  0.024 -0.015  0.008  0.033 -0.129 -0.010 -0.003 -0.008  0.013  ...

     5398   5399   5400   5401   5402   5403   5404   5405   5406   5407
17 -0.008 -0.014 -0.019 -0.014  0.005 -0.037 -0.012 -0.011  0.006  0.028
18  0.007 -0.028 -0.023 -0.024 -0.002 -0.054 -0.011 -0.016  0.007  0.039
26  0.002 -0.020 -0.018 -0.017  0.003 -0.042 -0.012 -0.012  0.009  0.030

[3 rows x 5408 columns]

In [86]:
y = df["result"]

In [62]:
# The library was referred from https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
# Received ChatGPT 4o's help when forming nested loop

#What to fix? 
# The dataset to be trained with needs to have X and Y combined to begin with, so let's start with df 
# Then we could do imputation 

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

# Extract features and target variable
X = x_df_3.copy()  # Imputed feature dataset
y = x_df_result  # Target column from df

# List of parameter values to try
weights_list = ["uniform", "distance"]
neighbors_list = [1, 3, 5, 9, 11, 15, 21]
dataset_types = ["unbalanced", "balanced"]

# To store results
results = []

# Loop over dataset types (unbalanced and balanced)
for dataset_type in dataset_types:
    if dataset_type == "unbalanced":
        X_current = X.copy()
        y_current = y.copy()
    else:
        # Create a balanced dataset using undersampling:
        balanced_df = df.copy()
        min_count = balanced_df["result"].value_counts().min()
        balanced_df = balanced_df.groupby("result", group_keys=False).apply(
            lambda grp: grp.sample(n=min_count, random_state=42)
        ).reset_index(drop=True)

        # Extract the balanced X and y
        X_current = balanced_df.drop(columns=["result"])
        y_current = balanced_df["result"]

    # Split the dataset into training and testing sets using a 70-30 split
    print(X_current.shape, y_current.shape)

    X_train, X_test, y_train, y_test = train_test_split(
        X_current, y_current, test_size=0.3, random_state=22222, stratify=y_current
    )

    # Loop over the weighting schemes and n_neighbors values
    for weight in weights_list:
        for n in neighbors_list:
            # Create the KNeighborsClassifier with the given parameters
            neigh = KNeighborsClassifier(n_neighbors=n, weights=weight)
            neigh.fit(X_train, y_train)

            # Evaluate the model
            train_score = neigh.score(X_train, y_train)
            test_score = neigh.score(X_test, y_test)

            # Store the results
            results.append({
                "dataset": dataset_type,
                "weight": weight,
                "n_neighbors": n,
                "train_score": train_score,
                "test_score": test_score
            })

# Convert results to a DataFrame
results_df = pd.DataFrame(results)
print(results_df)

(1895, 5408) (1900,)

ValueError: Found input variables with inconsistent numbers of samples: [1895, 1900]

### When Do I Normalize Data??

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

NameError: name 'X' is not defined

In [ ]:
clf.fit(X_train, y_train)

In [ ]:
y_pred = clf.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

### Scikit-Learn's kNN library explanation
##### https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html