In [2]:
import torch

In [3]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
NVIDIA GeForce RTX 3050 Ti Laptop GPU

In [4]:
!nvidia-smi

Thu Mar 20 21:53:01 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.124.04             Driver Version: 570.124.04     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   45C    P8              7W /   60W |      15MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            2456      G   /usr/bin/gnome-shell                      1MiB |
+-----------------------------------------------------------------------------------------+

In [5]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [6]:
# No truncating results
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns',None)

In [7]:
# Using Practice File for faster processing, swap it to original file for correct result. 
file_path = "/home/joong/orange/ece-5464/project_3/data/k8 _practicee.xlsx"

In [8]:
df = pd.read_excel(file_path, header= None)

In [9]:
df.shape

(1900, 5409)

In [10]:
# Renaming column referred from ChatGPT 4o
df.rename(columns={df.columns[-1]: "result"}, inplace=True)

In [11]:
# Check for "?" in the entire DataFrame
question_marks = df.map(lambda x: x == "?")

# Sum up how many "?" values are in each column
question_mark_count = question_marks.sum()

print("Number of '?' values per column:\n", question_mark_count)

Number of '?' values per column:
 0         32
1         32
2         32
3         32
4         32
5         32
6         32
7         32
8         32
9         32
10        32
11        32
12        32
13        32
14        32
15        32
16        32
17        32
18        32
19        32
20        32
21        32
22        32
23        32
24        32
25        32
26        32
27        32
28        32
29        32
30        32
31        32
32        32
33        32
34        32
35        32
36        32
37        32
38        32
39        32
40        32
41        32
42        32
43        32
44        32
45        32
46        32
47        32
48        32
49        32
50        32
51        32
52        32
53        32
54        32
55        32
56        32
57        32
58        32
59        32
60        32
61        32
62        32
63        32
64        32
65        32
66        32
67        32
68        32
69        32
70        32
71        32
72        32
73        32
74        32
75        32
76        32
77        32
78        32
79        32
80        32
81        32
82        32
83        32
84        32
85        32
86        32
87        32
88        32
89        32
90        32
91        32
92        32
93        32
94        32
95        32
96        32
97        32
98        32
99        32
100       32
101       32
102       32
103       32
104       32
105       32
106       32
107       32
108       32
109       32
110       32
111       32
112       32
113       32
114       32
115       32
116       32
117       32
118       32
119       32
120       32
121       32
122       32
123       32
124       32
125       32
126       32
127       32
128       32
129       32
130       32
131       32
132       32
133       32
134       32
135       32
136       32
137       32
138       32
139       32
140       32
141       32
142       32
143       32
144       32
145       32
146       32
147       32
148       32
149       32
150       32
151       32
152       32
153       32
154       32
155       32
156       32
157       32
158       32
159       32
160       32
161       32
162       32
163       32
164       32
165       32
166       32
167       32
168       32
169       32
170       32
171       32
172       32
173       32
174       32
175       32
176       32
177       32
178       32
179       32
180       32
181       32
182       32
183       32
184       32
185       32
186       32
187       32
188       32
189       32
190       32
191       32
192       32
193       32
194       32
195       32
196       32
197       32
198       32
199       32
200       32
201       32
202       32
203       32
204       32
205       32
206       32
207       32
208       32
209       32
210       32
211       32
212       32
213       32
214       32
215       32
216       32
217       32
218       32
219       32
220       32
221       32
222       32
223       32
224       32
225       32
226       32
227       32
228       32
229       32
230       32
231       32
232       32
233       32
234       32
235       32
236       32
237       32
238       32
239       32
240       32
241       32
242       32
243       32
244       32
245       32
246       32
247       32
248       32
249       32
250       32
251       32
252       32
253       32
254       32
255       32
256       32
257       32
258       32
259       32
260       32
261       32
262       32
263       32
264       32
265       32
266       32
267       32
268       32
269       32
270       32
271       32
272       32
273       32
274       32
275       32
276       32
277       32
278       32
279       32
280       32
281       32
282       32
283       32
284       32
285       32
286       32
287       32
288       32
289       32
290       32
291       32
292       32
293       32
294       32
295       32
296       32
297       32
298       32
299       32
300       32
301       32
302       32
303       32
304       32
305       32
306       32
307       32
308       32
309       32
310       32
311       32
312       32
313       32
314       32
315       32
316       32
317       32
318       32
319       32
320       32
321       32
322       32
323       32
324       32
325       32
326       32
327       32
328       32
329       32
330       32
331       32
332       32
333       32
334       32
335       32
336       32
337       32
338       32
339       32
340       32
341       32
342       32
343       32
344       32
345       32
346       32
347       32
348       32
349       32
350       32
351       32
352       32
353       32
354       32
355       32
356       32
357       32
358       32
359       32
360       32
361       32
362       32
363       32
364       32
365       32
366       32
367       32
368       32
369       32
370       32
371       32
372       32
373       32
374       32
375       32
376       32
377       32
378       32
379       32
380       32
381       32
382       32
383       32
384       32
385       32
386       32
387       32
388       32
389       32
390       32
391       32
392       32
393       32
394       32
395       32
396       32
397       32
398       32
399       32
400       32
401       32
402       32
403       32
404       32
405       32
406       32
407       32
408       32
409       32
410       32
411       32
412       32
413       32
414       32
415       32
416       32
417       32
418       32
419       32
420       32
421       32
422       32
423       32
424       32
425       32
426       32
427       32
428       32
429       32
430       32
431       32
432       32
433       32
434       32
435       32
436       32
437       32
438       32
439       32
440       32
441       32
442       32
443       32
444       32
445       32
446       32
447       32
448       32
449       32
450       32
451       32
452       32
453       32
454       32
455       32
456       32
457       32
458       32
459       32
460       32
461       32
462       32
463       32
464       32
465       32
466       32
467       32
468       32
469       32
470       32
471       32
472       32
473       32
474       32
475       32
476       32
477       32
478       32
479       32
480       32
481       32
482       32
483       32
484       32
485       32
486       32
487       32
488       32
489       32
490       32
491       32
492       32
493       32
494       32
495       32
496       32
497       32
498       32
499       32
500       32
501       32
502       32
503       32
504       32
505       32
506       32
507       32
508       32
509       32
510       32
511       32
512       32
513       32
514       32
515       32
516       32
517       32
518       32
519       32
520       32
521       32
522       32
523       32
524       32
525       32
526       32
527       32
528       32
529       32
530       32
531       32
532       32
533       32
534       32
535       32
536       32
537       32
538       32
539       32
540       32
541       32
542       32
543       32
544       32
545       32
546       32
547       32
548       32
549       32
550       32
551       32
552       32
553       32
554       32
555       32
556       32
557       32
558       32
559       32
560       32
561       32
562       32
563       32
564       32
565       32
566       32
567       32
568       32
569       32
570       32
571       32
572       32
573       32
574       32
575       32
576       32
577       32
578       32
579       32
580       32
581       32
582       32
583       32
584       32
585       32
586       32
587       32
588       32
589       32
590       32
591       32
592       32
593       32
594       32
595       32
596       32
597       32
598       32
599       32
600       32
601       32
602       32
603       32
604       32
605       32
606       32
607       32
608       32
609       32
610       32
611       32
612       32
613       32
614       32
615       32
616       32
617       32
618       32
619       32
620       32
621       32
622       32
623       32
624       32
625       32
626       32
627       32
628       32
629       32
630       32
631       32
632       32
633       32
634       32
635       32
636       32
637       32
638       32
639       32
640       32
641       32
642       32
643       32
644       32
645       32
646       32
647       32
648       32
649       32
650       32
651       32
652       32
653       32
654       32
655       32
656       32
657       32
658       32
659       32
660       32
661       32
662       32
663       32
664       32
665       32
666       32
667       32
668       32
669       32
670       32
671       32
672       32
673       32
674       32
675       32
676       32
677       32
678       32
679       32
680       32
681       32
682       32
683       32
684       32
685       32
686       32
687       32
688       32
689       32
690       32
691       32
692       32
693       32
694       32
695       32
696       32
697       32
698       32
699       32
700       32
701       32
702       32
703       32
704       32
705       32
706       32
707       32
708       32
709       32
710       32
711       32
712       32
713       32
714       32
715       32
716       32
717       32
718       32
719       32
720       32
721       32
722       32
723       32
724       32
725       32
726       32
727       32
728       32
729       32
730       32
731       32
732       32
733       32
734       32
735       32
736       32
737       32
738       32
739       32
740       32
741       32
742       32
743       32
744       32
745       32
746       32
747       32
748       32
749       32
750       32
751       32
752       32
753       32
754       32
755       32
756       32
757       32
758       32
759       32
760       32
761       32
762       32
763       32
764       32
765       32
766       32
767       32
768       32
769       32
770       32
771       32
772       32
773       32
774       32
775       32
776       32
777       32
778       32
779       32
780       32
781       32
782       32
783       32
784       32
785       32
786       32
787       32
788       32
789       32
790       32
791       32
792       32
793       32
794       32
795       32
796       32
797       32
798       32
799       32
800       32
801       32
802       32
803       32
804       32
805       32
806       32
807       32
808       32
809       32
810       32
811       32
812       32
813       32
814       32
815       32
816       32
817       32
818       32
819       32
820       32
821       32
822       32
823       32
824       32
825       32
826       32
827       32
828       32
829       32
830       32
831       32
832       32
833       32
834       32
835       32
836       32
837       32
838       32
839       32
840       32
841       32
842       32
843       32
844       32
845       32
846       32
847       32
848       32
849       32
850       32
851       32
852       32
853       32
854       32
855       32
856       32
857       32
858       32
859       32
860       32
861       32
862       32
863       32
864       32
865       32
866       32
867       32
868       32
869       32
870       32
871       32
872       32
873       32
874       32
875       32
876       32
877       32
878       32
879       32
880       32
881       32
882       32
883       32
884       32
885       32
886       32
887       32
888       32
889       32
890       32
891       32
892       32
893       32
894       32
895       32
896       32
897       32
898       32
899       32
900       32
901       32
902       32
903       32
904       32
905       32
906       32
907       32
908       32
909       32
910       32
911       32
912       32
913       32
914       32
915       32
916       32
917       32
918       32
919       32
920       32
921       32
922       32
923       32
924       32
925       32
926       32
927       32
928       32
929       32
930       32
931       32
932       32
933       32
934       32
935       32
936       32
937       32
938       32
939       32
940       32
941       32
942       32
943       32
944       32
945       32
946       32
947       32
948       32
949       32
950       32
951       32
952       32
953       32
954       32
955       32
956       32
957       32
958       32
959       32
960       32
961       32
962       32
963       32
964       32
965       32
966       32
967       32
968       32
969       32
970       32
971       32
972       32
973       32
974       32
975       32
976       32
977       32
978       32
979       32
980       32
981       32
982       32
983       32
984       32
985       32
986       32
987       32
988       32
989       32
990       32
991       32
992       32
993       32
994       32
995       32
996       32
997       32
998       32
999       32
1000      32
1001      32
1002      32
1003      32
1004      32
1005      32
1006      32
1007      32
1008      32
1009      32
1010      32
1011      32
1012      32
1013      32
1014      32
1015      32
1016      32
1017      32
1018      32
1019      32
1020      32
1021      32
1022      32
1023      32
1024      32
1025      32
1026      32
1027      32
1028      32
1029      32
1030      32
1031      32
1032      32
1033      32
1034      32
1035      32
1036      32
1037      32
1038      32
1039      32
1040      32
1041      32
1042      32
1043      32
1044      32
1045      32
1046      32
1047      32
1048      32
1049      32
1050      32
1051      32
1052      32
1053      32
1054      32
1055      32
1056      32
1057      32
1058      32
1059      32
1060      32
1061      32
1062      32
1063      32
1064      32
1065      32
1066      32
1067      32
1068      32
1069      32
1070      32
1071      32
1072      32
1073      32
1074      32
1075      32
1076      32
1077      32
1078      32
1079      32
1080      32
1081      32
1082      32
1083      32
1084      32
1085      32
1086      32
1087      32
1088      32
1089      32
1090      32
1091      32
1092      32
1093      32
1094      32
1095      32
1096      32
1097      32
1098      32
1099      32
1100      32
1101      32
1102      32
1103      32
1104      32
1105      32
1106      32
1107      32
1108      32
1109      32
1110      32
1111      32
1112      32
1113      32
1114      32
1115      32
1116      32
1117      32
1118      32
1119      32
1120      32
1121      32
1122      32
1123      32
1124      32
1125      32
1126      32
1127      32
1128      32
1129      32
1130      32
1131      32
1132      32
1133      32
1134      32
1135      32
1136      32
1137      32
1138      32
1139      32
1140      32
1141      32
1142      32
1143      32
1144      32
1145      32
1146      32
1147      32
1148      32
1149      32
1150      32
1151      32
1152      32
1153      32
1154      32
1155      32
1156      32
1157      32
1158      32
1159      32
1160      32
1161      32
1162      32
1163      32
1164      32
1165      32
1166      32
1167      32
1168      32
1169      32
1170      32
1171      32
1172      32
1173      32
1174      32
1175      32
1176      32
1177      32
1178      32
1179      32
1180      32
1181      32
1182      32
1183      32
1184      32
1185      32
1186      32
1187      32
1188      32
1189      32
1190      32
1191      32
1192      32
1193      32
1194      32
1195      32
1196      32
1197      32
1198      32
1199      32
1200      32
1201      32
1202      32
1203      32
1204      32
1205      32
1206      32
1207      32
1208      32
1209      32
1210      32
1211      32
1212      32
1213      32
1214      32
1215      32
1216      32
1217      32
1218      32
1219      32
1220      32
1221      32
1222      32
1223      32
1224      32
1225      32
1226      32
1227      32
1228      32
1229      32
1230      32
1231      32
1232      32
1233      32
1234      32
1235      32
1236      32
1237      32
1238      32
1239      32
1240      32
1241      32
1242      32
1243      32
1244      32
1245      32
1246      32
1247      32
1248      32
1249      32
1250      32
1251      32
1252      32
1253      32
1254      32
1255      32
1256      32
1257      32
1258      32
1259      32
1260      32
1261      32
1262      32
1263      32
1264      32
1265      32
1266      32
1267      32
1268      32
1269      32
1270      32
1271      32
1272      32
1273      32
1274      32
1275      32
1276      32
1277      32
1278      32
1279      32
1280      32
1281      32
1282      32
1283      32
1284      32
1285      32
1286      32
1287      32
1288      32
1289      32
1290      32
1291      32
1292      32
1293      32
1294      32
1295      32
1296      32
1297      32
1298      32
1299      32
1300      32
1301      32
1302      32
1303      32
1304      32
1305      32
1306      32
1307      32
1308      32
1309      32
1310      32
1311      32
1312      32
1313      32
1314      32
1315      32
1316      32
1317      32
1318      32
1319      32
1320      32
1321      32
1322      32
1323      32
1324      32
1325      32
1326      32
1327      32
1328      32
1329      32
1330      32
1331      32
1332      32
1333      32
1334      32
1335      32
1336      32
1337      32
1338      32
1339      32
1340      32
1341      32
1342      32
1343      32
1344      32
1345      32
1346      32
1347      32
1348      32
1349      32
1350      32
1351      32
1352      32
1353      32
1354      32
1355      32
1356      32
1357      32
1358      32
1359      32
1360      32
1361      32
1362      32
1363      32
1364      32
1365      32
1366      32
1367      32
1368      32
1369      32
1370      32
1371      32
1372      32
1373      32
1374      32
1375      32
1376      32
1377      32
1378      32
1379      32
1380      32
1381      32
1382      32
1383      32
1384      32
1385      32
1386      32
1387      32
1388      32
1389      32
1390      32
1391      32
1392      32
1393      32
1394      32
1395      32
1396      32
1397      32
1398      32
1399      32
1400      32
1401      32
1402      32
1403      32
1404      32
1405      32
1406      32
1407      32
1408      32
1409      32
1410      32
1411      32
1412      32
1413      32
1414      32
1415      32
1416      32
1417      32
1418      32
1419      32
1420      32
1421      32
1422      32
1423      32
1424      32
1425      32
1426      32
1427      32
1428      32
1429      32
1430      32
1431      32
1432      32
1433      32
1434      32
1435      32
1436      32
1437      32
1438      32
1439      32
1440      32
1441      32
1442      32
1443      32
1444      32
1445      32
1446      32
1447      32
1448      32
1449      32
1450      32
1451      32
1452      32
1453      32
1454      32
1455      32
1456      32
1457      32
1458      32
1459      32
1460      32
1461      32
1462      32
1463      32
1464      32
1465      32
1466      32
1467      32
1468      32
1469      32
1470      32
1471      32
1472      32
1473      32
1474      32
1475      32
1476      32
1477      32
1478      32
1479      32
1480      32
1481      32
1482      32
1483      32
1484      32
1485      32
1486      32
1487      32
1488      32
1489      32
1490      32
1491      32
1492      32
1493      32
1494      32
1495      32
1496      32
1497      32
1498      32
1499      32
1500      32
1501      32
1502      32
1503      32
1504      32
1505      32
1506      32
1507      32
1508      32
1509      32
1510      32
1511      32
1512      32
1513      32
1514      32
1515      32
1516      32
1517      32
1518      32
1519      32
1520      32
1521      32
1522      32
1523      32
1524      32
1525      32
1526      32
1527      32
1528      32
1529      32
1530      32
1531      32
1532      32
1533      32
1534      32

In [12]:
# how to drop rows with all "?"
# Referred from https://saturncloud.io/blog/how-to-drop-rows-with-all-zeros-in-pandas-dataframe/

In [13]:
df.head()

       0      1      2      3      4      5      6      7      8      9  \
0 -0.161 -0.014  0.002 -0.036 -0.033 -0.093  0.025  0.005      0 -0.015
1 -0.158 -0.002 -0.012 -0.025 -0.012 -0.106  0.013  0.005      0 -0.002
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.169 -0.025  -0.01 -0.041 -0.045 -0.069  0.038  0.014  0.008 -0.014
4 -0.183 -0.051 -0.023 -0.077 -0.092 -0.015  0.071  0.027   0.02 -0.019

      10     11     12     13     14     15     16     17     18     19  \
0  -0.03  -0.05 -0.031 -0.036 -0.093 -0.008  -0.03 -0.023 -0.036 -0.042
1 -0.007  -0.01 -0.009 -0.017 -0.024  0.002  0.003 -0.011 -0.013  -0.01
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.032 -0.043 -0.033 -0.046 -0.094 -0.017 -0.042 -0.022 -0.033 -0.039
4 -0.044 -0.097 -0.052 -0.079 -0.175  -0.04 -0.084  -0.03 -0.047 -0.058

      20     21     22     23     24     25     26     27     28     29  \
0 -0.038 -0.036 -0.088 -0.102 -0.021 -0.031 -0.053 -0.257 -0.114 -0.075
1 -0.019 -0.017 -0.023 -0.044 -0.004 -0.019 -0.033 -0.187 -0.074 -0.057
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.044  -0.04 -0.091 -0.132 -0.035 -0.036 -0.062 -0.258 -0.133 -0.097
4 -0.067 -0.063 -0.148 -0.228 -1.008 -0.058 -0.094 -0.315 -0.204 -0.156

      30     31     32     33     34     35     36     37     38        39  \
0 -0.037   0.08  0.027 -0.161  0.056 -0.004  0.002  0.003 -0.033 -0.056133
1 -0.044  0.044  0.006 -0.146  0.009 -0.017 -0.009 -0.008 -0.029 -0.010433
2      ?      ?      ?      ?      ?      ?      ?      ?      ?         ?
3  -0.07  0.069  0.014 -0.177  0.053 -0.006 -0.002 -0.005 -0.031 -0.070167
4 -0.122  0.081  0.007 -0.204  0.084  0.003      0 -0.008 -0.028   -0.1135

         40     41     42     43     44     45     46     47     48     49  \
0 -0.019444  0.016  0.004  0.038  0.028 -0.016 -0.027 -0.044 -0.055 -0.024
1  0.012889  0.023  0.022  0.026   0.06 -0.025  0.053 -0.053 -0.087 -0.029
2         ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.035333  0.006  -0.01  0.029 -0.013 -0.032  -0.03 -0.049 -0.084 -0.028
4 -0.114333 -0.002 -0.032  0.034 -0.073 -0.108 -0.066 -0.073 -0.166 -0.046

      50     51     52     53     54     55     56     57     58     59  \
0  0.016  -0.02 -0.019 -0.024  0.007 -0.046 -0.052  0.042 -0.059 -0.073
1 -0.075 -0.122 -0.363  -0.01  0.101  0.006 -0.104 -0.029  -0.24 -0.099
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.012 -0.051 -0.377  -0.05  0.008 -0.071 -0.073  0.019  -0.04 -0.076
4 -0.038 -0.125 -0.423 -0.118  -0.03 -0.184 -0.133 -0.037 -0.089 -0.187

      60     61     62     63     64     65     66     67     68     69  \
0  -0.02  0.016 -0.018 -0.023 -0.039 -0.268 -0.036  0.015 -0.003 -0.019
1  0.027   0.12  0.086  0.199 -0.185  -0.64 -0.066  0.059  0.017  0.053
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  -0.04 -0.014 -0.034 -0.017 -0.043  -0.27 -0.033      0 -0.011 -0.024
4 -0.149 -0.121  -0.12 -0.124 -0.098 -0.478 -0.068 -0.062 -0.053 -0.078

      70     71     72     73     74     75     76     77     78     79  \
0 -0.019 -0.053 -0.037 -0.002 -0.034 -0.031 -0.034 -0.025  0.018  0.008
1  0.084 -0.149 -0.047  0.049 -0.048 -0.012 -0.007 -0.003  0.071  0.048
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.026  -0.05 -0.035      0 -0.023 -0.023 -0.028 -0.026  0.015  0.015
4 -0.082 -0.121 -0.107 -0.046 -0.034  -0.04 -0.047 -0.057 -0.064  0.054

      80     81     82     83     84     85     86     87     88     89  \
0 -0.017 -0.042 -0.035 -0.065 -0.076  0.006 -0.024 -0.023 -0.048 -0.049
1 -0.045 -0.081 -0.029  0.093 -0.068 -0.048  0.006 -0.008 -0.012  0.006
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.007 -0.028 -0.023 -0.069 -0.071   0.01 -0.056 -0.051  -0.05 -0.065
4  -0.03 -0.052 -0.052 -0.184 -0.089 -0.111 -0.116 -0.087 -0.096 -0.139

      90     91     92     93     94     95     96     97     98     99  \
0 -0.049 -0.069 -0.026  0.049  0.049  0.025 -0.025  3.593  3.082  4.411
1 -0.007 -0.021  -0.01  0.036  0.024  0.014 -0.005    3.6  3.094  4.406
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.047 -0.062 -0.025   0.06  0.053   0.02 -0.031  3.591  3.075  4.405
4 -0.097 -0.103 -0.039  0.036  0.076  0.019 -0.055  3.589  3.056  4.398

     100    101    102    103    104    105       106       107       108  \
0  3.695  2.765  0.038  0.463  0.604  0.904 -0.144053     0.027  0.085904
1  3.696  2.776  0.027  0.412  0.609   0.91 -0.172632  0.024812  0.082942
2      ?      ?      ?      ?      ?      ?         ?         ?         ?
3   3.69  2.762  0.043   0.45  0.595  0.896 -0.158158   0.05025  0.146481
4  3.684  2.747 -0.963  0.444  0.574  0.872 -0.038211  0.045687    0.1125

     109    110    111    112    113    114    115    116    117    118  \
0 -0.044 -0.003  0.034 -0.021 -0.024  0.033 -0.014  0.023 -0.035 -0.058
1 -0.042  0.006  0.041 -0.026 -0.011  0.005 -0.003 -0.013 -0.017 -0.047
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.062  0.004  0.005 -0.032 -0.019  0.035 -0.013   0.01 -0.031 -0.049
4 -0.082 -0.005 -0.018 -0.075 -0.028  0.046 -0.021  0.005 -0.052 -0.061

     119    120    121    122    123    124    125    126    127    128  \
0 -0.063 -0.027  0.009 -0.076 -0.059 -0.035  0.009  0.082 -0.101   -0.1
1 -0.008 -0.007  0.015 -0.054 -0.044 -0.025  0.023  0.141 -0.051 -0.082
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.041 -0.025  0.005 -0.075 -0.058 -0.037  0.009  0.088 -0.096 -0.097
4 -0.061  -0.04 -0.007 -0.095  -0.07 -0.049  0.002  0.064 -0.121 -0.098

     129    130    131       132       133     134       135       136    137  \
0  0.053  0.197 -0.021  0.032727 -0.006955   0.102 -0.572514  0.009724  0.021
1  0.008  0.089 -0.038  0.035212 -0.005523  0.0475 -0.559914   0.00869  0.002
2      ?      ?      ?         ?         ?       ?         ?         ?      ?
3  0.043  0.185 -0.033  0.041485 -0.013295   0.096 -0.579429  0.007966   0.02
4  0.065  0.197 -0.039  0.057303 -0.025864    0.13   -0.5916  0.002759  0.014

     138    139    140    141    142    143    144    145    146    147  \
0 -0.274 -0.011  0.013 -0.025 -0.037 -0.005  0.016  0.023  0.026 -0.045
1 -0.291  0.011  0.001 -0.042  0.002  0.014  0.014  0.023  0.069 -0.022
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.051 -0.012  0.019  0.036 -0.048 -0.013   0.01  0.034  0.044  -0.04
4  0.027 -0.027  0.039  0.035 -0.086 -0.032  0.012  0.046  0.046 -0.075

     148    149    150    151    152    153    154    155    156    157  \
0  0.001  0.019  0.007  0.013 -0.034 -0.033  0.006  0.009  0.026  0.006
1  0.013  0.022 -0.011  0.011 -0.035  0.002  0.003 -0.004  0.001      0
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.003  0.006  0.001      0 -0.078 -0.005  0.011  0.007  0.006  0.008
4      0   0.01  0.027  0.009 -0.089  0.015  0.033  0.025  0.021  0.022

     158    159       160    161    162    163    164    165    166    167  \
0  0.045  0.052  0.073167 -0.044 -0.018 -0.066 -0.064  -0.05 -0.028 -0.036
1  0.011  0.006  0.027333 -0.041 -0.017 -0.055 -0.048 -0.042 -0.021 -0.034
2      ?      ?         ?      ?      ?      ?      ?      ?      ?      ?
3  0.004  0.021    0.0575 -0.044 -0.027 -0.064 -0.054 -0.047 -0.032 -0.034
4  0.014  0.037  0.034167 -2.503 -0.013 -0.076 -0.061 -0.056 -0.043 -0.044

        168       169       170       171    172    173    174    175    176  \
0  0.001857 -0.018933 -0.035123  0.017667 -0.084  0.171  0.004  0.004 -0.002
1 -0.005714 -0.017533 -0.014308  0.006667  0.027 -0.022  0.014  0.019  0.008
2         ?         ?         ?         ?      ?      ?      ?      ?      ?
3   -0.0128 -0.028133 -0.044062 -0.006833 -0.066 -0.043  0.009  0.001 -0.001
4 -0.025457  0.603633 -0.055246 -0.081333 -0.035  0.041  0.039 -0.014 -0.001

     177    178    179    180    181    182    183    184    185    186  \
0  0.108  0.169 -0.156  0.013  0.007  0.013  0.029  0.063 -0.183  0.023
1  0.013  0.076  -0.15  0.021  0.011  0.021  0.026  0.058 -0.188  0.013
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.009  0.058   -0.2  0.007  0.004  0.012  0.024  0.036 -0.202  0.031
4  0.002  0.053 -0.302 -0.008      0  0.005  0.022  0.003 -0.224   0.05

     187    188    189    190    191    192    193    194    195    196  \
0      0  0.018  0.037  0.051 -0.152 -0.127 -0.029 -0.009 -0.015  0.001
1 -0.003  0.025  0.042  0.036 -0.167 -0.122 -0.071  0.017 -0.005   0.02
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3      0  0.017   0.02   0.03 -0.161 -0.144  0.002 -0.009 -0.016  0.004
4  0.008  0.008 -0.025   0.01 -0.167 -0.182  0.109 -0.032 -0.008 -0.008

     197    198    199    200    201    202    203    204    205    206  \
0  0.018  0.027  0.021  0.025  0.105  0.028  -0.15  0.021  0.005 -0.016
1  0.026  0.028  0.019  0.027  0.011  0.014 -0.151  0.022   0.02 -0.007
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.018  0.028  0.019  0.022  0.094  0.011 -0.174  0.001  0.004 -0.027
4  0.018  0.035  0.021  0.017  0.088 -0.006 -0.209 -0.028 -0.004 -0.048

     207    208    209    210    211    212    213    214    215    216  \
0 -0.006  0.006 -0.003  0.017  0.029  0.185  0.022   0.04  0.001 -0.009
1  0.006  0.021  0.004  0.019  0.018  0.018  0.013  0.054  0.007  0.007
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.014  0.002 -0.011  0.011  0.022  0.159      0  0.025 -0.025 -0.023
4 -0.032  -0.01 -0.036 -0.002  0.016   0.13 -0.036 -0.007 -0.064 -0.057

     217    218    219    220    221    222    223    224    225    226  \
0  0.025  0.026 -0.001 -0.029 -0.037  0.015  0.299  0.037 -0.004 -0.009
1  0.023  0.014 -0.007 -0.023  -0.01   0.01  0.296  0.031 -0.003  0.056
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.017  0.015 -0.036 -0.057 -0.054  0.008  0.275  0.025 -0.009  -0.02
4      0  0.006 -0.099 -0.113 -0.093  0.016  0.199 -0.006 -0.011 -0.065

     227    228    229    230    231    232    233    234    235    236  \
0 -0.028 -0.042  -0.07 -0.061 -0.063 -0.019  0.031 -0.074  -0.11 -0.092
1 -0.035  0.009      0  0.005 -0.014 -0.016  0.024  0.033  0.016  0.006
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  -0.04 -0.039 -0.065 -0.065 -0.065 -0.076 -0.007 -0.072 -0.111 -0.096
4 -0.082 -0.052 -0.092 -0.103 -0.104  -0.12 -0.028 -0.104 -0.151 -0.147

     237    238    239    240    241    242    243    244    245    246  \
0 -0.088  0.017 -0.037 -0.039  -0.08 -0.078  0.013 -0.023  0.009  0.021
1  0.006 -0.022 -0.044 -0.013  0.012 -0.004  0.004 -0.011  0.008  0.004
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.087 -0.032  0.022  0.104 -0.085 -0.088 -0.013 -0.045  0.019  0.009
4 -0.131 -0.028 -0.012   0.06 -0.131 -0.143 -0.044 -0.088  0.046  0.033

     247    248    249    250    251    252    253    254    255    256  \
0  0.002 -0.043 -0.034 -0.051  0.086  0.008 -0.021 -0.015 -0.027 -0.064
1 -0.001 -0.017 -0.008  0.004   0.06 -0.011  -0.01 -0.001  0.009 -0.011
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.014 -0.049 -0.042 -0.048  0.143 -0.016  -0.03 -0.023 -0.027 -0.059
4 -0.028 -0.079  -0.08 -0.093   0.35 -0.026 -0.048 -0.048 -0.061 -0.109

     257    258    259    260    261    262    263    264    265    266  \
0 -0.085   0.07  0.005 -0.025 -0.015 -0.023 -0.044 -0.061 -0.092 -0.062
1  -0.02  0.006 -0.002 -0.025 -0.011 -0.009  -0.02      0 -0.032 -0.036
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.073  0.075 -0.001 -0.044 -0.022 -0.028 -0.045 -0.049 -0.083 -0.058
4 -0.125    0.1 -0.006 -0.074 -0.038  -0.05 -0.086 -0.089 -0.131 -0.079

     267    268    269    270    271    272    273    274    275    276  \
0  0.039 -0.024 -0.017 -0.053 -0.089  0.054  0.003 -0.011 -0.018  0.159
1  0.003 -0.005 -0.003 -0.031 -0.043  0.026  0.005 -0.011 -0.028 -0.028
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.036 -0.049  -0.02 -0.058 -0.099  0.122  0.006 -0.013 -0.028  0.146
4  0.053 -0.024 -0.044 -0.088 -0.152  0.162  0.011  -0.02  -0.04    0.1

     277    278    279    280    281    282    283    284    285    286  \
0 -0.055 -0.052 -0.013 -0.062 -0.397  0.023   0.01 -0.068   -0.1 -0.061
1 -0.023 -0.031 -0.047 -0.006  0.009 -0.029   0.03 -0.027 -0.046 -0.039
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.064 -0.059 -0.022 -0.087 -0.107  0.014 -0.003 -0.068 -0.096  -0.06
4 -0.084  -0.09 -0.051 -0.158 -0.181  0.018 -0.046 -0.101 -0.125 -0.073

     287    288    289    290    291    292    293    294    295    296  \
0 -0.479 -4.485 -0.058 -0.055 -0.171 -0.694 -4.222 -4.109 -0.072 -0.065
1 -0.469 -4.489 -0.022 -0.016 -0.147 -0.689 -4.238 -4.111 -0.084 -0.034
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.481 -4.485 -0.062 -0.054 -0.173 -0.696 -4.224 -4.107 -0.086 -0.083
4 -0.493 -4.484 -0.094 -0.082 -0.192 -0.701 -4.219 -4.106 -0.101 -0.131

     297    298    299    300    301    302    303    304    305       306  \
0  0.003 -0.004  0.011 -0.033 -3.665 -2.676  0.025  0.075 -2.556  0.023846
1  0.006 -0.002 -0.001 -0.057 -3.725 -2.851  0.014  0.023 -2.645  0.027423
2      ?      ?      ?      ?      ?      ?      ?      ?      ?         ?
3 -0.012 -0.017  0.001 -0.031 -3.643 -2.769  0.016  0.054  -2.58  0.011077
4 -0.038 -0.043 -0.011 -0.145 -3.998 -2.806  0.011  0.052 -2.557 -0.007346

        307     308      309    310    311    312    313    314    315    316  \
0    -0.103    0.01   0.0178  0.062 -0.051  -0.03 -0.011  0.012  0.005 -0.026
1 -0.054667  0.0135   0.0233  0.054 -0.071  -0.04 -0.011 -0.008 -0.014 -0.029
2         ?       ?        ?      ?      ?      ?      ?      ?      ?      ?
3 -0.099333  0.0095 -0.00882   0.06  -0.08  -0.05 -0.021 -0.006 -0.012  -0.03
4 -0.134333   0.004 -0.02124  0.067 -0.104 -0.096 -0.039 -0.017 -0.026 -0.041

     317    318    319    320    321    322    323    324    325    326  \
0 -0.014 -0.011  0.002  0.011  2.551 -0.047 -0.046 -0.008  0.005  0.006
1 -0.038 -0.024 -0.004  0.003 -0.002 -0.032 -0.046 -0.021  0.003  0.001
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.036 -0.027 -0.006  0.001 -0.002 -0.043 -0.061  -0.02  0.002 -0.001
4 -0.065 -0.049 -0.017 -0.011 -0.017 -0.051 -0.095 -0.038 -0.002  -0.01

     327    328    329    330    331    332    333    334    335    336  \
0  0.015  0.002 -0.076 -0.037 -0.016 -0.001 -0.003 -0.001 -0.001 -0.118
1  0.004  0.007 -0.042 -0.043 -0.021  0.001      0      0  0.003 -0.039
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3      0 -0.006 -0.074 -0.052 -0.028 -0.002 -0.008  -0.01 -0.012  -0.06
4 -0.019 -0.016 -0.099 -0.082  -0.05 -0.007 -0.017  -0.03 -0.035 -0.086

     337    338    339    340    341    342    343    344    345    346  \
0 -0.008 -0.003 -0.002  3.024  -0.03 -0.019 -0.015 -0.024 -0.442 -0.001
1  0.003  0.006  0.005  2.952  0.001  0.008  0.006 -0.004 -0.366  0.009
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.012      0 -0.004  3.031 -0.032 -0.016 -0.004 -0.027 -0.089 -0.019
4 -0.026      0 -0.012 -0.033 -0.036  -0.03  0.012 -0.056 -0.056 -0.046

     347    348    349    350    351    352    353    354    355    356  \
0 -0.198  0.235  0.199  0.074  -0.22  0.069 -0.016  0.102  0.028  0.028
1 -0.123  0.291  0.113  0.056 -0.385  0.051 -0.025  0.036  0.012  0.035
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.233  0.268   0.19  0.051 -0.232  0.063  -0.02  0.098  0.033   0.04
4 -0.319  0.387  0.207  0.025 -0.105 -0.109 -0.066 -0.005 -0.011  -0.01

     357    358    359    360    361    362    363    364    365    366  \
0  0.026  0.621   0.06   0.02 -0.008 -0.076 -0.035  0.021 -0.019  0.004
1  0.034  0.086      0 -0.005 -0.007  0.041  0.033  0.012  0.065  0.015
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.037  0.607  0.061  0.024 -0.005  -0.04 -0.032  0.008 -0.029 -0.004
4  0.001  0.534  0.042   0.03 -0.012  -0.03 -0.054 -0.011 -0.086  -0.04

     367    368    369    370    371    372    373    374    375    376  \
0 -0.007      0  0.005  1.038 -0.014 -0.011 -0.023 -0.041 -0.031  0.064
1 -0.016 -0.011 -0.004  0.992 -0.014 -0.022 -0.014 -0.009      0  0.017
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.011 -0.008  0.001  1.051 -0.023 -0.014 -0.023 -0.046 -0.031  0.051
4 -0.014 -0.013  0.021   1.18  -0.06 -0.017  -0.03 -0.088 -0.051  0.021

     377    378    379    380    381    382    383    384    385    386  \
0 -0.046 -0.049 -0.043 -0.033 -0.028 -0.036 -0.027 -0.049 -0.074 -0.049
1 -0.004 -0.019 -0.018 -0.012 -0.009  0.001 -0.012 -0.036 -0.024 -0.014
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.035 -0.047 -0.043  -0.03 -0.035 -0.047 -0.024 -0.048 -0.065 -0.048
4 -0.047 -0.074 -0.051 -0.039 -0.056 -0.097  0.007 -0.048 -0.109 -0.087

     387    388    389    390    391    392    393    394    395    396  \
0 -0.047 -0.025 -0.008 -0.014  -0.03 -0.052 -0.028  0.049 -0.102 -0.029
1 -0.015 -0.009      0 -0.033 -0.006 -0.016 -0.008  0.016 -0.029  0.009
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.047 -0.033 -0.019 -0.018  -0.03 -0.054 -0.034  0.029 -0.099 -0.027
4 -0.064  -0.05  -0.04  0.008 -0.087 -0.085 -0.057   0.04  -0.11 -0.057

     397    398    399    400    401    402    403    404    405    406  \
0  0.063 -0.041 -0.023 -0.006 -0.003 -0.014  0.024  0.012 -0.012 -0.018
1  0.041 -0.027 -0.002  0.011  0.014   0.01 -0.005  0.006 -0.002 -0.008
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.028 -0.055 -0.024  -0.01 -0.004 -0.014  0.038  0.017  0.004 -0.015
4 -0.008 -0.125 -0.161 -0.164  0.076  -0.11   0.06 -0.018  0.087 -0.055

     407    408    409    410    411    412    413    414    415    416  \
0  0.044  0.065  0.022 -0.002  0.059  0.042 -0.017  0.027  0.189  0.147
1   0.05  0.067  0.021 -0.003  0.056  0.043 -0.017  0.005  0.183   0.04
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.058  0.085  0.033  0.005  0.065  0.046 -0.024  0.012  0.195   0.15
4  0.038  0.092  0.075  0.003  0.064  0.054 -0.187 -0.304  0.219  0.157

     417    418    419    420    421    422    423    424    425    426  \
0  0.021  0.008 -0.004  0.621  0.046 -0.001 -0.027 -0.012 -0.015  0.042
1  0.014  0.001  -0.01  0.609  0.004 -0.018 -0.026 -0.012 -0.008  0.015
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.022  0.008 -0.019  0.626  0.046 -0.004  -0.03 -0.016 -0.014  0.024
4  0.019  0.011 -0.185  -0.34  0.049 -0.022 -0.056 -0.052 -0.034 -0.054

     427    428    429    430    431    432    433    434    435    436  \
0  0.063 -0.039 -0.151  -0.13 -0.127 -0.017  -0.05 -0.007 -0.079 -0.423
1  0.054 -0.031 -0.148 -0.128 -0.125 -0.004 -0.043 -0.021 -0.071 -0.414
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3  0.045 -0.037 -0.148 -0.135 -0.132 -0.018 -0.047 -0.012 -0.077 -0.422
4 -0.301 -0.024  0.005 -0.045 -0.061 -0.069 -0.019 -0.013 -0.026 -0.031

     437    438    439    440    441    442    443    444    445    446  \
0 -0.238 -0.008  -0.05  0.012 -0.084 -0.023 -0.007 -0.196  0.008 -0.017
1 -0.227  0.003  -0.04  0.024 -0.066 -0.009  0.015 -0.182  0.018 -0.009
2      ?      ?      ?      ?      ?      ?      ?      ?      ?      ?
3 -0.244 -0.014 -0.051  0.011 -0.084 -0.026 -0.007 -0.194  0.007 -0.021
4 -0.054 -0.069 -0.113 -0.042 -0.061 -0.052 -0.047 -0.197  -0.04 -0.052

     447       448    449    450    451    452    453    454    455    456  \
0 -0.018  0.013176  1.221  0.048  0.134 -0.015  0.028 -0.006 -0.051  0.034

In [14]:
# Drop rows where column 4826 has a "?"
df = df[df[4826] != "?"]

In [15]:
df.head()

       0      1      2      3      4      5      6      7      8      9  \
0 -0.161 -0.014  0.002 -0.036 -0.033 -0.093  0.025  0.005      0 -0.015
1 -0.158 -0.002 -0.012 -0.025 -0.012 -0.106  0.013  0.005      0 -0.002
3 -0.169 -0.025  -0.01 -0.041 -0.045 -0.069  0.038  0.014  0.008 -0.014
4 -0.183 -0.051 -0.023 -0.077 -0.092 -0.015  0.071  0.027   0.02 -0.019
5 -0.154  0.005 -0.011 -0.013 -0.002 -0.115  0.005  0.002 -0.003  0.002

      10     11     12     13     14     15     16     17     18     19  \
0  -0.03  -0.05 -0.031 -0.036 -0.093 -0.008  -0.03 -0.023 -0.036 -0.042
1 -0.007  -0.01 -0.009 -0.017 -0.024  0.002  0.003 -0.011 -0.013  -0.01
3 -0.032 -0.043 -0.033 -0.046 -0.094 -0.017 -0.042 -0.022 -0.033 -0.039
4 -0.044 -0.097 -0.052 -0.079 -0.175  -0.04 -0.084  -0.03 -0.047 -0.058
5  0.006 -0.002 -0.004 -0.009 -0.011  0.006  0.015 -0.008 -0.009 -0.004

      20     21     22     23     24     25     26     27     28     29  \
0 -0.038 -0.036 -0.088 -0.102 -0.021 -0.031 -0.053 -0.257 -0.114 -0.075
1 -0.019 -0.017 -0.023 -0.044 -0.004 -0.019 -0.033 -0.187 -0.074 -0.057
3 -0.044  -0.04 -0.091 -0.132 -0.035 -0.036 -0.062 -0.258 -0.133 -0.097
4 -0.067 -0.063 -0.148 -0.228 -1.008 -0.058 -0.094 -0.315 -0.204 -0.156
5  -0.01 -0.011 -0.007 -0.016  0.005 -0.011 -0.022 -0.161 -0.058 -0.043

      30     31     32     33     34     35     36     37     38        39  \
0 -0.037   0.08  0.027 -0.161  0.056 -0.004  0.002  0.003 -0.033 -0.056133
1 -0.044  0.044  0.006 -0.146  0.009 -0.017 -0.009 -0.008 -0.029 -0.010433
3  -0.07  0.069  0.014 -0.177  0.053 -0.006 -0.002 -0.005 -0.031 -0.070167
4 -0.122  0.081  0.007 -0.204  0.084  0.003      0 -0.008 -0.028   -0.1135
5  -0.03  0.041  0.008 -0.133      0  -0.02 -0.012  -0.01 -0.029  0.000033

         40     41     42     43     44     45     46     47     48     49  \
0 -0.019444  0.016  0.004  0.038  0.028 -0.016 -0.027 -0.044 -0.055 -0.024
1  0.012889  0.023  0.022  0.026   0.06 -0.025  0.053 -0.053 -0.087 -0.029
3 -0.035333  0.006  -0.01  0.029 -0.013 -0.032  -0.03 -0.049 -0.084 -0.028
4 -0.114333 -0.002 -0.032  0.034 -0.073 -0.108 -0.066 -0.073 -0.166 -0.046
5  0.008278  0.018   0.01  0.043   0.05 -0.003 -0.011 -0.025 -0.014 -0.009

      50     51     52     53     54     55     56     57     58     59  \
0  0.016  -0.02 -0.019 -0.024  0.007 -0.046 -0.052  0.042 -0.059 -0.073
1 -0.075 -0.122 -0.363  -0.01  0.101  0.006 -0.104 -0.029  -0.24 -0.099
3 -0.012 -0.051 -0.377  -0.05  0.008 -0.071 -0.073  0.019  -0.04 -0.076
4 -0.038 -0.125 -0.423 -0.118  -0.03 -0.184 -0.133 -0.037 -0.089 -0.187
5  0.008 -0.006 -0.025 -0.019 -0.006 -0.027  -0.03  0.025  -0.11 -0.114

      60     61     62     63     64     65     66     67     68     69  \
0  -0.02  0.016 -0.018 -0.023 -0.039 -0.268 -0.036  0.015 -0.003 -0.019
1  0.027   0.12  0.086  0.199 -0.185  -0.64 -0.066  0.059  0.017  0.053
3  -0.04 -0.014 -0.034 -0.017 -0.043  -0.27 -0.033      0 -0.011 -0.024
4 -0.149 -0.121  -0.12 -0.124 -0.098 -0.478 -0.068 -0.062 -0.053 -0.078
5 -0.022  0.002 -0.021  0.017 -0.051 -0.444 -0.062  0.015 -0.027 -0.032

      70     71     72     73     74     75     76     77     78     79  \
0 -0.019 -0.053 -0.037 -0.002 -0.034 -0.031 -0.034 -0.025  0.018  0.008
1  0.084 -0.149 -0.047  0.049 -0.048 -0.012 -0.007 -0.003  0.071  0.048
3 -0.026  -0.05 -0.035      0 -0.023 -0.023 -0.028 -0.026  0.015  0.015
4 -0.082 -0.121 -0.107 -0.046 -0.034  -0.04 -0.047 -0.057 -0.064  0.054
5  -0.03 -0.078 -0.059 -0.007 -0.064 -0.049  -0.04 -0.026  0.005 -0.009

      80     81     82     83     84     85     86     87     88     89  \
0 -0.017 -0.042 -0.035 -0.065 -0.076  0.006 -0.024 -0.023 -0.048 -0.049
1 -0.045 -0.081 -0.029  0.093 -0.068 -0.048  0.006 -0.008 -0.012  0.006
3 -0.007 -0.028 -0.023 -0.069 -0.071   0.01 -0.056 -0.051  -0.05 -0.065
4  -0.03 -0.052 -0.052 -0.184 -0.089 -0.111 -0.116 -0.087 -0.096 -0.139
5 -0.031 -0.088 -0.056  -0.07 -0.081  -0.09  0.012 -0.011  0.003  0.028

      90     91     92     93     94     95     96     97     98     99  \
0 -0.049 -0.069 -0.026  0.049  0.049  0.025 -0.025  3.593  3.082  4.411
1 -0.007 -0.021  -0.01  0.036  0.024  0.014 -0.005    3.6  3.094  4.406
3 -0.047 -0.062 -0.025   0.06  0.053   0.02 -0.031  3.591  3.075  4.405
4 -0.097 -0.103 -0.039  0.036  0.076  0.019 -0.055  3.589  3.056  4.398
5  0.016 -0.008  0.004  0.071  0.046  0.036  0.018  0.043   2.91  0.005

     100    101    102    103    104    105       106       107       108  \
0  3.695  2.765  0.038  0.463  0.604  0.904 -0.144053     0.027  0.085904
1  3.696  2.776  0.027  0.412  0.609   0.91 -0.172632  0.024812  0.082942
3   3.69  2.762  0.043   0.45  0.595  0.896 -0.158158   0.05025  0.146481
4  3.684  2.747 -0.963  0.444  0.574  0.872 -0.038211  0.045687    0.1125
5  3.103  2.495 -2.852 -2.116 -1.979  0.407 -0.178263   0.02425  0.022962

     109    110    111    112    113    114    115    116    117    118  \
0 -0.044 -0.003  0.034 -0.021 -0.024  0.033 -0.014  0.023 -0.035 -0.058
1 -0.042  0.006  0.041 -0.026 -0.011  0.005 -0.003 -0.013 -0.017 -0.047
3 -0.062  0.004  0.005 -0.032 -0.019  0.035 -0.013   0.01 -0.031 -0.049
4 -0.082 -0.005 -0.018 -0.075 -0.028  0.046 -0.021  0.005 -0.052 -0.061
5 -0.037   0.01  0.037 -0.029 -0.007   0.01  0.002 -0.014 -0.015  -0.04

     119    120    121    122    123    124    125    126    127    128  \
0 -0.063 -0.027  0.009 -0.076 -0.059 -0.035  0.009  0.082 -0.101   -0.1
1 -0.008 -0.007  0.015 -0.054 -0.044 -0.025  0.023  0.141 -0.051 -0.082
3 -0.041 -0.025  0.005 -0.075 -0.058 -0.037  0.009  0.088 -0.096 -0.097
4 -0.061  -0.04 -0.007 -0.095  -0.07 -0.049  0.002  0.064 -0.121 -0.098
5  0.001 -0.002  0.018 -0.044 -0.038  -0.02  0.025  0.063 -0.041 -0.078

     129    130    131       132       133     134       135       136    137  \
0  0.053  0.197 -0.021  0.032727 -0.006955   0.102 -0.572514  0.009724  0.021
1  0.008  0.089 -0.038  0.035212 -0.005523  0.0475 -0.559914   0.00869  0.002
3  0.043  0.185 -0.033  0.041485 -0.013295   0.096 -0.579429  0.007966   0.02
4  0.065  0.197 -0.039  0.057303 -0.025864    0.13   -0.5916  0.002759  0.014
5  0.001  0.071 -0.037  0.031818   -0.0025   0.039 -0.557514  0.010241  0.024

     138    139    140    141    142    143    144    145    146    147  \
0 -0.274 -0.011  0.013 -0.025 -0.037 -0.005  0.016  0.023  0.026 -0.045
1 -0.291  0.011  0.001 -0.042  0.002  0.014  0.014  0.023  0.069 -0.022
3  0.051 -0.012  0.019  0.036 -0.048 -0.013   0.01  0.034  0.044  -0.04
4  0.027 -0.027  0.039  0.035 -0.086 -0.032  0.012  0.046  0.046 -0.075
5   0.07      0  0.002  0.036 -0.005 -0.013  0.002   0.02  0.052 -0.005

     148    149    150    151    152    153    154    155    156    157  \
0  0.001  0.019  0.007  0.013 -0.034 -0.033  0.006  0.009  0.026  0.006
1  0.013  0.022 -0.011  0.011 -0.035  0.002  0.003 -0.004  0.001      0
3 -0.003  0.006  0.001      0 -0.078 -0.005  0.011  0.007  0.006  0.008
4      0   0.01  0.027  0.009 -0.089  0.015  0.033  0.025  0.021  0.022
5 -0.007 -0.007 -0.034 -0.016 -0.062  0.009 -0.014  -0.02 -0.024  0.001

     158    159       160    161    162    163    164    165    166    167  \
0  0.045  0.052  0.073167 -0.044 -0.018 -0.066 -0.064  -0.05 -0.028 -0.036
1  0.011  0.006  0.027333 -0.041 -0.017 -0.055 -0.048 -0.042 -0.021 -0.034
3  0.004  0.021    0.0575 -0.044 -0.027 -0.064 -0.054 -0.047 -0.032 -0.034
4  0.014  0.037  0.034167 -2.503 -0.013 -0.076 -0.061 -0.056 -0.043 -0.044
5 -0.015 -0.009    0.0375 -0.044 -0.012 -0.057 -0.054 -0.038 -0.015 -0.023

        168       169       170       171    172    173    174    175    176  \
0  0.001857 -0.018933 -0.035123  0.017667 -0.084  0.171  0.004  0.004 -0.002
1 -0.005714 -0.017533 -0.014308  0.006667  0.027 -0.022  0.014  0.019  0.008
3   -0.0128 -0.028133 -0.044062 -0.006833 -0.066 -0.043  0.009  0.001 -0.001
4 -0.025457  0.603633 -0.055246 -0.081333 -0.035  0.041  0.039 -0.014 -0.001
5 -0.000771 -0.015167 -0.007277   -0.0085 -0.021  0.235  0.013  0.026   0.01

     177    178    179    180    181    182    183    184    185    186  \
0  0.108  0.169 -0.156  0.013  0.007  0.013  0.029  0.063 -0.183  0.023
1  0.013  0.076  -0.15  0.021  0.011  0.021  0.026  0.058 -0.188  0.013
3  0.009  0.058   -0.2  0.007  0.004  0.012  0.024  0.036 -0.202  0.031
4  0.002  0.053 -0.302 -0.008      0  0.005  0.022  0.003 -0.224   0.05
5  0.117  0.164 -0.138  0.027  0.014  0.023  0.028  0.068 -0.183   0.01

     187    188    189    190    191    192    193    194    195    196  \
0      0  0.018  0.037  0.051 -0.152 -0.127 -0.029 -0.009 -0.015  0.001
1 -0.003  0.025  0.042  0.036 -0.167 -0.122 -0.071  0.017 -0.005   0.02
3      0  0.017   0.02   0.03 -0.161 -0.144  0.002 -0.009 -0.016  0.004
4  0.008  0.008 -0.025   0.01 -0.167 -0.182  0.109 -0.032 -0.008 -0.008
5 -0.004  0.027  0.044  0.041 -0.166 -0.107 -0.095  0.024 -0.001  0.021

     197    198    199    200    201    202    203    204    205    206  \
0  0.018  0.027  0.021  0.025  0.105  0.028  -0.15  0.021  0.005 -0.016
1  0.026  0.028  0.019  0.027  0.011  0.014 -0.151  0.022   0.02 -0.007
3  0.018  0.028  0.019  0.022  0.094  0.011 -0.174  0.001  0.004 -0.027
4  0.018  0.035  0.021  0.017  0.088 -0.006 -0.209 -0.028 -0.004 -0.048
5  0.022  0.023  0.018  0.029  0.011  0.019 -0.138  0.033  0.024      0

     207    208    209    210    211    212    213    214    215    216  \
0 -0.006  0.006 -0.003  0.017  0.029  0.185  0.022   0.04  0.001 -0.009
1  0.006  0.021  0.004  0.019  0.018  0.018  0.013  0.054  0.007  0.007
3 -0.014  0.002 -0.011  0.011  0.022  0.159      0  0.025 -0.025 -0.023
4 -0.032  -0.01 -0.036 -0.002  0.016   0.13 -0.036 -0.007 -0.064 -0.057
5  0.011   0.02  0.014  0.021   0.02  0.019  0.021  0.067  0.022  0.017

     217    218    219    220    221    222    223    224    225    226  \
0  0.025  0.026 -0.001 -0.029 -0.037  0.015  0.299  0.037 -0.004 -0.009
1  0.023  0.014 -0.007 -0.023  -0.01   0.01  0.296  0.031 -0.003  0.056
3  0.017  0.015 -0.036 -0.057 -0.054  0.008  0.275  0.025 -0.009  -0.02
4      0  0.006 -0.099 -0.113 -0.093  0.016  0.199 -0.006 -0.011 -0.065
5  0.027  0.015  0.005 -0.004  0.006  0.011   0.31  0.041  0.001  0.027

     227    228    229    230    231    232    233    234    235    236  \
0 -0.028 -0.042  -0.07 -0.061 -0.063 -0.019  0.031 -0.074  -0.11 -0.092
1 -0.035  0.009      0  0.005 -0.014 -0.016  0.024  0.033  0.016  0.006
3  -0.04 -0.039 -0.065 -0.065 -0.065 -0.076 -0.007 -0.072 -0.111 -0.096
4 -0.082 -0.052 -0.092 -0.103 -0.104  -0.12 -0.028 -0.104 -0.151 -0.147
5 -0.002 -0.033 -0.048  -0.02 -0.026 -0.029   0.01 -0.027 -0.048 -0.019

     237    238    239    240    241    242    243    244    245    246  \
0 -0.088  0.017 -0.037 -0.039  -0.08 -0.078  0.013 -0.023  0.009  0.021
1  0.006 -0.022 -0.044 -0.013  0.012 -0.004  0.004 -0.011  0.008  0.004
3 -0.087 -0.032  0.022  0.104 -0.085 -0.088 -0.013 -0.045  0.019  0.009
4 -0.131 -0.028 -0.012   0.06 -0.131 -0.143 -0.044 -0.088  0.046  0.033
5 -0.015 -0.045 -0.057 -0.002 -0.004  0.025  0.011 -0.003 -0.006 -0.012

     247    248    249    250    251    252    253    254    255    256  \
0  0.002 -0.043 -0.034 -0.051  0.086  0.008 -0.021 -0.015 -0.027 -0.064
1 -0.001 -0.017 -0.008  0.004   0.06 -0.011  -0.01 -0.001  0.009 -0.011
3 -0.014 -0.049 -0.042 -0.048  0.143 -0.016  -0.03 -0.023 -0.027 -0.059
4 -0.028 -0.079  -0.08 -0.093   0.35 -0.026 -0.048 -0.048 -0.061 -0.109
5 -0.003 -0.002  0.005  0.016  0.002 -0.029 -0.009  0.003  0.019  0.008

     257    258    259    260    261    262    263    264    265    266  \
0 -0.085   0.07  0.005 -0.025 -0.015 -0.023 -0.044 -0.061 -0.092 -0.062
1  -0.02  0.006 -0.002 -0.025 -0.011 -0.009  -0.02      0 -0.032 -0.036
3 -0.073  0.075 -0.001 -0.044 -0.022 -0.028 -0.045 -0.049 -0.083 -0.058
4 -0.125    0.1 -0.006 -0.074 -0.038  -0.05 -0.086 -0.089 -0.131 -0.079
5  0.004  0.002  0.002 -0.024 -0.008 -0.004 -0.006  0.018 -0.013 -0.034

     267    268    269    270    271    272    273    274    275    276  \
0  0.039 -0.024 -0.017 -0.053 -0.089  0.054  0.003 -0.011 -0.018  0.159
1  0.003 -0.005 -0.003 -0.031 -0.043  0.026  0.005 -0.011 -0.028 -0.028
3  0.036 -0.049  -0.02 -0.058 -0.099  0.122  0.006 -0.013 -0.028  0.146
4  0.053 -0.024 -0.044 -0.088 -0.152  0.162  0.011  -0.02  -0.04    0.1
5  0.019  0.003 -0.004  -0.02 -0.017  0.019  0.026  0.001 -0.004   0.18

     277    278    279    280    281    282    283    284    285    286  \
0 -0.055 -0.052 -0.013 -0.062 -0.397  0.023   0.01 -0.068   -0.1 -0.061
1 -0.023 -0.031 -0.047 -0.006  0.009 -0.029   0.03 -0.027 -0.046 -0.039
3 -0.064 -0.059 -0.022 -0.087 -0.107  0.014 -0.003 -0.068 -0.096  -0.06
4 -0.084  -0.09 -0.051 -0.158 -0.181  0.018 -0.046 -0.101 -0.125 -0.073
5 -0.052 -0.036 -0.017 -0.012 -0.018  -0.03  0.046  -0.02 -0.042 -0.039

     287    288    289    290    291    292    293    294    295    296  \
0 -0.479 -4.485 -0.058 -0.055 -0.171 -0.694 -4.222 -4.109 -0.072 -0.065
1 -0.469 -4.489 -0.022 -0.016 -0.147 -0.689 -4.238 -4.111 -0.084 -0.034
3 -0.481 -4.485 -0.062 -0.054 -0.173 -0.696 -4.224 -4.107 -0.086 -0.083
4 -0.493 -4.484 -0.094 -0.082 -0.192 -0.701 -4.219 -4.106 -0.101 -0.131
5 -0.468  -4.49 -0.011 -0.013 -0.143 -0.688 -4.239  -4.11 -0.093 -0.013

     297    298    299    300    301    302    303    304    305       306  \
0  0.003 -0.004  0.011 -0.033 -3.665 -2.676  0.025  0.075 -2.556  0.023846
1  0.006 -0.002 -0.001 -0.057 -3.725 -2.851  0.014  0.023 -2.645  0.027423
3 -0.012 -0.017  0.001 -0.031 -3.643 -2.769  0.016  0.054  -2.58  0.011077
4 -0.038 -0.043 -0.011 -0.145 -3.998 -2.806  0.011  0.052 -2.557 -0.007346
5  0.011  0.004  0.002  -0.06 -3.741 -2.841  0.018  0.022 -2.649     0.035

        307     308      309    310    311    312    313    314    315    316  \
0    -0.103    0.01   0.0178  0.062 -0.051  -0.03 -0.011  0.012  0.005 -0.026
1 -0.054667  0.0135   0.0233  0.054 -0.071  -0.04 -0.011 -0.008 -0.014 -0.029
3 -0.099333  0.0095 -0.00882   0.06  -0.08  -0.05 -0.021 -0.006 -0.012  -0.03
4 -0.134333   0.004 -0.02124  0.067 -0.104 -0.096 -0.039 -0.017 -0.026 -0.041
5 -0.057333   0.012  0.03686  0.051 -0.047 -0.027 -0.005 -0.004 -0.013 -0.022

     317    318    319    320    321    322    323    324    325    326  \
0 -0.014 -0.011  0.002  0.011  2.551 -0.047 -0.046 -0.008  0.005  0.006
1 -0.038 -0.024 -0.004  0.003 -0.002 -0.032 -0.046 -0.021  0.003  0.001
3 -0.036 -0.027 -0.006  0.001 -0.002 -0.043 -0.061  -0.02  0.002 -0.001
4 -0.065 -0.049 -0.017 -0.011 -0.017 -0.051 -0.095 -0.038 -0.002  -0.01
5 -0.027 -0.015      0  0.004      0 -0.025 -0.032 -0.014  0.005  0.005

     327    328    329    330    331    332    333    334    335    336  \
0  0.015  0.002 -0.076 -0.037 -0.016 -0.001 -0.003 -0.001 -0.001 -0.118
1  0.004  0.007 -0.042 -0.043 -0.021  0.001      0      0  0.003 -0.039
3      0 -0.006 -0.074 -0.052 -0.028 -0.002 -0.008  -0.01 -0.012  -0.06
4 -0.019 -0.016 -0.099 -0.082  -0.05 -0.007 -0.017  -0.03 -0.035 -0.086
5  0.008  0.013 -0.031 -0.029 -0.011  0.004  0.004  0.005  0.014 -0.027

     337    338    339    340    341    342    343    344    345    346  \
0 -0.008 -0.003 -0.002  3.024  -0.03 -0.019 -0.015 -0.024 -0.442 -0.001
1  0.003  0.006  0.005  2.952  0.001  0.008  0.006 -0.004 -0.366  0.009
3 -0.012      0 -0.004  3.031 -0.032 -0.016 -0.004 -0.027 -0.089 -0.019
4 -0.026      0 -0.012 -0.033 -0.036  -0.03  0.012 -0.056 -0.056 -0.046
5  0.006  0.007  0.009  2.974  0.007  0.019  0.009  0.008 -0.362  0.017

     347    348    349    350    351    352    353    354    355    356  \
0 -0.198  0.235  0.199  0.074  -0.22  0.069 -0.016  0.102  0.028  0.028
1 -0.123  0.291  0.113  0.056 -0.385  0.051 -0.025  0.036  0.012  0.035
3 -0.233  0.268   0.19  0.051 -0.232  0.063  -0.02  0.098  0.033   0.04
4 -0.319  0.387  0.207  0.025 -0.105 -0.109 -0.066 -0.005 -0.011  -0.01
5 -0.008   0.27  0.115  0.068 -0.024 -0.171 -0.006  0.109 -0.007  0.064

     357    358    359    360    361    362    363    364    365    366  \
0  0.026  0.621   0.06   0.02 -0.008 -0.076 -0.035  0.021 -0.019  0.004
1  0.034  0.086      0 -0.005 -0.007  0.041  0.033  0.012  0.065  0.015
3  0.037  0.607  0.061  0.024 -0.005  -0.04 -0.032  0.008 -0.029 -0.004
4  0.001  0.534  0.042   0.03 -0.012  -0.03 -0.054 -0.011 -0.086  -0.04
5  0.033  0.609  0.063   0.02  0.013  0.069  0.029  0.011 -0.024 -0.001

     367    368    369    370    371    372    373    374    375    376  \
0 -0.007      0  0.005  1.038 -0.014 -0.011 -0.023 -0.041 -0.031  0.064
1 -0.016 -0.011 -0.004  0.992 -0.014 -0.022 -0.014 -0.009      0  0.017
3 -0.011 -0.008  0.001  1.051 -0.023 -0.014 -0.023 -0.046 -0.031  0.051
4 -0.014 -0.013  0.021   1.18  -0.06 -0.017  -0.03 -0.088 -0.051  0.021
5 -0.001 -0.004  0.011  0.949 -0.012  -0.01  0.002 -0.009  0.001 -0.024

     377    378    379    380    381    382    383    384    385    386  \
0 -0.046 -0.049 -0.043 -0.033 -0.028 -0.036 -0.027 -0.049 -0.074 -0.049
1 -0.004 -0.019 -0.018 -0.012 -0.009  0.001 -0.012 -0.036 -0.024 -0.014
3 -0.035 -0.047 -0.043  -0.03 -0.035 -0.047 -0.024 -0.048 -0.065 -0.048
4 -0.047 -0.074 -0.051 -0.039 -0.056 -0.097  0.007 -0.048 -0.109 -0.087
5 -0.025 -0.014 -0.001 -0.003 -0.006 -0.009 -0.011 -0.038 -0.025 -0.007

     387    388    389    390    391    392    393    394    395    396  \
0 -0.047 -0.025 -0.008 -0.014  -0.03 -0.052 -0.028  0.049 -0.102 -0.029
1 -0.015 -0.009      0 -0.033 -0.006 -0.016 -0.008  0.016 -0.029  0.009
3 -0.047 -0.033 -0.019 -0.018  -0.03 -0.054 -0.034  0.029 -0.099 -0.027
4 -0.064  -0.05  -0.04  0.008 -0.087 -0.085 -0.057   0.04  -0.11 -0.057
5 -0.002 -0.002 -0.009 -0.036 -0.012 -0.011 -0.008   0.02  0.007  0.006

     397    398    399    400    401    402    403    404    405    406  \
0  0.063 -0.041 -0.023 -0.006 -0.003 -0.014  0.024  0.012 -0.012 -0.018
1  0.041 -0.027 -0.002  0.011  0.014   0.01 -0.005  0.006 -0.002 -0.008
3  0.028 -0.055 -0.024  -0.01 -0.004 -0.014  0.038  0.017  0.004 -0.015
4 -0.008 -0.125 -0.161 -0.164  0.076  -0.11   0.06 -0.018  0.087 -0.055
5  0.026 -0.051 -0.079  -0.08 -0.042 -0.082  0.116 -0.008  0.126 -0.035

     407    408    409    410    411    412    413    414    415    416  \
0  0.044  0.065  0.022 -0.002  0.059  0.042 -0.017  0.027  0.189  0.147
1   0.05  0.067  0.021 -0.003  0.056  0.043 -0.017  0.005  0.183   0.04
3  0.058  0.085  0.033  0.005  0.065  0.046 -0.024  0.012  0.195   0.15
4  0.038  0.092  0.075  0.003  0.064  0.054 -0.187 -0.304  0.219  0.157
5  0.051  0.086  0.096  0.055  0.051  0.047   -0.1 -0.166  0.174  0.034

     417    418    419    420    421    422    423    424    425    426  \
0  0.021  0.008 -0.004  0.621  0.046 -0.001 -0.027 -0.012 -0.015  0.042
1  0.014  0.001  -0.01  0.609  0.004 -0.018 -0.026 -0.012 -0.008  0.015
3  0.022  0.008 -0.019  0.626  0.046 -0.004  -0.03 -0.016 -0.014  0.024
4  0.019  0.011 -0.185  -0.34  0.049 -0.022 -0.056 -0.052 -0.034 -0.054
5  0.008  0.002 -0.097 -0.206 -0.004 -0.034 -0.039 -0.027 -0.014  -0.02

     427    428    429    430    431    432    433    434    435    436  \
0  0.063 -0.039 -0.151  -0.13 -0.127 -0.017  -0.05 -0.007 -0.079 -0.423
1  0.054 -0.031 -0.148 -0.128 -0.125 -0.004 -0.043 -0.021 -0.071 -0.414
3  0.045 -0.037 -0.148 -0.135 -0.132 -0.018 -0.047 -0.012 -0.077 -0.422
4 -0.301 -0.024  0.005 -0.045 -0.061 -0.069 -0.019 -0.013 -0.026 -0.031
5 -0.279 -0.027 -0.129 -0.144 -0.144 -0.024 -0.037 -0.029 -0.071 -0.411

     437    438    439    440    441    442    443    444    445    446  \
0 -0.238 -0.008  -0.05  0.012 -0.084 -0.023 -0.007 -0.196  0.008 -0.017
1 -0.227  0.003  -0.04  0.024 -0.066 -0.009  0.015 -0.182  0.018 -0.009
3 -0.244 -0.014 -0.051  0.011 -0.084 -0.026 -0.007 -0.194  0.007 -0.021
4 -0.054 -0.069 -0.113 -0.042 -0.061 -0.052 -0.047 -0.197  -0.04 -0.052
5 -0.244  -0.04 -0.071  0.003 -0.071 -0.008  0.002 -0.174 -0.003 -0.016

     447       448    449    450    451    452    453    454    455    456  \
0 -0.018  0.013176  1.221  0.048  0.134 -0.015  0.028 -0.006 -0.051  0.034

# impute here!!

In [16]:
from sklearn.impute import KNNImputer

# Replace '?' with np.nan explicitly
df = df.replace("?", np.nan)

/tmp/ipykernel_112661/2342245356.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace("?", np.nan)

In [17]:
# Now extract X and y properly
x_df = df.drop(columns=["result"])  # Drop the target column for features
y = df["result"]  # Keep the target variable

In [18]:
# Convert any 'pd.NA' to np.nan
x_df = x_df.applymap(lambda x: np.nan if pd.isna(x) else x)

# Ensure all values are numeric
x_df = x_df.astype(float)

# n_neighbors = 1 
# Apply KNN Imputer
imputer = KNNImputer(n_neighbors=5)
x_df = imputer.fit_transform(x_df)  # Returns a NumPy array

# Convert back to DataFrame
x_df = pd.DataFrame(x_df)

# Check for remaining NaNs
print(x_df.isna().sum().sum())  # Should print 0 if all missing values are imputed

/tmp/ipykernel_112661/2703309602.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  x_df = x_df.applymap(lambda x: np.nan if pd.isna(x) else x)

0

In [19]:
print(x_df.shape, y.shape)

(1895, 5408) (1895,)

In [20]:
x_df.head(20)

      0      1       2       3       4       5       6       7       8     \
0  -0.1610 -0.014  0.0020 -0.0360 -0.0330 -0.0930  0.0250  0.0050  0.0000
1  -0.1580 -0.002 -0.0120 -0.0250 -0.0120 -0.1060  0.0130  0.0050  0.0000
2  -0.1690 -0.025 -0.0100 -0.0410 -0.0450 -0.0690  0.0380  0.0140  0.0080
3  -0.1830 -0.051 -0.0230 -0.0770 -0.0920 -0.0150  0.0710  0.0270  0.0200
4  -0.1540  0.005 -0.0110 -0.0130 -0.0020 -0.1150  0.0050  0.0020 -0.0030
5  -0.1500  0.016 -0.0140  0.0000  0.0160 -0.1230 -0.0040 -0.0020 -0.0050
6  -0.1580  0.002 -0.0190 -0.0280 -0.0080 -0.1010  0.0110  0.0050  0.0010
7  -0.1520  0.009 -0.0150 -0.0080  0.0040 -0.1200 -0.0020 -0.0020 -0.0070
8  -0.1720 -0.028  0.0030 -0.0450 -0.0550 -0.0780  0.0390  0.0110  0.0060
9  -0.1640 -0.019 -0.0110 -0.0370 -0.0310 -0.0810  0.0290  0.0120  0.0070
10 -0.1480  0.018 -0.0120  0.0040  0.0210 -0.1280 -0.0070 -0.0030 -0.0060
11 -0.1530  0.012 -0.0170 -0.0090  0.0060 -0.1160  0.0000  0.0010 -0.0040
12 -0.1610 -0.014  0.0010 -0.0330 -0.0270 -0.0930  0.0230  0.0070  0.0030
13 -0.1530  0.010 -0.0170 -0.0120  0.0040 -0.1120  0.0040  0.0020 -0.0020
14 -0.1530  0.006 -0.0110 -0.0100  0.0000 -0.1190  0.0030  0.0000 -0.0050
15 -0.7708 -0.012  0.0114  0.0236  0.0458 -0.1178  0.0064  0.0154  0.0104
16 -3.2720 -0.168  0.1130  0.0640  0.0570 -0.0500  0.0840  0.0970  0.0890
17 -0.1410  0.035 -0.0150  0.0230  0.0590 -0.1430 -0.0180 -0.0060 -0.0100
18 -0.1660 -0.019  0.0000 -0.0410 -0.0380 -0.0930  0.0290  0.0080  0.0030
19 -0.1750 -0.036 -0.0220 -0.0580 -0.0610 -0.0430  0.0520  0.0220  0.0150

     9       10      11      12      13      14      15      16     17    \
0  -0.015 -0.0300 -0.0500 -0.0310 -0.0360 -0.0930 -0.0080 -0.0300 -0.023
1  -0.002 -0.0070 -0.0100 -0.0090 -0.0170 -0.0240  0.0020  0.0030 -0.011
2  -0.014 -0.0320 -0.0430 -0.0330 -0.0460 -0.0940 -0.0170 -0.0420 -0.022
3  -0.019 -0.0440 -0.0970 -0.0520 -0.0790 -0.1750 -0.0400 -0.0840 -0.030
4   0.002  0.0060 -0.0020 -0.0040 -0.0090 -0.0110  0.0060  0.0150 -0.008
5   0.010  0.0340  0.0130  0.0090  0.0050  0.0310  0.0150  0.0370 -0.001
6   0.003  0.0040 -0.0040 -0.0040 -0.0130 -0.0150  0.0020  0.0110 -0.007
7   0.004  0.0220  0.0030  0.0000 -0.0030  0.0140  0.0100  0.0270 -0.007
8  -0.020 -0.0370 -0.0830 -0.0430 -0.0530 -0.1270 -0.0220 -0.0590 -0.029
9  -0.010 -0.0260 -0.0220 -0.0260 -0.0370 -0.0710 -0.0120 -0.0270 -0.018
10  0.010  0.0360  0.0150  0.0100  0.0070  0.0310  0.0150  0.0390 -0.001
11  0.008  0.0300  0.0110  0.0060  0.0000  0.0190  0.0110  0.0300 -0.003
12 -0.013 -0.0280 -0.0360 -0.0270 -0.0330 -0.0750 -0.0080 -0.0240 -0.020
13  0.007  0.0290  0.0090  0.0040 -0.0030  0.0080  0.0090  0.0250 -0.003
14  0.004  0.0110  0.0000 -0.0030 -0.0070 -0.0060  0.0060  0.0180 -0.007
15 -0.004 -0.0946 -0.2708 -0.2628  0.0248  0.0424  0.0284  0.0502  0.010
16 -0.078 -0.6740 -1.4570 -1.3860 -0.0430  0.0020  0.0570  0.0340  0.040
17  0.018  0.0630  0.0330  0.0250  0.0590  0.0730  0.0300  0.0680  0.007
18 -0.017 -0.0310 -0.0540 -0.0350 -0.0400 -0.1030 -0.0190 -0.0400 -0.023
19 -0.014 -0.0350 -0.0480 -0.0370 -0.0590 -0.1050 -0.0310 -0.0560 -0.022

      18     19      20     21      22      23      24      25      26    \
0  -0.0360 -0.042 -0.0380 -0.036 -0.0880 -0.1020 -0.0210 -0.0310 -0.0530
1  -0.0130 -0.010 -0.0190 -0.017 -0.0230 -0.0440 -0.0040 -0.0190 -0.0330
2  -0.0330 -0.039 -0.0440 -0.040 -0.0910 -0.1320 -0.0350 -0.0360 -0.0620
3  -0.0470 -0.058 -0.0670 -0.063 -0.1480 -0.2280 -1.0080 -0.0580 -0.0940
4  -0.0090 -0.004 -0.0100 -0.011 -0.0070 -0.0160  0.0050 -0.0110 -0.0220
5   0.0030  0.010  0.0020  0.001  0.0280  0.0230  0.0180 -0.0010 -0.0080
6  -0.0060 -0.001 -0.0120 -0.012 -0.0050 -0.0330 -0.0020 -0.0150 -0.0280
7  -0.0060  0.000 -0.0070 -0.007  0.0090  0.0050  0.0170 -0.0080 -0.0170
8  -0.0480 -0.058 -0.0520 -0.049 -0.1270 -0.1530 -0.0480 -0.0410 -0.0690
9  -0.0270 -0.026 -0.0340 -0.033 -0.0700 -0.1040 -0.0250 -0.0290 -0.0510
10  0.0030  0.013  0.0030  0.003  0.0320  0.0320  0.0210 -0.0010 -0.0060
11  0.0010  0.010 -0.0030 -0.003  0.0200  0.0080  0.0130 -0.0070 -0.0140
12 -0.0300 -0.034 -0.0340 -0.032 -0.0760 -0.0890 -0.0190 -0.0270 -0.0480
13 -0.0010  0.009 -0.0050 -0.005  0.0150  0.0000  0.0110 -0.0080 -0.0170
14 -0.0070 -0.002 -0.0080 -0.008 -0.0020 -0.0080  0.0060 -0.0100 -0.0200
15  0.0186  0.082  0.0186  0.018  0.0538  0.0278 -0.1602  0.0086  0.0034
16  0.0570  0.322  0.0520  0.058  0.0600 -0.0890 -0.9120  0.0210  0.0030
17  0.0150  0.030  0.0180  0.014  0.0710  0.0810  0.0380  0.0120  0.0120
18 -0.0380 -0.045 -0.0410 -0.039 -0.0980 -0.1110 -0.0350 -0.0300 -0.0550
19 -0.0320 -0.039 -0.0490 -0.047 -0.1010 -0.1690 -0.0540 -0.0440 -0.0720

     27      28      29      30      31      32      33      34      35    \
0  -0.257 -0.1140 -0.0750 -0.0370  0.0800  0.0270 -0.1610  0.0560 -0.0040
1  -0.187 -0.0740 -0.0570 -0.0440  0.0440  0.0060 -0.1460  0.0090 -0.0170
2  -0.258 -0.1330 -0.0970 -0.0700  0.0690  0.0140 -0.1770  0.0530 -0.0060
3  -0.315 -0.2040 -0.1560 -0.1220  0.0810  0.0070 -0.2040  0.0840  0.0030
4  -0.161 -0.0580 -0.0430 -0.0300  0.0410  0.0080 -0.1330  0.0000 -0.0200
5  -0.117 -0.0340 -0.0280 -0.0240  0.0240  0.0010 -0.0990 -0.0240 -0.0270
6  -0.167 -0.0670 -0.0540 -0.0520  0.0330 -0.0010 -0.1400 -0.0040 -0.0200
7  -0.141 -0.0430 -0.0270 -0.0100  0.0470  0.0100 -0.1110 -0.0010 -0.0230
8  -0.292 -0.1550 -0.1070 -0.0630  0.0830  0.0220 -0.1820  0.0690 -0.0020
9  -0.233 -0.1130 -0.0840 -0.0610  0.0620  0.0130 -0.1630  0.0420 -0.0090
10 -0.110 -0.0310 -0.0250 -0.0220  0.0270  0.0010 -0.0960 -0.0260 -0.0270
11 -0.131 -0.0440 -0.0350 -0.0350  0.0260 -0.0010 -0.1130 -0.0210 -0.0250
12 -0.236 -0.1030 -0.0680 -0.0380  0.0740  0.0260 -0.1610  0.0520 -0.0050
13 -0.139 -0.0490 -0.0390 -0.0390  0.0300  0.0000 -0.1200 -0.0120 -0.0240
14 -0.157 -0.0530 -0.0390 -0.0310  0.0360  0.0050 -0.1180 -0.0010 -0.0200
15 -0.119 -0.0322 -0.0308 -0.0266  0.0252  0.0108 -0.0744 -0.0388 -0.0292
16 -0.274 -0.1050 -0.0900 -0.0670  0.0600  0.0620 -0.0630 -0.0370 -0.0260
17 -0.050  0.0030 -0.0050 -0.0090  0.0110 -0.0030 -0.0440 -0.0480 -0.0320
18 -0.262 -0.1250 -0.0860 -0.0480  0.0750  0.0220 -0.1790  0.0540 -0.0060
19 -0.270 -0.1580 -0.1250 -0.1040  0.0650  0.0020 -0.1850  0.0570 -0.0060

      36      37      38        39        40      41     42      43      44    \
0   0.0020  0.0030 -0.0330 -0.056133 -0.019444  0.0160  0.004  0.0380  0.0280
1  -0.0090 -0.0080 -0.0290 -0.010433  0.012889  0.0230  0.022  0.0260  0.0600
2  -0.0020 -0.0050 -0.0310 -0.070167 -0.035333  0.0060 -0.010  0.0290 -0.0130
3   0.0000 -0.0080 -0.0280 -0.113500 -0.114333 -0.0020 -0.032  0.0340 -0.0730
4  -0.0120 -0.0100 -0.0290  0.000033  0.008278  0.0180  0.010  0.0430  0.0500
5  -0.0170 -0.0130 -0.0270  0.012600  0.022778  0.0190  0.014  0.0410  0.0650
6  -0.0140 -0.0140 -0.0260 -0.006900  0.000778  0.0130  0.003  0.0400  0.0360
7  -0.0250 -0.0240 -0.0340  0.006400  0.016667  0.0250  0.020  0.0520  0.0660
8   0.0020  0.0020 -0.0370 -0.090433 -0.048667  0.0150 -0.005  0.0500 -0.0140
9  -0.0050 -0.0060 -0.0300 -0.074700 -0.021222  0.0100 -0.003  0.0300 -0.0240
10 -0.0170 -0.0140 -0.0280  0.012433  0.025167  0.0170  0.017  0.0290  0.0520
11 -0.0170 -0.0150 -0.0260  0.006733  0.015778  0.0160  0.009  0.0380  0.0560
12  0.0000  0.0020 -0.0320 -0.056833 -0.032278  0.0190  0.006  0.0490  0.0280
13 -0.0150 -0.0130 -0.0280  0.004833  0.014667  0.0130  0.006  0.0360  0.0470
14 -0.0120 -0.0100 -0.0290  0.003400  0.027278  0.1600  0.066  0.2320  0.1220
15 -0.0178 -0.0114 -0.0238  0.030900  0.034544  0.1948  0.179  0.2156  0.4244
16 -0.0100  0.0070 -0.0240  0.011933  0.027667  0.1370  0.041  0.2080  0.0930
17 -0.0210 -0.0170 -0.0250  0.050300  0.040222  0.1250  0.034 -0.0020  0.1020
18 -0.0010  0.0010 -0.0370 -0.118800 -0.028278  0.1360  0.005  0.2090  0.0260
19 -0.0060 -0.0120 -0.0280 -0.136900 -0.053611  0.1500  0.000  0.2110  0.0000

      45      46     47     48      49     50      51      52      53    \
0  -0.0160 -0.0270 -0.044 -0.055 -0.0240  0.016 -0.0200 -0.0190 -0.0240
1  -0.0250  0.0530 -0.053 -0.087 -0.0290 -0.075 -0.1220 -0.3630 -0.0100
2  -0.0320 -0.0300 -0.049 -0.084 -0.0280 -0.012 -0.0510 -0.3770 -0.0500
3  -0.1080 -0.0660 -0.073 -0.166 -0.0460 -0.038 -0.1250 -0.4230 -0.1180
4  -0.0030 -0.0110 -0.025 -0.014 -0.0090  0.008 -0.0060 -0.0250 -0.0190
5   0.0060 -0.0020 -0.015  0.009 -0.0020  0.001  0.0010 -0.0130 -0.0070
6  -0.0070 -0.0090 -0.025 -0.027 -0.0100 -0.010 -0.0230 -0.0280 -0.0230
7   0.0040 -0.0040 -0.018 -0.002 -0.0050  0.013  0.0030 -0.0150 -0.0110
8  -0.0610 -0.0660 -0.069 -0.105 -0.0350  0.012 -0.0570 -0.0890 -0.0930
9  -0.0440 -0.0400 -0.042 -0.065 -0.0080 -0.023 -0.0660 -0.4160 -0.0760
10  0.0050  0.0030 -0.003  0.023  0.0170 -0.007 -0.0090 -0.0230 -0.0040
11  0.0060  0.0020 -0.014  0.000 -0.0040 -0.001 -0.0060 -0.0150 -0.0060
12 -0.0310 -0.0420 -0.052 -0.062 -0.0250  0.019 -0.0260 -0.0600 -0.0590
13  0.0050  0.0040 -0.011  0.001 -0.0040  0.000 -0.0050 -0.0220 -0.0060
14  0.0450  0.0520  0.004 -0.001 -0.0300  0.071  0.0690  0.0530  0.0560
15  0.4988  0.3972  0.281  0.122 -0.0062  0.226  0.3768  0.5722  0.6712
16  0.0360  0.0530  0.013  0.006 -0.0520  0.036  0.0500  0.0420  0.0570
17  0.0500  0.0700  0.029  0.036 -0.0610  0.041  0.0630  0.0560  0.0700
18 -0.0050  0.0180 -0.030 -0.381 -0.2240  0.060  0.0270 -0.3300  0.0080
19 -0.0270  0.0200 -0.030 -0.374 -0.2080  0.027 -0.0230 -0.3500 -0.0100

     54      55      56      57     58     59      60      61      62    \
0   0.007 -0.0460 -0.0520  0.0420 -0.059 -0.073 -0.0200  0.0160 -0.0180
1   0.101  0.0060 -0.1040 -0.0290 -0.240 -0.099  0.0270  0.1200  0.0860
2   0.008 -0.0710 -0.0730  0.0190 -0.040 -0.076 -0.0400 -0.0140 -0.0340
3  -0.030 -0.1840 -0.1330 -0.0370 -0.089 -0.187 -0.1490 -0.1210 -0.1200
4  -0.006 -0.0270 -0.0300  0.0250 -0.110 -0.114 -0.0220  0.0020 -0.0210
5   0.001 -0.0060 -0.0170  0.0190 -0.108 -0.100 -0.0120  0.0090 -0.0080
6   0.002 -0.0350 -0.0380  0.0120 -0.104 -0.110 -0.0350 -0.0180 -0.0270
7   0.000 -0.0170 -0.0230  0.0240 -0.099 -0.102 -0.0140  0.0070 -0.0140
8  -0.043 -0.1350 -0.0940  0.0250 -0.139 -0.179 -0.1010 -0.0620 -0.0900
9  -0.019 -0.0860 -0.0550 -0.0200 -0.136 -0.146 -0.0800 -0.0530 -0.0650
10  0.003  0.0090  0.0060  0.0040 -0.124 -0.096 -0.0070  0.0100 -0.0020
11  0.006 -0.0060 -0.0180  0.0170 -0.106 -0.099 -0.0130  0.0040 -0.0090
12 -0.027 -0.0850 -0.0640  0.0310 -0.125 -0.151 -0.0580 -0.0210 -0.0560
13  0.009 -0.0050 -0.0160  0.0220 -0.117 -0.106 -0.0140  0.0040 -0.0070
14  0.063  0.0470 -0.0050  0.0460 -0.020 -0.017  0.0440  0.0410  0.0320
15  0.436  0.4148  0.1782  0.2086  0.375  0.366  0.1462  0.2178  0.3262
16  0.063  0.0680  0.0080  0.0110 -0.038 -0.010  0.0560  0.0570  0.0440
17  0.099  0.0920  0.0190  0.0100 -0.049 -0.006  0.0690  0.0670  0.0570
18  0.055 -0.0050 -0.0980  0.0360 -0.023 -0.031  0.0030  0.0120 -0.0040
19  0.069 -0.0370 -0.1060 -0.0160 -0.005 -0.044 -0.0180 -0.0160 -0.0200

      63      64      65     66      67      68      69      70      71    \
0  -0.0230 -0.0390 -0.2680 -0.036  0.0150 -0.0030 -0.0190 -0.0190 -0.0530
1   0.1990 -0.1850 -0.6400 -0.066  0.0590  0.0170  0.0530  0.0840 -0.1490
2  -0.0170 -0.0430 -0.2700 -0.033  0.0000 -0.0110 -0.0240 -0.0260 -0.0500
3  -0.1240 -0.0980 -0.4780 -0.068 -0.0620 -0.0530 -0.0780 -0.0820 -0.1210
4   0.0170 -0.0510 -0.4440 -0.062  0.0150 -0.0270 -0.0320 -0.0300 -0.0780
5   0.0530 -0.0470 -0.4300 -0.062  0.0170 -0.0280 -0.0230 -0.0190 -0.0740
6   0.0290 -0.0520 -0.4260 -0.060  0.0000 -0.0340 -0.0320 -0.0290 -0.0770
7   0.0340 -0.0450 -0.4090 -0.060  0.0180 -0.0270 -0.0280 -0.0250 -0.0720
8  -0.1340 -0.0940 -0.5440 -0.081 -0.0300 -0.0430 -0.0690 -0.0750 -0.1210
9  -0.0990 -0.0840 -0.4510 -0.070 -0.0270 -0.0370 -0.0520 -0.0490 -0.0970
10  0.0360 -0.0500 -0.4110 -0.060  0.0140 -0.0260 -0.0190 -0.0120 -0.0670
11  0.0630 -0.0440 -0.4100 -0.057  0.0130 -0.0290 -0.0220 -0.0190 -0.0690
12 -0.0740 -0.0730 -0.5000 -0.072 -0.0020 -0.0330 -0.0590 -0.0570 -0.1030
13  0.0560 -0.0450 -0.4690 -0.055  0.0160 -0.0260 -0.0200 -0.0150 -0.0720
14  0.1320  0.0000 -0.2620 -0.010  0.0510  0.0040  0.0110  0.0050 -0.0210
15  0.5094  0.0974 -0.2592  0.102  0.1262  0.1222  0.1498  0.2014  0.0308
16  0.1460 -0.0100 -0.2330 -0.008  0.0540  0.0040  0.0180  0.0190 -0.0160
17  0.1760 -0.0090 -0.2520 -0.009  0.0590  0.0000  0.0230  0.0240 -0.0160
18  0.0300 -0.0140 -0.2710 -0.010  0.0350  0.0160 -0.0010 -0.0150 -0.0330
19  0.0640 -0.0300 -0.2280 -0.002  0.0170  0.0000 -0.0110 -0.0240 -0.0270

     72     73      74     75      76      77      78     79      80     81    \
0  -0.037 -0.002 -0.0340 -0.031 -0.0340 -0.0250  0.0180  0.008 -0.0170 -0.042
1  -0.047  0.049 -0.0480 -0.012 -0.0070 -0.0030  0.0710  0.048 -0.0450 -0.081
2  -0.035  0.000 -0.0230 -0.023 -0.0280 -0.0260  0.0150  0.015 -0.0070 -0.028
3  -0.107 -0.046 -0.0340 -0.040 -0.0470 -0.0570 -0.0640  0.054 -0.0300 -0.052
4  -0.059 -0.007 -0.0640 -0.049 -0.0400 -0.0260  0.0050 -0.009 -0.0310 -0.088
5  -0.050  0.002 -0.0640 -0.046 -0.0360 -0.0190  0.0160 -0.003 -0.0270 -0.092
6  -0.055 -0.003 -0.0550 -0.043 -0.0350 -0.0260  0.0070 -0.003 -0.0230 -0.079
7  -0.052 -0.001 -0.0640 -0.048 -0.0380 -0.0230  0.0120 -0.006 -0.0300 -0.088
8  -0.111 -0.053 -0.0650 -0.061 -0.0600 -0.0530 -0.0550 -0.025 -0.0500 -0.078
9  -0.078 -0.024 -0.0440 -0.042 -0.0420 -0.0460 -0.0180 -0.006 -0.0270 -0.063
10 -0.041  0.009 -0.0560 -0.041 -0.0310 -0.0230  0.0210  0.002 -0.0200 -0.081
11 -0.046  0.005 -0.0590 -0.043 -0.0330 -0.0200  0.0170  0.000 -0.0220 -0.084
12 -0.090 -0.035 -0.0680 -0.059 -0.0550 -0.0420 -0.0260 -0.022 -0.0450 -0.085
13 -0.047  0.010 -0.0550 -0.039 -0.0300 -0.0190  0.0210  0.005 -0.0190 -0.081
14  0.002  0.038 -0.0300 -0.019 -0.0180 -0.0290  0.0520  0.026 -0.0020 -0.064
15  0.032  0.044 -0.0048  0.066  0.1108  0.0472  0.0748  0.045  0.0284 -0.003
16  0.009  0.047 -0.0250 -0.017 -0.0110 -0.0300  0.0600  0.031  0.0090 -0.058
17  0.015  0.053 -0.0330 -0.020 -0.0120 -0.0250  0.0680  0.032  0.0060 -0.071
18 -0.017  0.022 -0.0070 -0.016 -0.0220 -0.0660  0.0260  0.023  0.0020 -0.031
19 -0.011  0.022  0.0080 -0.007 -0.0180 -0.0800  0.0210  0.035  0.0170 -0.017

      82      83      84      85      86      87     88      89      90    \
0  -0.0350 -0.0650 -0.0760  0.0060 -0.0240 -0.0230 -0.048 -0.0490 -0.0490
1  -0.0290  0.0930 -0.0680 -0.0480  0.0060 -0.0080 -0.012  0.0060 -0.0070
2  -0.0230 -0.0690 -0.0710  0.0100 -0.0560 -0.0510 -0.050 -0.0650 -0.0470
3  -0.0520 -0.1840 -0.0890 -0.1110 -0.1160 -0.0870 -0.096 -0.1390 -0.0970
4  -0.0560 -0.0700 -0.0810 -0.0900  0.0120 -0.0110  0.003  0.0280  0.0160
5  -0.0520 -0.0510 -0.0760 -0.0880  0.0310 -0.0010  0.008  0.0520  0.0190
6  -0.0470 -0.0730 -0.0750 -0.0880  0.0010 -0.0180  0.002  0.0180  0.0150
7  -0.0530 -0.0600 -0.0770 -0.0870  0.0230 -0.0060  0.011  0.0410  0.0270
8  -0.0710 -0.1650 -0.1090 -0.1140 -0.0640 -0.0560 -0.062 -0.0830 -0.0550
9  -0.0500 -0.1210 -0.0740 -0.0900 -0.0380 -0.0420 -0.035 -0.0390 -0.0310
10 -0.0430 -0.0420 -0.0660 -0.0740  0.0360  0.0040  0.023  0.0620  0.0420
11 -0.0460 -0.0490 -0.0730 -0.0820  0.0230 -0.0040  0.014  0.0460  0.0310
12 -0.0680 -0.1250 -0.0960 -0.1040 -0.0380 -0.0440 -0.047 -0.0410 -0.0370
13 -0.0450 -0.0600 -0.0680 -0.0820  0.0210 -0.0060  0.009  0.0420  0.0220
14 -0.0340  0.0040 -0.0480 -0.0660  0.0150 -0.0080  0.004  0.0340  0.0190
15  0.0618  0.0188  0.0138  0.0138  0.0488  0.0132  0.035  0.0812  0.0542
16 -0.0200  0.0270 -0.0350 -0.0550  0.0390  0.0050  0.028  0.0660  0.0440
17 -0.0210  0.0490 -0.0370 -0.0570  0.0640  0.0220  0.049  0.1020  0.0690
18 -0.0240 -0.0500 -0.0470 -0.0590 -0.0410 -0.0440 -0.047 -0.0500 -0.0350
19 -0.0120 -0.0590 -0.0340 -0.0630 -0.0780 -0.0650 -0.063 -0.0870 -0.0620

     91      92     93      94      95      96      97     98      99    \
0  -0.069 -0.0260  0.049  0.0490  0.0250 -0.0250  3.5930  3.082  4.4110
1  -0.021 -0.0100  0.036  0.0240  0.0140 -0.0050  3.6000  3.094  4.4060
2  -0.062 -0.0250  0.060  0.0530  0.0200 -0.0310  3.5910  3.075  4.4050
3  -0.103 -0.0390  0.036  0.0760  0.0190 -0.0550  3.5890  3.056  4.3980
4  -0.008  0.0040  0.071  0.0460  0.0360  0.0180  0.0430  2.910  0.0050
5   0.009 -0.0280  0.017 -0.0130 -0.0110 -0.0020  0.0070  2.881 -0.0150
6  -0.005 -0.0160  0.046  0.0270  0.0130  0.0010  3.5940  3.096  4.4200
7   0.005  0.0000  0.030  0.0140  0.0170  0.0110  3.6030  3.093  4.4330
8  -0.085 -0.0390  0.082  0.0610  0.0250 -0.0360  3.5920  3.069  4.4500
9  -0.048 -0.0190  0.052  0.0440  0.0180 -0.0230  3.5960  3.082  4.4170
10  0.017  0.0050  0.025  0.0050  0.0160  0.0200  3.6040  3.093  4.4380
11  0.012  0.0010  0.031  0.0090  0.0140  0.0140  3.6040  3.097  4.4320
12 -0.054 -0.0090 -0.054  0.0360  0.0370 -0.0080  3.6080  3.083  4.4410
13  0.007 -0.0760  0.021  0.0060 -0.0020  0.0020  3.6230  3.108  4.4040
14 -0.004 -0.0050  0.029  0.0160  0.0170  0.0060  3.6020  3.094  4.2700
15  0.031  0.0056  0.022 -0.0024  0.0162  0.0284  3.6056  3.096  4.3364
16  0.022  0.0050  0.023  0.0020  0.0150  0.0220  3.6030  3.094  4.2740
17  0.045  0.0100  0.019 -0.0100  0.0170  0.0390  3.6080  3.098  4.4280
18 -0.066 -0.0320  0.045  0.0510  0.0260 -0.0280  3.5890  3.075  4.2660
19 -0.070 -0.0320  0.058  0.0540  0.0130 -0.0390  3.5900  3.068  4.2480

      100     101     102    103     104     105       106       107   \
0   3.6950  2.7650  0.0380  0.463  0.6040  0.9040 -0.144053  0.027000
1   3.6960  2.7760  0.0270  0.412  0.6090  0.9100 -0.172632  0.024812
2   3.6900  2.7620  0.0430  0.450  0.5950  0.8960 -0.158158  0.050250
3   3.6840  2.7470 -0.9630  0.444  0.5740  0.8720 -0.038211  0.045687
4   3.1030  2.4950 -2.8520 -2.116 -1.9790  0.4070 -0.178263  0.024250
5   3.0850  2.4610 -2.8930 -2.113 -1.9220  0.7360  0.029105  0.019625
6   3.7100  2.7940  0.0160  0.401  0.6240  0.9240 -0.183842  0.022937
7   3.7220  2.8300  0.0090  0.411  0.6450  1.2160 -0.180211  0.022187
8   3.7160  2.7630  0.1390  0.499  0.6080  0.8930 -0.024158  0.046938
9   3.7030  2.7750  0.0220  0.451  0.6090  0.9090 -0.176737  0.032563
10  3.7260  2.8350  0.0030  0.402  0.6520  1.2230  0.029684  0.019000
11  3.7230  2.8310  0.0050  0.401  0.6430  1.2140  0.026684  0.020188
12  3.7160  2.8150  0.1100  0.461  0.6870  1.2120 -0.169263  0.024688
13  3.7120  2.8200  0.0000  0.382  0.6210  1.2010  0.026947  0.020875
14  3.6800  2.7940  0.0190  0.399  0.6250  1.1810 -0.172789  0.023750
15  3.7096  2.8174 -0.1126  0.377  0.6416  1.2146 -0.000611  0.017350
16  3.6910  2.8080 -0.0120  0.381  0.6340  1.1950  0.032105  0.018000
17  3.7260  2.8280 -0.2740  0.369  0.6510  1.2330  0.030895  0.016750
18  3.6550  2.7190  0.0360  0.450  0.5820  0.8640 -0.158105  0.026937
19  3.6400  2.7110  0.0330  0.417  0.5650  0.8490 -0.040316  0.050875

        108     109     110     111    112     113     114     115    116   \
0   0.085904 -0.0440 -0.0030  0.0340 -0.021 -0.0240  0.0330 -0.0140  0.023
1   0.082942 -0.0420  0.0060  0.0410 -0.026 -0.0110  0.0050 -0.0030 -0.013
2   0.146481 -0.0620  0.0040  0.0050 -0.032 -0.0190  0.0350 -0.0130  0.010
3   0.112500 -0.0820 -0.0050 -0.0180 -0.075 -0.0280  0.0460 -0.0210  0.005
4   0.022962 -0.0370  0.0100  0.0370 -0.029 -0.0070  0.0100  0.0020 -0.014
5   0.018885 -0.0360  0.0140  0.0460 -0.010  0.0160 -0.0040  0.0090 -0.028
6   0.082404 -0.0430  0.0060  0.0320 -0.035 -0.0060  0.0020  0.0030 -0.023
7   0.019096 -0.0370  0.0100  0.0300 -0.033 -0.0030  0.0080  0.0070 -0.023
8   0.147538 -0.0700  0.0080  0.0020 -0.057 -0.0230  0.0520 -0.0180  0.031
9   0.079923 -0.0510  0.0050  0.0160 -0.012 -0.0160  0.0280 -0.0080  0.004
10  0.019154 -0.0370  0.0060  0.0470 -0.011  0.0140 -0.0020  0.0100 -0.028
11  0.017577 -0.0400  0.0080  0.0410 -0.014  0.0120 -0.0040  0.0080 -0.027
12  0.084096 -0.0490  0.0090  0.0170 -0.016 -0.0160  0.0370 -0.0110  0.012
13  0.017923 -0.0390  0.0090  0.0350 -0.014  0.0130 -0.0010  0.0050 -0.025
14  0.018885 -0.0410  0.0020  0.0800 -0.039 -0.0110  0.0060  0.0000 -0.007
15  0.010619 -0.0378  0.0078  0.0622 -0.012  0.0108 -0.0106  0.0138 -0.028
16  0.018538 -0.0380  0.0060  0.0460 -0.011  0.0120 -0.0070  0.0110 -0.030

In [21]:
y.head(20)

0     inactive
1     inactive
3     inactive
4     inactive
5     inactive
6     inactive
7     inactive
8     inactive
9     inactive
10    inactive
11    inactive
12    inactive
13    inactive
14    inactive
15    inactive
16    inactive
17      active
18      active
19      active
20      active
Name: result, dtype: object

In [23]:
# This is the help I got from ChatGPT 4o to determine which rows were used to impute row 15. 
# Since n_neighbors=1 returned whatever row was closest, I had to make sure it was not just using the closest rows in my dataset. 

from sklearn.metrics.pairwise import nan_euclidean_distances
import numpy as np

# Assume x_df is your original dataframe (before imputation)
x_imputed = imputer.fit_transform(x_df)  # Imputed Data

# Compute distances to find nearest neighbors
distances = nan_euclidean_distances(x_df)
nearest_neighbors = np.argsort(distances, axis=1)[:, 1:4]  # Get top 3 nearest neighbors

# Show the 3 nearest rows used for row 15
print("Nearest neighbors for row 15:")
print(x_df.iloc[nearest_neighbors[15]])

Nearest neighbors for row 15:
     0      1      2      3      4      5      6      7      8      9     \
25 -0.148  0.024 -0.015  0.008  0.033 -0.129 -0.010 -0.003 -0.008  0.013
16 -3.272 -0.168  0.113  0.064  0.057 -0.050  0.084  0.097  0.089 -0.078
23 -0.142  0.039 -0.016  0.028  0.071 -0.144 -0.022 -0.009 -0.012  0.021

     10     11     12     13     14     15     16     17     18     19    \
25  0.050  0.024  0.016  0.020  0.047  0.017  0.049  0.001  0.007  0.021
16 -0.674 -1.457 -1.386 -0.043  0.002  0.057  0.034  0.040  0.057  0.322
23  0.069  0.040  0.030  0.079  0.083  0.029  0.074  0.008  0.018  0.035

     20     21     22     23     24     25     26     27     28     29    \
25  0.007  0.005  0.047  0.044  0.023  0.002  0.000 -0.096 -0.022 -0.019
16  0.052  0.058  0.060 -0.089 -0.912  0.021  0.003 -0.274 -0.105 -0.090
23  0.021  0.019  0.084  0.096  0.039  0.014  0.016 -0.038  0.007 -0.003

     30     31     32     33     34     35     36     37     38        39    \
25 -0.021  0.017 -0.003 -0.091 -0.040 -0.030 -0.020 -0.017 -0.025  0.020567
16 -0.067  0.060  0.062 -0.063 -0.037 -0.026 -0.010  0.007 -0.024  0.011933
23 -0.009  0.006 -0.006 -0.057 -0.061 -0.036 -0.023 -0.018 -0.021  0.035800

        40     41     42     43     44     45     46     47     48     49    \
25  0.029944  0.410  0.693  0.555  1.655  2.302  1.742  1.328  0.511  0.133
16  0.027667  0.137  0.041  0.208  0.093  0.036  0.053  0.013  0.006 -0.052
23  0.043722  0.093  0.257 -0.195  0.036  0.068  0.081  0.046  0.059 -0.006

     50     51     52     53     54     55     56     57     58     59    \
25  0.930  1.616  2.637  3.089  1.831  1.763  0.832  0.950  2.008  1.858
16  0.036  0.050  0.042  0.057  0.063  0.068  0.008  0.011 -0.038 -0.010
23 -0.968 -0.513 -0.154  0.081  0.113  0.101  0.056 -0.423 -0.219  0.012

     60     61     62     63     64     65     66     67     68     69    \
25  0.479  0.846  1.429  1.889  0.500 -0.311  0.543  0.395  0.602  0.668
16  0.056  0.057  0.044  0.146 -0.010 -0.233 -0.008  0.054  0.004  0.018
23  0.070  0.054  0.048  0.171 -0.169 -0.096 -0.012  0.054 -0.007  0.012

     70     71     72     73     74     75     76     77     78     79    \
25  0.930  0.220  0.115  0.024  0.106  0.407  0.607  0.331  0.121  0.105
16  0.019 -0.016  0.009  0.047 -0.025 -0.017 -0.011 -0.030  0.060  0.031
23  0.008 -0.018  0.010  0.044 -0.040 -0.027 -0.018 -0.016  0.060  0.020

     80     81     82     83     84     85     86     87     88     89    \
25  0.129  0.262  0.411 -0.045  0.234  0.310  0.048  0.015  0.032  0.077
16  0.009 -0.058 -0.020  0.027 -0.035 -0.055  0.039  0.005  0.028  0.066
23 -0.008 -0.079 -0.031  0.039 -0.043 -0.065  0.072  0.028  0.055  0.116

     90     91     92     93     94     95     96     97     98     99    \
25  0.052  0.032  0.004  0.023 -0.002  0.014  0.026  3.605  3.096  4.275
16  0.044  0.022  0.005  0.023  0.002  0.015  0.022  3.603  3.094  4.274
23  0.078  0.054  0.013  0.017 -0.014  0.017  0.044  3.608  3.097  4.280

     100    101    102    103    104    105       106       107       108   \
25  3.713  2.817 -0.010  0.377  0.637  1.220  0.031789  0.016563  0.018654
16  3.691  2.808 -0.012  0.381  0.634  1.195  0.032105  0.018000  0.018538
23  3.726  2.831 -0.281  0.362  0.653  1.237  0.075474  0.012687 -0.001346

     109    110    111    112    113    114    115    116    117    118   \
25 -0.038  0.010  0.052 -0.007  0.016 -0.011  0.014 -0.032  0.001  0.194
16 -0.038  0.006  0.046 -0.011  0.012 -0.007  0.011 -0.030 -0.004  0.192
23 -0.036  0.011  0.059 -0.002  0.020 -0.021  0.022 -0.038  0.010  0.195

     119    120    121    122    123    124    125    126    127    128   \
25  0.016  0.005  0.008 -0.029 -0.024 -0.004  0.010  0.074 -0.001  0.611
16  0.012  0.003  0.009 -0.032 -0.027 -0.007  0.013  0.072 -0.008  0.608
23  0.023  0.010  0.223 -0.019 -0.015  0.006  0.000  0.080  0.023  0.612

     129    130    131       132       133     134       135       136   \
25  0.045 -0.023  0.501  0.030030 -0.001182 -0.0675 -0.546771  0.008655
16  0.048  0.001  0.500  0.029424 -0.004841  0.0035 -0.548686  0.009138
23  0.031 -0.086  0.502  0.023364  0.001341 -0.0860 -0.544086  0.004310

     137    138    139    140    141    142    143    144    145    146   \
25  0.024  0.073 -0.004 -0.007  0.032  0.009 -0.023 -0.010  0.013  0.070
16  0.023  0.073 -0.002 -0.004  0.033  0.007 -0.020 -0.005  0.013  0.060
23 -0.056  0.050 -0.030 -0.048 -0.003  0.047 -0.034 -0.028 -0.014  0.079

     147    148    149    150    151    152    153    154    155    156   \
25  0.022 -0.011 -0.021 -0.055 -0.030 -0.061  0.003 -0.019 -0.038 -0.050
16  0.014 -0.009 -0.017 -0.052 -0.029 -0.065 -0.004 -0.018 -0.033 -0.045
23  0.042 -0.004 -0.025 -0.072 -0.030 -0.058  0.003 -0.014 -0.044 -0.056

     157    158    159       160    161    162    163    164    165    166   \
25 -0.017 -0.029 -0.052  0.056167 -0.039 -0.007 -0.057 -0.047 -0.033 -0.005
16 -0.017 -0.024 -0.045  0.050000 -0.044 -0.008 -0.056 -0.048 -0.033 -0.006
23 -0.029  0.009 -0.061  0.068000 -0.038 -0.001 -0.054 -0.040 -0.029 -0.069

     167       168       169       170       171    172    173    174    175   \
25  0.000 -0.005229 -0.009533  0.007569  0.012333 -0.059  0.195  0.026  0.037
16 -0.005 -0.007000 -0.010033  0.003923  0.014167 -0.054  0.199  0.019  0.036
23  0.003  0.002543 -0.004467  0.019000  0.019000 -0.087  0.164  0.032  0.045

     176    177    178    179    180    181    182    183    184    185   \
25  0.018  0.126  0.164 -0.130  0.034  0.019  0.030  0.030  0.079 -0.177
16  0.015  0.121  0.161 -0.133  0.033  0.019  0.028  0.027  0.074 -0.179
23  0.023  0.130  0.153 -0.040  0.040  0.023  0.034  0.032  0.093 -0.169

     186    187    188    189    190    191    192    193    194    195   \
25 -0.001 -0.002  0.032  0.044  0.039 -0.176 -0.093 -0.076  0.030  0.011
16  0.002 -0.002  0.032  0.044  0.037 -0.173 -0.094 -0.134  0.030  0.008
23 -0.006 -0.002  0.036  0.047  0.041 -0.179  0.040 -0.098  0.023  0.018

     196    197    198    199    200    201    202    203    204    205   \
25  0.032  0.024  0.021  0.016  0.031 -0.002  0.011 -0.129  0.042  0.036
16  0.030  0.023  0.021  0.016  0.029  0.000  0.013 -0.130  0.041  0.034
23  0.038  0.026  0.020  0.016  0.036 -0.007  0.013  0.037  0.042  0.044

     206    207    208    209    210    211    212    213    214    215   \
25  0.012  0.023  0.029  0.025  0.020  0.017  0.014  0.018  0.078  0.036
16  0.010  0.020  0.026  0.024  0.021  0.019  0.015  0.019  0.077  0.034
23  0.021  0.033  0.037  0.034  0.022  0.016  0.013  0.021  0.094  0.053

     216    217    218    219    220    221   222    223    224    225   \
25  0.036  0.030  0.007  0.009  0.016  0.015  0.01  0.180  0.051  0.003
16  0.033  0.029  0.009  0.009  0.013  0.013  0.01  0.178  0.051  0.002
23  0.051  0.033  0.004  0.015  0.035  0.028  0.01  0.194  0.062  0.006

     226    227    228    229    230    231    232    233    234    235   \
25  0.054  0.018 -0.018 -0.020  0.013  0.001 -0.015  0.021  0.011  0.004
16  0.049  0.015 -0.020 -0.027  0.006 -0.005 -0.020  0.015  0.001 -0.006
23  0.039  0.042 -0.010 -0.007  0.028  0.022 -0.003  0.023  0.031  0.032

     236    237    238    239    240    241    242    243    244    245   \
25  0.023  0.024 -0.070 -0.053  0.023  0.029  0.034  0.007  0.010 -0.030
16  0.012  0.013 -0.068 -0.054  0.018  0.018  0.020  0.007  0.006 -0.032
23  0.049  0.048 -0.078 -0.048  0.042  0.054  0.065  0.014  0.023 -0.037

     246    247    248    249    250    251    252    253    254    255   \
25 -0.050 -0.013  0.007  0.025  0.062 -0.079 -0.052 -0.006  0.012  0.049
16 -0.053 -0.014  0.002  0.022  0.053 -0.071 -0.053 -0.007  0.011  0.045
23 -0.053 -0.009  0.025  0.043  0.090 -0.118 -0.051  0.004  0.023  0.069

     256    257    258    259    260    261    262    263    264    265   \
25  0.053  0.061 -0.017 -0.014 -0.022 -0.006  0.007  0.023  0.072  0.040
16  0.044  0.049 -0.016 -0.017 -0.027 -0.011  0.007  0.018  0.065  0.028
23  0.082  0.099 -0.027 -0.017 -0.012 -0.001  0.016  0.041  0.107  0.075

     266    267    268    269    270    271    272    273    274    275   \
25 -0.008 -0.023 -0.002 -0.004  0.015  0.041 -0.087 -0.005 -0.002 -0.016
16 -0.012 -0.021 -0.006 -0.010  0.011  0.026 -0.066 -0.007  0.001 -0.017
23  0.005 -0.036  0.003 -0.004  0.037  0.074 -0.150 -0.004  0.002 -0.011

     276    277    278    279    280    281    282    283    284    285   \
25  0.026 -0.030 -0.015 -0.016  0.012  0.027 -0.062  0.081  0.021  0.008
16  0.030 -0.033 -0.017 -0.015 -0.003  0.015 -0.056  0.071  0.010 -0.001
23 -0.103 -0.020 -0.005 -0.014  0.041  0.060 -0.086  0.105  0.048  0.033

     286    287    288    289    290    291    292    293    294    295   \
25 -0.019 -0.450 -4.493  0.019  0.001 -0.126 -0.685 -4.252 -4.114 -0.090
16 -0.021 -0.454 -4.492  0.010 -0.002 -0.130 -0.685 -4.250 -4.113 -0.089
23 -0.013 -0.443 -4.495  0.044  0.007 -0.117 -0.681 -4.259 -4.115 -0.089

     296    297    298    299    300    301    302    303    304    305   \
25  0.019  0.012  0.007 -0.004 -0.082 -3.802 -2.928  0.007 -0.017 -2.713
16  0.012  0.009  0.004 -0.005 -0.081 -3.797 -2.907  0.011 -0.006 -2.700
23  0.051  0.024  0.017 -0.004 -0.095 -3.842 -2.938  0.006 -0.031 -2.745

        306       307     308      309    310    311    312    313    314   \
25  0.038577 -0.035333  0.0180  0.04140  0.044 -0.058 -0.029  0.002 -0.010
16  0.037577 -0.036333  0.0200  0.04116  0.046 -0.057 -0.027  0.001 -0.009
23  0.048077 -0.046667  0.0205  0.04458  0.040 -0.050 -0.022  0.009 -0.010

     315    316    317    318    319    320    321    322    323    324   \
25 -0.020 -0.021 -0.040 -0.018  0.002  0.001 -0.007 -0.013 -0.026 -0.019
16 -0.019 -0.020 -0.036 -0.016  0.003  0.005 -0.006 -0.012 -0.023 -0.017
23 -0.022 -0.020 -0.037 -0.015  0.005  0.001 -0.009 -0.010 -0.022 -0.018

     325    326    327    328    329    330    331    332    333    334   \
25  0.006  0.005  0.006  0.020 -0.008 -0.028 -0.010  0.007  0.009  0.011
16  0.007  0.005  0.006  0.021 -0.006 -0.024 -0.009  0.006  0.008  0.010
23  0.008  0.008  0.009  0.027 -0.003 -0.020 -0.005  0.009  0.014  0.018

     335    336    337    338    339    340    341    342    343    344   \
25  0.021 -0.067  0.011  0.012  0.016  3.002  0.012  0.043  0.023  0.027
16  0.019 -0.060  0.011  0.012  0.015  2.995  0.011  0.036  0.019  0.023
23  0.030 -0.058  0.012  0.015  0.022  3.040  0.014  0.060  0.032  0.043

     345    346    347    348    349    350    351    352    353    354   \
25 -0.126  0.020  0.014  0.088  0.056  0.059 -0.116 -0.098  0.000 -0.096
16 -0.116  0.020  0.004  0.113  0.059  0.058 -0.100 -0.879 -0.069 -0.664
23 -0.111  0.027  0.032 -0.014  0.027  0.060 -0.176 -0.065  0.001 -0.068

     355    356    357    358    359    360    361    362    363    364   \
25 -0.145  0.050 -0.053  1.342  0.159  0.008  0.009  0.309 -0.002 -0.083
16 -0.698  0.027 -0.279  0.093  0.063  0.008  0.027  0.172 -0.004 -0.124
23 -0.120  0.053 -0.038  0.120  0.092  0.023  0.026  0.178 -0.012 -0.068

     365    366    367    368    369    370    371    372    373    374   \
25  0.430  0.143 -0.039 -0.109  0.024  0.251 -0.066 -0.047 -0.138  0.041
16 -0.005 -0.028 -0.012 -0.128  0.012  0.095 -0.054 -0.036 -0.167 -0.014
23 -0.001 -0.005 -0.003 -0.112  0.016  0.231 -0.023 -0.026 -0.152  0.016

     375    376    377    378    379    380    381    382    383    384   \
25  0.081  0.024  0.190 -0.028  0.022  0.024  0.034  0.079  0.058 -0.005
16  0.609 -0.052  0.012 -0.034  0.013 -0.008 -0.012  0.052  0.003 -0.020
23  0.031 -0.049  0.012  0.013  0.039  0.016  0.018  0.024 -0.002 -0.023

     385    386    387    388    389    390    391    392    393    394   \
25  0.088  0.054  0.037  0.031 -0.123 -0.052  0.045  0.031  0.025  0.027
16  0.014  0.012  0.006 -0.007 -0.026 -0.030  0.003 -0.007 -0.022  0.004
23  0.045  0.050  0.041  0.024 -0.003 -0.072  0.045  0.035  0.011 -0.016

     395    396    397    398    399    400    401    402    403    404   \
25  0.093  0.081  0.078 -0.012 -0.074 -0.020 -0.121 -0.019 -0.072 -0.050
16  0.027  0.003 -0.045 -0.026 -0.056 -0.049 -1.056 -1.233 -1.794 -0.856
23  0.085  0.042  0.001 -0.012 -0.031 -0.024 -0.080 -0.035 -0.037 -0.061

     405    406    407    408    409    410    411    412    413    414   \
25 -0.026 -0.067 -0.040 -0.038 -0.054 -0.075 -0.011 -0.019 -0.124 -0.222
16 -0.991 -1.834 -0.296 -0.356 -0.607 -0.971 -0.132 -0.121 -0.512 -1.322
23  0.000 -0.062 -0.021 -0.013 -0.031 -0.074  0.004 -0.003 -0.117 -0.212

     415    416    417    418    419    420    421    422    423    424   \
25 -0.033 -0.040 -0.042 -0.033 -0.092 -0.262 -0.037 -0.054 -0.032 -0.019
16 -0.148 -0.016 -0.111 -0.085 -0.292 -0.868  0.082 -0.093 -0.061 -0.046
23 -0.008 -0.023 -0.027 -0.024 -0.086 -0.241 -0.035 -0.049 -0.034 -0.018

     425    426    427    428    429    430    431    432    433    434   \
25 -0.004 -0.006  0.017 -0.010  0.008  0.008  0.010  0.014 -0.043 -0.045
16 -0.015 -0.078 -0.356 -0.023 -0.005 -0.001  0.007  0.016 -0.012 -0.033
23 -0.004 -0.008  0.026 -0.020 -0.005  0.000  0.006  0.013 -0.047 -0.046

     435    436    437    438    439    440    441    442    443    444   \
25  0.019  0.005  0.014  0.025 -0.056  0.052  0.013  0.022  0.038 -0.168
16 -0.002 -0.004  0.010  0.021 -0.034 -0.019  0.001  0.009  0.065 -0.010
23  0.013 -0.002  0.011  0.025 -0.053  0.052  0.013  0.016  0.038 -0.162

     445    446    447       448    449    450    451    452    453    454   \
25  0.020  0.007  0.007  0.004235  1.117 -0.002  0.109  0.002  0.041  0.040
16 -0.014 -0.028 -0.019  0.003902  1.118  0.011  0.120 -0.012  0.039  0.030
23  0.023  0.004  0.004  0.011333  1.123 -0.001  0.110  0.007  0.057  0.045

     455    456    457    458    459    460       461    462    463    464   \
25 -0.053  0.063  0.032  0.090  0.039  0.570  0.011525 -0.063 -0.096 -0.045
16 -0.050  0.061  0.022  0.073  0.031  0.564  0.007450 -0.014 -0.095 -0.034
23 -0.044  0.074  0.041  0.101  0.049  0.613  0.015000 -0.074 -0.105 -0.047

     465    466    467    468    469    470    471    472    473    474   \
25 -0.028  0.001 -0.785  0.009 -0.015 -0.024 -0.014 -0.015  0.004  0.006
16 -0.051 -0.006 -0.781  0.003 -0.010 -0.019 -0.004 -0.013  0.004  0.007
23 -0.008  0.012 -0.792  0.023 -0.025 -0.046 -0.029 -0.022  0.002  0.003

     475    476   477    478    479    480    481    482    483    484   \
25  0.088 -0.015 -0.01 -0.006  1.035  0.001  0.019  0.074  0.016 -0.013
16  0.064 -0.013 -0.01 -0.001  1.028  0.001  0.025  0.074 -0.026 -0.005
23  0.165 -0.020 -0.01 -0.002  1.042 -0.073  0.032  0.085 -0.004  0.010

     485    486    487    488    489    490    491    492    493    494   \
25  0.100  0.040 -0.032 -0.048 -0.053  0.408  0.451 -0.038 -0.048  0.063
16  0.105  0.066  0.006 -0.047 -0.065 -0.186  0.074 -0.051 -0.061 -0.060
23  0.037  0.067  0.038 -0.028 -0.040 -0.019 -0.025 -0.034 -0.036 -0.025

     495    496    497    498    499    500    501    502    503    504   \
25 -0.055 -0.030 -0.063  0.006 -0.042  0.006 -0.001  0.007 -0.024 -0.036
16 -0.061 -0.046 -0.081 -0.021 -0.059  0.006 -0.001  0.002 -0.028 -0.034
23 -0.076 -0.031 -0.063 -0.006 -0.048  0.011  0.000  0.026 -0.012 -0.038

     505    506    507    508    509    510    511    512    513    514   \
25  0.022  0.021 -0.021 -0.095  0.009  0.011 -0.061 -0.004  0.010  0.012
16  0.014  0.019 -0.017 -0.095  0.009  0.007 -0.063 -0.003  0.007  0.011
23  0.033  0.034 -0.037 -0.082  0.021  0.026 -0.055 -0.006  0.019  0.017

     515    516    517    518    519    520    521    522    523    524   \
25  0.009  0.051  0.054  0.042  0.028 -0.037 -0.012  0.004  0.000  0.025
16  0.008  0.046  0.050  0.038  0.024 -0.037 -0.014  0.004 -0.001  0.025
23  0.014  0.065  0.069  0.030  0.043 -0.026 -0.009 -0.002 -0.001  0.029

     525    526    527    528    529    530    531    532    533    534   \
25 -0.038 -0.002 -0.010 -0.022 -0.002  0.023 -0.001  0.020  0.017 -0.032
16 -0.036 -0.001 -0.011 -0.023 -0.003  0.021 -0.001  0.019  0.017 -0.027
23 -0.037 -0.003 -0.005 -0.029 -0.004  0.023  0.006  0.030  0.025 -0.035

     535    536    537    538    539    540    541    542    543    544   \
25  0.024  0.023  0.015  0.026  0.104  0.004  0.025  0.028  0.037  0.009
16  0.017  0.024  0.014  0.024  0.099  0.010  0.025  0.027  0.027  0.008
23  0.030  0.022  0.014  0.033  0.134 -0.011  0.031  0.041  0.061  0.006

     545    546    547    548    549    550    551       552       553   \
25  0.086  0.026  0.014  0.019  0.801 -0.002 -0.055 -0.007522 -0.004286
16  0.094  0.027  0.008  0.030  0.797  0.005 -0.053 -0.192652 -0.000857
23  0.100  0.053  0.025  0.005  0.713 -0.021 -0.057 -0.003304 -0.013286

        554       555     556    557    558    559    560    561    562   \
25  0.011737  0.038909  0.0602  0.155  0.109  0.211  0.225  0.371  0.019
16 -0.596526  0.056273  0.0564  0.152  0.100  0.199  0.222  0.368  0.020
23  0.014053  0.033636  0.0318  0.195  0.119  0.241  0.270  0.405  0.012

     563    564    565    566    567    568    569    570    571    572   \
25  0.166  0.212  0.415  0.098  0.220  0.219  0.199  0.174  0.277  0.112
16  0.158  0.197  0.415  0.094  0.202  0.199  0.178  0.053  0.269  0.111
23  0.192  0.269  0.420  0.124  0.285  0.278  0.256  0.186  0.285  0.111

     573    574    575    576    577    578    579    580    581    582   \
25  0.093  0.129  0.190  0.311  0.351  0.026 -0.056  0.025  0.087 -0.026
16  0.087  0.116  0.175  0.235  0.211  0.022 -0.054  0.019  0.079 -0.042
23  0.117  0.164  0.230  0.316  0.348  0.032 -0.045  0.046  0.114 -0.014

     583    584    585    586    587    588    589    590    591    592   \
25  0.061  0.031  0.020 -0.258 -0.092 -0.019 -0.132 -0.180  0.071 -0.118
16  0.031  0.030  0.021 -0.251 -0.089 -0.019 -0.327 -0.239  0.068 -0.117
23  0.069  0.039  0.032 -0.270 -0.089 -0.006 -0.108 -0.163  0.081 -0.087

     593    594    595    596    597    598    599    600    601    602   \
25 -0.247  0.021  0.063  0.049  0.012 -0.007  0.002  0.043  0.094 -0.026
16 -0.248  0.012  0.051 -0.031 -0.048 -0.013 -0.005  0.039  0.050 -0.027
23 -0.225  0.064  0.108  0.086  0.038  0.010  0.016  0.076  0.317  0.008

     603    604    605    606    607    608    609    610    611    612   \
25  0.015  0.026  0.018  0.005  0.319  0.303  0.096  0.136  0.025  0.023
16  0.013  0.005  0.000 -0.003  0.233  0.239  0.069  0.028  0.013  0.020
23  0.054  0.062  0.046  0.026  0.612  0.411  0.797  0.204  0.061  0.025

     613    614    615    616    617    618    619    620    621    622   \
25  0.082  0.042  0.121  0.147  0.160  0.047  0.082  0.085 -0.001  0.011
16  0.054  0.002  0.095  0.220  0.040  0.032  0.054  0.085 -0.002  0.008
23  0.153  0.073  0.138  0.171  0.181  0.101  0.143  0.084  0.003  0.019

     623    624    625    626    627    628    629    630    631    632   \
25  0.020  0.020  0.012  0.012  0.017  0.022  0.026  0.006  0.020 -0.003
16  0.015  0.016  0.006  0.007  0.012  0.017  0.020  0.001  0.011 -0.004
23  0.040  0.028  0.028  0.022  0.033  0.038  0.045  0.016  0.040  0.006

     633    634    635    636    637    638    639    640    641    642   \
25  0.002  0.018  0.014  0.013  0.014 -0.035 -0.011  0.016  0.028  0.004
16  0.002  0.013  0.011  0.013  0.013 -0.033 -0.015  0.008  0.022  0.002
23  0.013  0.036  0.020  0.016  0.023 -0.030 -0.004  0.027  0.050  0.012

     643    644    645    646    647    648    649    650    651    652   \
25 -0.006 -0.019  0.001  0.010 -0.025 -0.008  0.002  0.019  0.005  0.024
16 -0.010 -0.020 -0.001  0.008 -0.033 -0.008  0.001  0.008  0.001  0.017
23 -0.002 -0.012  0.006  0.017  0.011 -0.008  0.008  0.031  0.019  0.042

     653    654    655    656    657    658    659    660    661    662   \
25 -0.031  0.015  0.013 -0.003  0.015  0.007  0.025  0.034  0.031  0.025
16 -0.034  0.009  0.010 -0.015  0.017  0.009  0.012  0.036  0.029  0.027
23 -0.025  0.034  0.031  0.010  0.038  0.015  0.035  0.058  0.058  0.040


In [24]:
# The library was referred from https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
# Received ChatGPT 4o's help when forming nested loop

#What to fix? 
# The dataset to be trained with needs to have X and Y combined to begin with, so let's start with df 
# Then we could do imputation 

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

# Extract features and target variable
X = x_df.copy()  # Imputed feature dataset
# y = x_df_result  # Target column from df

# List of parameter values to try
weights_list = ["uniform", "distance"]
neighbors_list = [1, 3, 5, 9, 11, 15, 21]
dataset_types = ["unbalanced", "balanced"]

# To store results
results = []

# Loop over dataset types (unbalanced and balanced)
for dataset_type in dataset_types:
    if dataset_type == "unbalanced":
        X_current = X.copy()
        y_current = y.copy()
    else:
        # Create a balanced dataset using undersampling:
        balanced_df = df.copy()
        min_count = balanced_df["result"].value_counts().min()
        balanced_df = balanced_df.groupby("result", group_keys=False).apply(
            lambda grp: grp.sample(n=min_count, random_state=42)
        ).reset_index(drop=True)

        # Extract the balanced X and y
        X_current = balanced_df.drop(columns=["result"])
        y_current = balanced_df["result"]

    # Split the dataset into training and testing sets using a 70-30 split
    print(X_current.shape, y_current.shape)

    X_train, X_test, y_train, y_test = train_test_split(
        X_current, y_current, test_size=0.3, random_state=22222, stratify=y_current
    )

    # Loop over the weighting schemes and n_neighbors values
    for weight in weights_list:
        for n in neighbors_list:
            # Create the KNeighborsClassifier with the given parameters
            neigh = KNeighborsClassifier(n_neighbors=n, weights=weight)
            neigh.fit(X_train, y_train)

            # Evaluate the model
            train_score = neigh.score(X_train, y_train)
            test_score = neigh.score(X_test, y_test)

            # Store the results
            results.append({
                "dataset": dataset_type,
                "weight": weight,
                "n_neighbors": n,
                "train_score": train_score,
                "test_score": test_score
            })

# Convert results to a DataFrame
results_df = pd.DataFrame(results)
print(results_df)

(1895, 5408) (1895,)

/tmp/ipykernel_112661/1472857962.py:32: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  balanced_df = balanced_df.groupby("result", group_keys=False).apply(

(38, 5408) (38,)
       dataset    weight  n_neighbors  train_score  test_score
0   unbalanced   uniform            1     1.000000    0.984183
1   unbalanced   uniform            3     0.991704    0.991213
2   unbalanced   uniform            5     0.989442    0.992970
3   unbalanced   uniform            9     0.990196    0.989455
4   unbalanced   uniform           11     0.990196    0.989455
5   unbalanced   uniform           15     0.990196    0.989455
6   unbalanced   uniform           21     0.990196    0.989455
7   unbalanced  distance            1     1.000000    0.984183
8   unbalanced  distance            3     1.000000    0.991213
9   unbalanced  distance            5     1.000000    0.994728
10  unbalanced  distance            9     1.000000    0.989455
11  unbalanced  distance           11     1.000000    0.989455
12  unbalanced  distance           15     1.000000    0.989455
13  unbalanced  distance           21     1.000000    0.989455
14    balanced   uniform            1     1.000000    0.583333
15    balanced   uniform            3     0.923077    0.500000
16    balanced   uniform            5     0.807692    0.583333
17    balanced   uniform            9     0.730769    0.500000
18    balanced   uniform           11     0.807692    0.500000
19    balanced   uniform           15     0.730769    0.416667
20    balanced   uniform           21     0.769231    0.500000
21    balanced  distance            1     1.000000    0.583333
22    balanced  distance            3     1.000000    0.500000
23    balanced  distance            5     1.000000    0.583333
24    balanced  distance            9     1.000000    0.416667
25    balanced  distance           11     1.000000    0.500000
26    balanced  distance           15     1.000000    0.416667
27    balanced  distance           21     1.000000    0.500000

### When Do I Normalize Data??

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

### Scikit-Learn's kNN library explanation
##### https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html